/* 금옥중3 능률(김성곤) Lesson 5 — Environmental Innovations 챕터 저작 데이터
 * 실행: node _author-L5.mjs  → data/L5/{1..4}.json */
import { writeChapter } from './_author.mjs';
import { SOURCE } from './_SOURCE-L5.js';

const LIGHT = 'natural soft diffused daylight, bright overcast sky, high-key exposure, low contrast, clean bright palette';
const NO = '--no text, letters, words, logo, watermark, people, person, hands, faces, sunset, golden hour, night, dark moody grading, heavy shadows';

const chapters = [
  /* ── Ch1 ─────────────────────────────────────────── */
  {
    no: 1, type: '주제', answer: 2,
    question: '다음 글의 주제로 가장 적절한 것은?',
    summary: '환경을 보호할 방법을 찾는 것은 중요하고, 어떤 사람들은 지구를 구할 창의적인 방법을 찾아냈어요. 그 예가 멕시코 칸쿤의 수중 박물관이에요. 미술학 교수 Rosa Allison 박사에 따르면, 칸쿤에는 해마다 480만 명의 관광객이 찾아와 바닷속 해양 생물을 구경하는데, 이런 관광 활동이 칸쿤 인근 바다의 일부를 심각하게 훼손하고 있어요.',
    mainIdea: 'People are finding creative ways to protect the environment, and one example begins in Cancun, where tourism is seriously damaging the sea.',
    titleEn: 'Join Hands, Save the Earth: The Problem in Cancun’s Sea',
    ko: [
      '우리가 환경을 보호하는 방법을 찾는 것은 중요하다.',
      '몇몇 사람들은 지구를 구하기 위한 창의적인 방법들을 찾아냈다.',
      '한 예로 멕시코 칸쿤에 있는 수중 박물관이 있다.',
      '미술학 교수인 Rosa Allison 박사를 만나 이 특별한 박물관에 관한 설명을 들어 보자.',
      '칸쿤은 매년 480만 명의 관광객이 여행하는 도시입니다.',
      '그곳에서 하는 가장 인기 있는 활동 중 하나는 물속에서 그 지역의 아름다운 해양 생물을 보는 것입니다.',
      '하지만 관광 활동들은 칸쿤 인근의 바다 일부를 심각하게 훼손하고 있습니다.',
    ],
    choices: [
      ['멕시코 칸쿤이 세계적인 관광지가 된 역사적 배경', '칸쿤이 **관광객이 많은 도시**라는 사실은 나오지만, **관광지가 된 역사**는 전혀 다루지 않는다.'],
      ['환경 보호를 위한 창의적 노력과 칸쿤 바다가 처한 위기', '앞 단락은 **창의적인 환경 보호 방법**을, 뒤 단락은 **관광으로 훼손되는 칸쿤의 바다**를 소개한다. 두 내용을 모두 담은 **정답**이다.'],
      ['미술학 교수가 되기 위해 필요한 자질', 'Rosa Allison 박사는 **설명을 들려줄 사람**으로 소개될 뿐, 교수의 **자질**은 나오지 않는다.'],
      ['해양 생물을 가까이에서 관찰하는 방법', '물속에서 해양 생물을 보는 것은 **인기 활동**으로 언급될 뿐, **관찰 방법**을 설명하지 않는다.'],
      ['관광 산업이 지역 경제에 주는 이점', '글은 관광의 **이점**이 아니라 관광이 바다를 **훼손한다**({seriously damaging})는 문제를 말한다.'],
    ],
    vocab: [
      'important|형|중요한|significant, essential|unimportant 중요하지 않은|importance 중요성',
      'protect|동|보호하다|guard, save|harm 해치다|protection 보호',
      'environment|명|환경|nature, surroundings|—|environmental 환경의',
      'creative|형|창의적인|inventive, original|ordinary 평범한|create 창조하다 / creativity 창의성',
      'underwater|형|물속의, 수중의|undersea|above water 물 위의|water 물',
      'museum|명|박물관|gallery|—|—',
      'professor|명|교수|lecturer|student 학생|—',
      'explanation|명|설명|description|—|explain 설명하다',
      'special|형|특별한|unique, unusual|ordinary 평범한|specially 특별히',
      'million|명|백만|—|—|millions of 수백만의',
      'tourist|명|관광객|traveler, visitor|local 현지인|tour 관광 / tourism 관광업',
      'popular|형|인기 있는|well-liked|unpopular 인기 없는|popularity 인기',
      'activity|명|활동|action|—|active 활동적인',
      'sea life|명|해양 생물|marine life|—|—',
      'seriously|부|심각하게|badly, severely|slightly 약간|serious 심각한',
      'damage|동|손상시키다, 훼손하다|harm, hurt|repair 수리하다|damage 손상(명사)',
    ],
    flow: [
      ['🌍', '문제 제기 — 환경 보호의 중요성', '{It is important for us to ~} 로 **환경 보호 방법을 찾는 것이 중요하다**는 글 전체의 출발점을 제시한다.'],
      ['💡', '창의적인 해결 사례 예고', '{Some people have found creative ways} — **창의적인 방법**을 찾은 사람들이 있다며, 그 **첫 번째 예**로 칸쿤의 **수중 박물관**을 소개한다.'],
      ['🎤', '전문가 등장 — Rosa Allison 박사', '{Let’s meet ~ and listen to ~} 로 화자가 바뀐다. 이후 내용은 **미술학 교수의 설명**이다.'],
      ['⚠️', '위기 — 관광이 바다를 훼손', '480만 명의 관광객이 해양 생물을 보러 오지만, {However} 뒤에서 **관광 활동이 바다를 심각하게 훼손한다**는 **문제**가 드러난다.'],
    ],
    cards: [
      {
        covers: [1, 2],
        en: '[g:It is important] [h:for us] [r:to find ways] to protect the environment. | Some people [g:have found] [h:creative ways] [r:to save the earth].',
        ko: '우리가 환경을 보호하는 방법을 찾는 것은 중요하다. | 몇몇 사람들은 지구를 구하기 위한 창의적인 방법들을 찾아냈다.',
        note: '**해석 도움** — {It} 은 **가주어**, 진짜 주어는 {to find ways ~} 이다. {for us} 는 to부정사의 **의미상 주어**라서 "**우리가** 찾는 것"으로 해석한다.',
        points: [
          ['grammar', '**가주어 It ~ 진주어 to부정사** — {It is important (for us) to find ~}. 긴 to부정사 주어를 뒤로 보내고 그 자리에 {It} 을 둔다. {It} 을 "그것"으로 해석하지 않는다.'],
          ['grammar', '**의미상 주어 for + 목적격** — to부정사 동작의 주체를 밝힐 때 {for us} 처럼 쓴다. 단, {kind, nice} 같은 **성격 형용사** 뒤에는 {of + 목적격}을 쓴다.'],
          ['grammar', '**현재완료 have found** — 과거에 찾아서 **지금 그 방법을 갖고 있다**는 결과를 나타낸다. {ways to save} 의 to부정사는 **형용사적 용법**(구할 방법).'],
        ],
      },
      {
        covers: [3, 4],
        en: '[h:One example] is an underwater museum in Cancun, Mexico. | [g:Let’s meet] Dr. Rosa Allison, [h:an art professor], [g:and listen to] her explanation about the special museum.',
        note: '**해석 도움** — {Dr. Rosa Allison, an art professor} 는 콤마로 **같은 사람**을 다시 설명하는 **동격**이다. {Let’s} 뒤에 동사원형 {meet} 과 {listen} 이 {and} 로 나란히 이어진다.',
        points: [
          ['grammar', '**Let’s + 동사원형** — "~하자"라는 **제안**. {Let’s meet ~ and listen to ~} 처럼 동사원형 두 개가 **병렬**로 연결된다.'],
          ['grammar', '**동격의 콤마** — {Dr. Rosa Allison, an art professor,} 에서 콤마 사이 명사구가 앞 사람을 **보충 설명**한다. "미술학 교수인 Rosa Allison 박사"로 해석한다.'],
          ['reading', '**예시의 신호 One example is ~** — 앞 문장의 **창의적인 방법**에 대한 **구체적 사례**가 시작된다는 표지다.'],
        ],
      },
      {
        covers: [5],
        en: 'Cancun is a city | [g:where] 4.8 million tourists travel every year.',
        ko: '칸쿤은 도시입니다 | 매년 480만 명의 관광객이 여행하는',
        note: '**해석 도움** — {where} 는 장소 명사 {a city} 를 꾸미는 **관계부사**다. "매년 480만 명의 관광객이 **여행하는 도시**"처럼 뒤에서 앞으로 해석한다. {4.8 million} 은 **480만**.',
        points: [
          ['grammar', '**관계부사 where** — 선행사가 **장소**({a city})일 때 쓴다. {where} 뒤에는 **완전한 문장**(주어 + 동사)이 온다. {= in which} 로 바꿔 쓸 수 있다.'],
          ['vocab', '**숫자 읽기 4.8 million** — {million} 은 백만. 4.8 × 100만 = **480만**. 숫자 뒤 {million} 에는 **-s를 붙이지 않는다**({millions of} 는 "수백만의").'],
        ],
      },
      {
        covers: [6],
        en: '[h:One of the most popular activities] | [r:to do there] | [g:is] looking at the area’s beautiful sea life underwater.',
        ko: '가장 인기 있는 활동 중 하나는 | 그곳에서 하는 | 물속에서 그 지역의 아름다운 해양 생물을 보는 것입니다.',
        note: '**해석 도움** — 주어는 {One of the most popular activities to do there} 전체이고 동사는 {is} 다. {looking at ~} 은 **동명사**로 "~을 보는 것"이라는 **보어**다.',
        points: [
          ['grammar', '**one of the + 최상급 + 복수명사** — "가장 ~한 것 중 하나". 주어의 핵심은 {One} 이므로 동사는 **단수 is**다(activities에 속지 말 것).'],
          ['grammar', '**to부정사의 형용사적 용법** — {activities to do there} 는 "그곳에서 **할** 활동". 명사를 뒤에서 꾸민다.'],
          ['grammar', '**동명사 보어** — {is looking at} 은 진행형이 아니라 **be동사 + 동명사 보어**다. "~하는 것이다"로 해석한다.'],
        ],
      },
      {
        covers: [7],
        en: '[r:However], tourist activities [g:are seriously damaging] parts of the sea near Cancun.',
        ko: '하지만 관광 활동들은 | 칸쿤 인근의 바다 일부를 심각하게 훼손하고 있습니다.',
        note: '**해석 도움** — {However} 는 앞 내용(아름다운 해양 생물 관광)과 **반대되는 문제**를 끌어내는 연결어다. {are damaging} 은 **현재진행형**으로 지금도 훼손이 **계속되고 있음**을 강조한다.',
        points: [
          ['reading', '**역접 However** — 관광의 **매력** → 관광의 **피해**로 방향이 바뀐다. 다음 단락에서 이 **문제를 해결하는 방법**이 이어진다.'],
          ['grammar', '**현재진행형 + 부사 seriously** — {are seriously damaging}. 부사는 **be동사와 -ing 사이**에 놓여 동사를 꾸민다.'],
          ['vocab', '**parts of the sea** — 바다 **전체**가 아니라 **일부**가 훼손된다는 점이 중요하다. 그래서 다음 단락에서 **다른 쪽 바다**로 관광객을 유인하는 해결책이 나온다.'],
        ],
      },
    ],
    prompt: `Photorealistic aerial travel photograph, wide banner composition. The shallow turquoise Caribbean sea off Cancun, Mexico, seen from above: a coral reef visible through crystal-clear water, and several small white tour boats crowded together and anchored right over the reef, showing tourist pressure on the sea. White sand coastline with a row of hotels along the left edge. ${LIGHT}, vivid turquoise and white. ${NO}, statues, sculptures --ar 16:5 --v 8.1`,
  },

  /* ── Ch2 ─────────────────────────────────────────── */
  {
    no: 2, type: '내용일치', answer: 4,
    question: '다음 글의 내용과 일치하는 것은?',
    summary: '예술가들은 관광객을 바다의 다른 곳으로 유인하면 죽어 가는 지역이 회복할 시간을 가질 수 있다고 생각했어요. 그래서 해양 생물이 죽어 가는 곳에서 떨어진 곳에, 수면 아래 약 14미터 깊이로 500개의 조각상이 있는 수중 박물관을 만들었어요. 조각상은 해양 생물이 살 수 있는 재료로 만들어져 동식물에게 추가 서식처를 제공하고, 시간이 지나면 다양한 해양 생물이 자라 작품을 독특하게 만들어요. 사람들이 해양 생물의 풍부함을 깨달으면 바다를 지키는 것이 얼마나 중요한지 이해하게 될 거예요.',
    mainIdea: 'Artists built an underwater museum of statues away from the dying areas, so that tourists go elsewhere and the statues become new homes for sea life.',
    titleEn: 'An Underwater Museum That Gives the Sea Time to Heal',
    ko: [
      '이를 방지하기 위해, 예술가들이 무언가 재미난 일을 했습니다.',
      '그들은 만약 관광객들을 바다의 다른 쪽으로 유인한다면, 그 죽어가는 지역이 호전될 시간을 가질 수 있을 것이라 생각했습니다.',
      '그들은 해양 생물이 죽어가는 지역으로부터 떨어진 곳에 수중 박물관을 만들었습니다.',
      '그곳은 해수면에서 약 14미터 아래에 있으며 500개의 조각상이 있습니다.',
      '그 조각상들은 해양 생물이 살아갈 수 있게 하는 재료들로 만들어졌습니다.',
      '그것들은 동식물이 살 수 있는 장소를 추가로 제공합니다.',
      '시간이 지나면서 많은 종류의 해양 생물이 조각상 위에서 자랄 것인데, 이는 그 예술 작품을 독특하게 만들 것입니다.',
      '예술가들은 사람들이 조각상에서 다양한 해양 생물을 보길 원합니다.',
      '만약 사람들이 해양 생물이 얼마나 풍부한지 깨닫는다면, 그들은 바다를 지키는 것이 얼마나 중요한지 이해하게 될 것입니다.',
    ],
    choices: [
      ['수중 박물관은 해양 생물이 죽어 가는 지역 한가운데에 세워졌다.', '{away from the places where sea life was dying} — 박물관은 해양 생물이 죽어 가는 곳에서 **떨어진 곳**에 만들어졌다. **정반대**다.'],
      ['수중 박물관은 해수면에서 약 500미터 아래에 있다.', '깊이는 **약 14미터**이고, **500**은 조각상의 **개수**다. 숫자를 바꿔 끼운 오답이다.'],
      ['조각상은 해양 생물이 달라붙지 못하는 재료로 만들어졌다.', '{materials that support sea life} — 조각상은 해양 생물이 **살 수 있게 돕는** 재료로 만들어졌다.'],
      ['시간이 지나면 조각상 위에 여러 종류의 해양 생물이 자라게 된다.', '{Over time, many types of sea life will grow on the statues} 와 **일치**한다. **정답**.'],
      ['예술가들은 관광객이 바다에 들어가지 못하게 하려고 박물관을 만들었다.', '관광객을 **막으려는** 것이 아니라 바다의 **다른 곳으로 유인**하려는({attracted tourists to a different part}) 것이다.'],
    ],
    vocab: [
      'prevent|동|막다, 방지하다|stop, avoid|allow 허락하다|prevention 예방',
      'attract|동|(마음을) 끌다, 유인하다|draw, pull|drive away 쫓아내다|attraction 명소 / attractive 매력적인',
      'different|형|다른|other, another|same 같은|difference 차이',
      'dying|형|죽어 가는|fading|living 살아 있는|die 죽다 / death 죽음',
      'get better|숙|나아지다, 호전되다|recover, improve|get worse 악화되다|—',
      'away from|숙|~에서 떨어져|far from|near ~ 가까이|—',
      'surface|명|수면, 표면|top|bottom 바닥|—',
      'contain|동|포함하다, 담고 있다|include, hold|exclude 제외하다|container 용기',
      'statue|명|조각상|sculpture, figure|—|—',
      'material|명|재료, 물질|substance|—|—',
      'support|동|지탱하다, 살 수 있게 하다|help, sustain|harm 해치다|supportive 지원하는',
      'provide|동|제공하다|give, offer|take away 빼앗다|provider 제공자',
      'additional|형|추가의|extra, more|—|add 더하다 / addition 추가',
      'over time|숙|시간이 지나면서|gradually|—|—',
      'unique|형|독특한, 유일한|special, one of a kind|common 흔한|uniqueness 독특함',
      'a variety of|숙|다양한|various, many kinds of|—|vary 다르다 / variety 다양성',
      'realize|동|깨닫다|understand, notice|overlook 간과하다|realization 깨달음',
      'rich|형|풍부한|plentiful, abundant|poor 빈약한|richness 풍부함',
    ],
    flow: [
      ['🎨', '해결책 — 예술가들의 아이디어', '{To prevent this} 의 {this} 는 앞 단락의 **관광으로 인한 바다 훼손**이다. 예술가들은 관광객을 **다른 곳으로 유인**하면 죽어 가는 지역이 **회복할 시간**을 얻는다고 생각했다.'],
      ['🗿', '실행 — 수중 박물관 건립', '해양 생물이 죽어 가는 곳에서 **떨어진 곳**, 수면 아래 **약 14미터**에 **500개의 조각상**이 있는 박물관을 만들었다.'],
      ['🐠', '조각상의 역할 — 새로운 서식처', '조각상은 **해양 생물이 살 수 있는 재료**로 만들어져 동식물에게 **추가 서식처**가 된다. 시간이 지나면 생물이 자라 **작품이 독특해진다**.'],
      ['💙', '궁극적 목표 — 바다 보호 인식', '사람들이 **해양 생물의 풍부함**을 깨달으면 **바다를 지키는 것이 얼마나 중요한지** 이해하게 된다는 것이 예술가들의 바람이다.'],
    ],
    cards: [
      {
        covers: [1],
        en: '[r:To prevent this], | artists did [g:something interesting].',
        ko: '이를 방지하기 위해, | 예술가들이 무언가 재미난 일을 했습니다.',
        note: '**해석 도움** — {this} 는 앞 단락 마지막 문장, 즉 **관광 활동이 바다를 훼손하는 것**을 가리킨다. {To prevent} 는 "~하기 위해"라는 **목적**이다.',
        points: [
          ['grammar', '**목적의 to부정사** — 문장 맨 앞 {To prevent this,} 는 "이것을 **막기 위해**". {In order to prevent this} 로 바꿔 쓸 수 있다.'],
          ['grammar', '**-thing + 형용사** — {something interesting}. {something, anything, nothing} 처럼 **-thing** 으로 끝나는 대명사는 형용사가 **뒤에서** 꾸민다({interesting something} ✗).'],
        ],
      },
      {
        covers: [2],
        en: 'They thought | [g:if they attracted] tourists to a different part of the sea, | the dying areas [g:could have] time [r:to get better].',
        ko: '그들은 생각했습니다 | 만약 관광객들을 바다의 다른 쪽으로 유인한다면 | 그 죽어가는 지역이 호전될 시간을 가질 수 있을 것이라고',
        note: '**해석 도움** — {thought} 뒤에 접속사 {that} 이 **생략**되어 있고, 그 안에 {if} 조건절이 들어 있다. 과거 시점({thought})에 맞춰 {attracted, could} 로 **시제가 일치**되었다.',
        points: [
          ['grammar', '**목적어절 속 조건문** — {They thought (that) [if ~, the dying areas could ~]}. 생각의 **내용 전체**가 {thought} 의 목적어다.'],
          ['grammar', '**시제 일치** — 주절이 과거({thought})라서 종속절도 {attracted, could have} 처럼 과거형이 된다. 가정법이 아니라 **과거의 판단**을 전하는 것이다.'],
          ['vocab', '**time to get better** — to부정사가 {time} 을 꾸미는 **형용사적 용법**. "**호전될** 시간". {get better} 는 "(상태가) 나아지다".'],
        ],
      },
      {
        covers: [3, 4],
        en: 'They made an underwater museum [h:away from the places] [g:where sea life was dying]. | [h:It’s about 14 meters] below the surface [r:and contains] 500 statues.',
        note: '**해석 도움** — {where sea life was dying} 은 {the places} 를 꾸미는 **관계부사절**이다. 둘째 문장의 주어 {It} 은 **수중 박물관**이며 동사 {’s(is)} 와 {contains} 가 {and} 로 이어진다.',
        points: [
          ['grammar', '**관계부사 where** — 선행사 {the places}(장소) + {where} + 완전한 절. "해양 생물이 **죽어 가던 곳**".'],
          ['grammar', '**동사 병렬** — {It’s about 14 meters below ~ and contains 500 statues}. 주어 하나에 동사 {is} 와 {contains} 가 나란히 온다. 3인칭 단수라 {contains}.'],
          ['reading', '**숫자 정보 주의** — **14미터**(깊이)와 **500개**(조각상 수)는 내용일치 문제에서 **서로 바꿔 내기 쉬운** 정보다.'],
        ],
      },
      {
        covers: [5, 6],
        en: 'The statues [g:are made from] materials [g:that support] sea life. | They provide [h:additional places] [r:for plants and animals] [r:to live on].',
        note: '**해석 도움** — {are made from} 은 **수동태**(~로 만들어지다). {that support sea life} 는 {materials} 를 꾸미는 **주격 관계대명사절**이다. {for plants and animals} 는 {to live on} 의 **의미상 주어**다.',
        points: [
          ['grammar', '**be made from vs. be made of** — {from} 은 재료가 **변해서 원래 모습이 안 보일 때**, {of} 는 재료의 **성질이 그대로 보일 때** 주로 쓴다.'],
          ['grammar', '**주격 관계대명사 that** — {materials that support sea life}. 선행사가 복수라 동사도 **support**(복수형)다.'],
          ['grammar', '**to부정사 + 전치사** — {places to live on}. "~ **위에서** 살 장소"이므로 {live on places} 의 **전치사 on을 빠뜨리면 안 된다**.'],
        ],
      },
      {
        covers: [7],
        en: '[r:Over time], many types of sea life will grow on the statues, | [g:which] will [g:make the artwork unique].',
        ko: '시간이 지나면서 많은 종류의 해양 생물이 조각상 위에서 자랄 것인데, | 이는 그 예술 작품을 독특하게 만들 것입니다.',
        note: '**해석 도움** — 콤마 뒤 {which} 는 앞 **절 전체**(해양 생물이 조각상 위에서 자라는 것)를 받는 **계속적 용법**이다. "그리고 그것은 ~"으로 이어서 해석한다.',
        points: [
          ['grammar', '**계속적 용법의 which** — {, which} 는 **앞 문장 전체**를 선행사로 받을 수 있다. {= and it} 으로 바꿔 쓸 수 있고, **that으로 바꿀 수 없다**.'],
          ['grammar', '**5형식 make + 목적어 + 형용사** — {make the artwork unique} "작품을 **독특하게** 만들다". 목적격보어 자리에 **부사(uniquely)를 쓰지 않는다**.'],
        ],
      },
      {
        covers: [8],
        en: 'The artists [g:want people to see] [h:a variety of] sea life on the statues.',
        ko: '예술가들은 원합니다 | 사람들이 조각상에서 다양한 해양 생물을 보길',
        note: '**해석 도움** — {want + 목적어 + to부정사} 는 "(목적어)가 ~하기를 원하다". 보는 사람은 예술가가 아니라 **people** 이다.',
        points: [
          ['grammar', '**want + 목적어 + to부정사** — 목적격보어로 **to부정사**를 쓰는 동사: {want, ask, tell, allow, expect}. {want people see} ✗.'],
          ['vocab', '**a variety of + 복수명사** — "다양한 ~". {sea life} 처럼 셀 수 없는 명사와도 쓴다. {various} 로 바꿔 쓸 수 있다.'],
        ],
      },
      {
        covers: [9],
        en: '[g:If people realize] [h:how rich sea life is], | they [g:will understand] [h:how important] [r:it is to save the sea].',
        ko: '만약 사람들이 해양 생물이 얼마나 풍부한지 깨닫는다면, | 그들은 바다를 지키는 것이 얼마나 중요한지 이해하게 될 것입니다.',
        note: '**해석 도움** — 간접의문문이 **두 번** 나온다. {how rich sea life is} 와 {how important it is to save the sea} 모두 **“how + 형용사 + 주어 + 동사”** 어순이다. 뒤의 {it} 은 **가주어**, {to save the sea} 가 **진주어**다.',
        points: [
          ['grammar', '**조건의 부사절은 현재시제** — {If people realize ~, they will understand ~}. 미래의 일이라도 **if절에는 will을 쓰지 않는다**.'],
          ['grammar', '**간접의문문 how + 형용사 + 주어 + 동사** — {how rich sea life is}(○) / {how rich is sea life}(✗). 문장 안에 들어가면 **평서문 어순**.'],
          ['reading', '**글의 핵심 메시지** — 박물관의 최종 목적은 관광객 분산을 넘어, 사람들이 **바다를 지키는 것의 중요성**을 깨닫게 하는 것이다.'],
        ],
      },
    ],
    prompt: `Photorealistic underwater photograph, wide banner composition. An underwater sculpture museum on a sandy seabed about 14 meters deep: dozens of life-size grey concrete human statues standing in neat rows, their surfaces partly covered with young coral, green algae and small sponges, a few small colorful reef fish swimming between them. Clear blue water with gentle light rays from the bright surface above. ${LIGHT}, clean bright blue palette. --no text, letters, logo, watermark, diver, swimmer, living people, hands, boat, murky water, sunset, night, dark moody grading, heavy shadows --ar 16:5 --v 8.1`,
  },

  /* ── Ch3 ─────────────────────────────────────────── */
  {
    no: 3, type: '제목', answer: 1,
    question: '다음 글의 제목으로 가장 적절한 것은?',
    summary: '싱가포르에서는 사람들이 땅 위의 환경을 보호하기 위해 건축을 이용하고 있어요. 건축가 Rajesh Khan에 따르면, 싱가포르는 일 년 내내 더워서 대부분의 건물이 에어컨을 필요로 하는데, 에어컨은 에너지를 많이 쓰고 기후 변화의 원인이 돼요. 그래서 건축가들은 에어컨을 덜 쓰면서도 시원한 친환경 건물을 설계하기 시작했어요. 많은 건물이 개방형 구조로 설계되어 바깥 공기가 건물 전체로 흐르고, 이 자연적인 공기 흐름 덕분에 건물이 시원하게 유지돼요.',
    mainIdea: 'Architects in Singapore design eco-friendly buildings with open structures, so natural air flow keeps them cool with less air conditioning.',
    titleEn: 'Staying Cool without Much Air Conditioning: Open Buildings in Singapore',
    ko: [
      '싱가포르에서는 사람들이 땅 위에서 환경을 보호하기 위해 건축을 이용하고 있다.',
      '건축가인 Rajesh Khan이 친환경 건물에 대해 말하는 것을 들어 보자.',
      '싱가포르는 일 년 내내 덥습니다.',
      '대부분의 건물들이 에어컨 가동을 필요로 하는데, 그것은 많은 에너지를 사용하며 기후 변화의 원인이 됩니다.',
      '그것이 싱가포르의 건축가들이 에어컨을 덜 사용하면서도 실내는 여전히 시원한 친환경 건물을 설계하기 시작한 이유입니다.',
      '예를 들어, 싱가포르의 많은 건물은 개방형 구조를 갖도록 설계됩니다.',
      '이러한 구조는 바깥 공기가 건물 구석구석까지 이동할 수 있게 해 줍니다.',
      '이러한 자연적인 공기의 흐름은 이 건물들이 시원하게 유지되는 방법입니다.',
    ],
    choices: [
      ['Letting the Wind In: How Singapore’s Buildings Stay Cool', '**개방형 구조**로 바깥 공기가 흐르게 해 **에어컨 없이도 시원한** 싱가포르 건물을 잘 담았다. **정답**.'],
      ['Why Singapore Needs More Air Conditioners', '글은 에어컨을 **덜 쓰는**({use less air conditioning}) 방법을 말한다. **정반대** 방향이다.'],
      ['The Best Season to Travel to Singapore', '싱가포르는 **일 년 내내 덥다**는 배경 정보일 뿐, **여행 시기**는 다루지 않는다.'],
      ['How Air Conditioning Was First Invented', '에어컨의 **발명 역사**는 나오지 않는다. 에어컨은 **문제의 원인**으로만 언급된다.'],
      ['Architects Who Designed Famous Towers', '특정 **유명 건물이나 건축가의 업적**이 아니라 **친환경 설계 원리**를 설명하는 글이다.'],
    ],
    vocab: [
      'architecture|명|건축, 건축 양식|building design|—|architect 건축가 / architectural 건축의',
      'environment|명|환경|surroundings, nature|—|environmental 환경의',
      'architect|명|건축가|designer|—|architecture 건축',
      'eco-friendly|형|친환경적인|green, environmentally friendly|harmful 해로운|ecology 생태계',
      'throughout|전|~ 내내, ~ 곳곳에|all through|—|—',
      'air conditioning|명|에어컨 (가동), 냉방|cooling|heating 난방|air conditioner 에어컨(기계)',
      'energy|명|에너지|power|—|energetic 활기찬',
      'contribute to|숙|~의 원인이 되다, ~에 기여하다|cause, lead to|prevent 막다|contribution 기여',
      'climate change|명|기후 변화|global warming|—|climate 기후',
      'design|동|설계하다, 디자인하다|plan, create|—|designer 디자이너',
      'still|부|여전히, 그래도|yet|—|—',
      'structure|명|구조, 구조물|framework, form|—|structural 구조의',
      'possible|형|가능한|able to be done|impossible 불가능한|possibility 가능성',
      'natural|형|자연적인|—|artificial 인공적인|nature 자연 / naturally 자연스럽게',
      'flow|명|흐름|movement, stream|—|flow 흐르다(동사)',
    ],
    flow: [
      ['🏙️', '도입 — 땅 위의 환경 보호', '바다의 사례(칸쿤)에 이어 **땅 위**에서는 **건축**으로 환경을 보호하는 싱가포르의 사례로 넘어간다. 화자는 **건축가 Rajesh Khan**.'],
      ['🥵', '문제 — 더운 날씨와 에어컨', '싱가포르는 **일 년 내내 더워** 건물마다 **에어컨**이 필요하고, 에어컨은 **에너지를 많이 쓰며 기후 변화**의 원인이 된다.'],
      ['🏗️', '해결 — 친환경 건물 설계', '{That’s why} 로 **원인 → 결과**를 잇는다. 건축가들은 **에어컨을 덜 쓰면서도 시원한** 친환경 건물을 설계하기 시작했다.'],
      ['🌬️', '원리 — 개방형 구조와 공기 흐름', '{For example} — **개방형 구조**로 **바깥 공기가 건물 전체를 흐르게** 하고, 이 **자연적인 공기 흐름**이 건물을 시원하게 유지한다.'],
    ],
    cards: [
      {
        covers: [1, 2],
        en: 'In Singapore, people [g:are using] architecture [r:to protect] the environment on land. | [g:Let’s hear] [h:what Rajesh Khan, an architect, says] about eco-friendly buildings.',
        note: '**해석 도움** — {to protect} 는 **목적**(보호하기 위해)이다. {what Rajesh Khan ... says} 는 {hear} 의 목적어인 **관계대명사 what절**로 "Rajesh Khan이 **말하는 것**"이라는 뜻이다.',
        points: [
          ['grammar', '**목적의 to부정사** — {are using architecture to protect ~}. "보호하기 **위해** 건축을 이용하다".'],
          ['grammar', '**관계대명사 what = the thing(s) which** — {what Rajesh Khan says} "Rajesh Khan이 **말하는 것**". 선행사를 **포함**하므로 앞에 명사가 없다.'],
          ['reading', '**on land ↔ 앞 사례의 underwater** — 앞의 칸쿤은 **바다**, 이번 싱가포르는 **땅 위**. 두 사례가 **대비**를 이룬다.'],
        ],
      },
      {
        covers: [3, 4],
        en: 'Singapore is hot [h:throughout the year]. | Most buildings need air conditioning, | [g:which] uses a lot of energy [r:and contributes to] climate change.',
        note: '**해석 도움** — 콤마 뒤 {which} 는 앞의 {air conditioning} 을 받는 **계속적 용법**이다. {which} 뒤 동사 {uses} 와 {contributes} 가 {and} 로 병렬 연결된다.',
        points: [
          ['grammar', '**계속적 용법의 which** — {, which uses ~} = {and it uses ~}. 앞 명사에 대한 **추가 설명**을 덧붙인다.'],
          ['vocab', '**contribute to + 명사** — "~의 **원인이 되다**" 또는 "~에 **기여하다**". 여기서는 **부정적 결과**(기후 변화)의 원인이라는 뜻이다. {to} 는 **전치사**.'],
          ['vocab', '**throughout the year** — "**일 년 내내**". {throughout} 은 시간(~ 내내)과 장소(~ 곳곳에) 모두에 쓴다.'],
        ],
      },
      {
        covers: [5],
        en: '[r:That’s why] architects in Singapore [g:have begun] to design eco-friendly buildings | [g:that] use less air conditioning [h:but are still cool] inside.',
        ko: '그것이 싱가포르의 건축가들이 친환경 건물을 설계하기 시작한 이유입니다 | 에어컨을 덜 사용하면서도 실내는 여전히 시원한',
        note: '**해석 도움** — {That’s why + 결과} 는 "그것이 ~한 **이유**다". 앞 문장(에어컨의 문제)이 **원인**, 이 문장이 **결과**다. {that use ~ but are ~} 는 {eco-friendly buildings} 를 꾸미는 **주격 관계대명사절**이다.',
        points: [
          ['grammar', '**That’s why vs. That’s because** — {That’s why + 결과}, {That’s because + 원인}. 앞 문장이 **원인**이므로 여기서는 {why} 가 맞다.'],
          ['grammar', '**현재완료 have begun** — 과거에 시작해서 **지금도 계속** 친환경 건물을 설계하고 있음을 나타낸다.'],
          ['grammar', '**관계절 속 동사 병렬** — {that use ~ but are still cool}. 선행사가 복수 {buildings} 이므로 **use, are** 모두 복수형이다.'],
        ],
      },
      {
        covers: [6],
        en: '[r:For example], many buildings in Singapore [g:are designed] [h:to have an open structure].',
        ko: '예를 들어, | 싱가포르의 많은 건물은 개방형 구조를 갖도록 설계됩니다.',
        note: '**해석 도움** — {are designed} 는 **수동태**(설계되다). 건물은 스스로 설계하지 않으므로 수동태를 쓴다. {to have} 는 "~을 **갖도록**"이라는 **목적·결과**다.',
        points: [
          ['grammar', '**수동태 be + p.p.** — {are designed}. 행위자(건축가)가 분명해서 {by architects} 는 생략되었다.'],
          ['grammar', '**be designed to + 동사원형** — "~하도록 설계되다". 설계의 **목적**을 나타내는 to부정사다.'],
        ],
      },
      {
        covers: [7, 8],
        en: 'This structure [g:makes it possible] [h:for outside air] [r:to move throughout a building]. | This natural air flow is [g:how these buildings stay cool].',
        note: '**해석 도움** — {makes it possible for A to B} 에서 {it} 은 **가목적어**, {to move ~} 가 **진목적어**, {for outside air} 는 **의미상 주어**다. {how these buildings stay cool} 은 "이 건물들이 시원하게 **유지되는 방법**"이다.',
        points: [
          ['grammar', '**가목적어 it + 진목적어 to부정사** — {make it possible for A to ~} "A가 ~하는 것을 **가능하게** 하다". {make possible outside air to move} ✗.'],
          ['grammar', '**관계부사 how** — {is how ~} = {is the way ~}. "~하는 **방법**". {the way how} 처럼 **둘을 함께 쓰지 않는다**.'],
          ['grammar', '**stay + 형용사** — {stay cool} "시원한 상태로 **유지되다**". 2형식 동사 {stay, keep, remain} 뒤에는 **형용사 보어**가 온다.'],
        ],
      },
    ],
    prompt: `Photorealistic architectural photograph, wide banner composition. A modern eco-friendly high-rise building in tropical Singapore with an open structure: large open-air voids and breezeways cut through the middle floors, open terraces and louvered walls letting outside air pass straight through the building, pale concrete and white steel, a clear view of the sky visible through the openings. Street-level wide angle, surrounding tropical trees. ${LIGHT}, fresh white and soft green. ${NO}, air conditioner units, rooftop pool, vertical garden wall --ar 16:5 --v 8.1`,
  },

  /* ── Ch4 ─────────────────────────────────────────── */
  {
    no: 4, type: '요지', answer: 5,
    question: '다음 글의 요지로 가장 적절한 것은?',
    summary: '건축가들은 개방형 구조뿐 아니라 커다란 정원도 더해요. 이 녹지 공간은 그늘을 만들고 직사광선으로부터 건물을 보호해 건물을 더 시원하게 유지해요. 이런 친환경 건물은 환경 보호에 도움이 될 뿐 아니라 사람들에게 좋은 삶의 질을 제공하는데, 이것이 새로운 건축 양식의 목표예요. 모든 분야에는 환경을 보호하는 다양한 방법이 있고, 더 많은 혁신이 있으면 인간과 자연은 먼 미래까지 조화롭게 함께 살아갈 수 있을 거예요.',
    mainIdea: 'Eco-friendly buildings with gardens both protect the environment and improve people’s lives, and more innovation in every field will let humans and nature live in harmony.',
    titleEn: 'Green Buildings and a Future in Harmony',
    ko: [
      '건축가들은 개방형 구조를 만드는 것 외에도 커다란 정원을 추가합니다.',
      '이러한 녹지 공간은 그늘을 제공하고 직사광선으로부터 건물 일부를 보호하여, 건물을 더 시원하게 유지합니다.',
      '이와 같은 친환경 건물들은 환경을 보호하는 데 도움을 줄 뿐만 아니라, 사람들에게 양질의 삶을 제공합니다.',
      '그것들이 이 새로운 건축 양식의 목표입니다.',
      '바라건대, 건축가들은 계속해서 새로운 친환경 아이디어를 생각해낼 것입니다.',
      '모든 분야에는 환경을 보호하는 각기 다른 방법이 있다.',
      '더 많은 혁신으로, 먼 미래에 인간과 자연은 함께 조화를 이루며 살아갈 수 있을 것이다.',
    ],
    choices: [
      ['정원은 건물의 에너지 사용을 늘리므로 줄여야 한다.', '정원(녹지)은 **그늘을 만들어 건물을 더 시원하게** 한다. 에너지 사용을 **늘린다는 내용은 없다**.'],
      ['친환경 건물은 환경에는 좋지만 사람의 삶을 불편하게 만든다.', '{not only ~ but also provide people with a good quality of life} — 사람들에게 **좋은 삶의 질**을 제공한다. **정반대**다.'],
      ['환경 보호는 건축 분야만의 책임이다.', '{Every field has different ways} — **모든 분야**에 환경을 보호하는 방법이 있다고 했다.'],
      ['건축가들은 이제 새로운 아이디어를 낼 필요가 없다.', '{Hopefully, architects will keep coming up with new eco-friendly ideas} — 새로운 아이디어를 **계속 내기를 바란다**.'],
      ['다양한 분야의 혁신으로 인간과 자연이 조화롭게 공존할 수 있다.', '친환경 건물의 이점에 이어, **모든 분야의 혁신**으로 **인간과 자연이 조화를 이루며 살 수 있다**는 결론이 글의 요지다. **정답**.'],
    ],
    vocab: [
      'in addition to|숙|~ 외에도, ~에 더하여|besides, as well as|—|addition 추가 / additional 추가의',
      'structure|명|구조|framework|—|structural 구조의',
      'greenery|명|녹지, 초목|plants, vegetation|—|green 녹색의',
      'shade|명|그늘|shadow, cover|sunlight 햇빛|shady 그늘진',
      'protect A from B|숙|B로부터 A를 보호하다|guard A against B|expose 노출하다|protection 보호',
      'direct|형|직접적인|straight|indirect 간접적인|directly 곧바로',
      'sunlight|명|햇빛|sunshine|shade 그늘|—',
      'not only A but also B|숙|A뿐만 아니라 B도|B as well as A|—|—',
      'provide A with B|숙|A에게 B를 제공하다|provide B for A, supply|—|provider 제공자',
      'quality of life|명|삶의 질|well-being, living standards|—|quality 질',
      'goal|명|목표|aim, purpose|—|—',
      'hopefully|부|바라건대|—|—|hope 희망하다 / hopeful 희망에 찬',
      'come up with|숙|(생각을) 떠올리다, 내놓다|think of, create|—|—',
      'field|명|분야|area, sector|—|—',
      'innovation|명|혁신|new idea, invention|—|innovate 혁신하다 / innovative 혁신적인',
      'in harmony|숙|조화를 이루어|peacefully, together|in conflict 갈등하여|harmonious 조화로운',
      'far into the future|숙|먼 미래까지|for a long time to come|—|—',
    ],
    flow: [
      ['🌳', '추가 설계 — 커다란 정원', '{In addition to} — **개방형 구조**에 더해 **큰 정원**을 만든다. 녹지는 **그늘**을 만들고 **직사광선**을 막아 건물을 더 시원하게 한다.'],
      ['🏡', '이점 — 환경과 삶의 질', '{not only A but also B} 로 친환경 건물의 **두 가지 이점**(환경 보호 + 좋은 삶의 질)을 제시하고, 이것이 **새 건축 양식의 목표**라고 정리한다.'],
      ['💭', '기대 — 계속되는 아이디어', '{Hopefully} — 건축가들이 **새로운 친환경 아이디어를 계속 내놓기**를 바란다는 **화자의 희망**으로 Rajesh Khan의 설명이 끝난다.'],
      ['🤝', '결론 — 모든 분야의 혁신과 조화', '다시 글쓴이의 목소리로 돌아와, **모든 분야**에 환경 보호 방법이 있으며 **더 많은 혁신**으로 **인간과 자연이 조화롭게 살 수 있다**는 전체 결론을 내린다.'],
    ],
    cards: [
      {
        covers: [1],
        en: '[r:In addition to] [g:making] open structures, | architects add large gardens.',
        ko: '개방형 구조를 만드는 것 외에도, | 건축가들은 커다란 정원을 추가합니다.',
        note: '**해석 도움** — {In addition to} 의 {to} 는 **전치사**이므로 뒤에 동사원형이 아니라 **동명사**({making})가 온다.',
        points: [
          ['grammar', '**전치사 to + 동명사** — {in addition to making}. {look forward to -ing}, {be used to -ing} 처럼 **to가 전치사**인 표현은 뒤에 **-ing** 를 쓴다.'],
          ['reading', '**첨가의 연결어** — {In addition to} 는 앞 단락의 **개방형 구조**에 이어 **두 번째 설계 방법**(정원)을 더한다는 신호다.'],
        ],
      },
      {
        covers: [2],
        en: 'This greenery [g:provides] shade [g:and protects] parts of the building [h:from direct sunlight], | [r:which keeps the building cooler].',
        ko: '이러한 녹지 공간은 그늘을 제공하고 직사광선으로부터 건물 일부를 보호하여, | 건물을 더 시원하게 유지합니다.',
        note: '**해석 도움** — 주어 {This greenery} 에 동사 {provides} 와 {protects} 가 병렬로 이어진다. 콤마 뒤 {which} 는 앞 **절 전체**(그늘을 주고 햇빛을 막는 것)를 받는다.',
        points: [
          ['grammar', '**protect A from B** — "B로부터 A를 보호하다". {protects parts of the building from direct sunlight}.'],
          ['grammar', '**계속적 용법 which (앞 절 전체)** — {, which keeps ~} = {and this keeps ~}. 무엇이 건물을 시원하게 하는지 **앞 내용 전체**가 답이다.'],
          ['grammar', '**keep + 목적어 + 형용사(비교급)** — {keeps the building cooler} "건물을 **더 시원하게** 유지하다". 5형식 구문.'],
        ],
      },
      {
        covers: [3, 4],
        en: 'Eco-friendly buildings like these [r:not only] help protect the environment, | [r:but also] [g:provide people with] a good quality of life. | [h:Those are the goals] of this new style of architecture.',
        note: '**해석 도움** — {not only A but also B} 는 "A뿐만 아니라 B도". A와 B 자리에 동사구 {help protect ~} 와 {provide ~} 가 **같은 형태로** 온다. {help protect} 는 {help (to) protect} 에서 to가 생략된 형태다.',
        points: [
          ['grammar', '**상관접속사 not only A but also B** — A와 B는 **문법적으로 같은 형태**(병렬)여야 한다. {= B as well as A}.'],
          ['grammar', '**help + (to) 동사원형** — {help protect}. {help} 는 뒤에 **동사원형**과 **to부정사** 모두 올 수 있다.'],
          ['grammar', '**provide A with B = provide B for A** — {provide people with a good quality of life} = {provide a good quality of life for people}.'],
        ],
      },
      {
        covers: [5],
        en: '[r:Hopefully], architects will [g:keep coming up with] new eco-friendly ideas.',
        ko: '바라건대, | 건축가들은 계속해서 새로운 친환경 아이디어를 생각해낼 것입니다.',
        note: '**해석 도움** — {Hopefully} 는 문장 전체를 꾸미는 부사로 "**바라건대**, ~하면 좋겠다". {keep -ing} 는 "계속 ~하다", {come up with} 는 "(생각을) 떠올리다, 내놓다".',
        points: [
          ['grammar', '**keep + 동명사** — {keep coming up with}. {keep, enjoy, finish, mind, give up} 은 **동명사**를 목적어로 쓴다.'],
          ['vocab', '**come up with** — "(아이디어·해결책을) **생각해 내다**". {think of} 와 비슷하다. 구동사이므로 **세 단어를 한 덩어리**로 외운다.'],
        ],
      },
      {
        covers: [6, 7],
        en: '[h:Every field has] different ways [g:of protecting] the environment. | [r:With more innovation], humans and nature [g:will be able to] live together [h:in harmony] far into the future.',
        note: '**해석 도움** — {Every} 뒤에는 **단수 명사 + 단수 동사**({field has})가 온다. {With more innovation} 은 "더 많은 혁신이 **있으면**"이라는 **조건**의 의미로 해석하면 자연스럽다.',
        points: [
          ['grammar', '**every + 단수명사 + 단수동사** — {Every field has ~}. "모든"이라는 뜻이지만 **단수 취급**한다.'],
          ['grammar', '**전치사 of + 동명사** — {ways of protecting} "보호하는 방법". {ways to protect} 로도 쓸 수 있다(앞 단락 {ways to protect} 와 비교).'],
          ['reading', '**글 전체의 결론** — 바다(칸쿤)와 땅(싱가포르) 두 사례를 **모든 분야**로 일반화하며, **혁신 → 인간과 자연의 조화**라는 최종 메시지를 전한다.'],
        ],
      },
    ],
    prompt: `Photorealistic architectural photograph, wide banner composition. A modern tropical apartment tower in Singapore whose balconies and sky terraces overflow with large lush gardens: mature trees, hanging plants and shrubs on every level, the greenery casting soft shade across the pale facade and shielding it from direct sun. Shot from a low angle across a leafy public garden in the foreground. ${LIGHT}, vivid fresh greens and white concrete. ${NO}, open-air voids, cars, traffic --ar 16:5 --v 8.1`,
  },
];

console.log('✍️  L5 저작');
for (const c of chapters) writeChapter('L5', SOURCE, c);
