/* 신서중3 동아(윤정미) Lesson 6 — Stories for All Time · One Lucky Sunday · 저작 원고
 * 문법은 _gen-data.mjs 머리말 참고. 정답 위치 3/5/2/4 (사전 분산).
 * 원작: Roald Dahl, "Parson’s Pleasure" 각색. 인물은 허구이므로 삽화는 인물 없이 사물·장소로. */

const NEG = 'people, person, faces, hands, figures, text, letters, numbers, logo, signage, price tags, watermark, dramatic lighting, sunset, golden hour, night, heavy shadows, dark moody grading';

export const CHAPTERS = [
  /* ─────────────────────────── Ch1 ─────────────────────────── */
  {
    no: 1, type: '내용일치', answer: 3,
    summary: 'Cyril Boggis는 런던의 골동품 가구 판매상이었어요. 그는 좋은 물건을 싸게 사서 비싸게 파는 것으로 유명했지요. 사람들이 가구를 어디서 구했느냐고 물으면 그는 “비밀이에요.”라고만 했어요. 그 비밀은 간단했어요. 그는 일요일마다 작은 마을에 가서 문을 두드리고 자신이 가구 판매상이라고 말했어요. 사람들은 자기 물건이 얼마나 값진지 몰랐고, Boggis 씨는 그 점을 이용해 물건을 아주 싸게 살 수 있었답니다.',
    main_idea_en: 'Mr. Boggis, a London antique dealer, got rich by visiting small towns on Sundays and cheaply buying valuable furniture from people who did not know its worth.',
    title_en: 'The Secret of an Antique Dealer',
    illust: `Wide banner interior photograph of an elegant old London antique furniture shop: polished eighteenth-century
      English furniture arranged in rows — carved mahogany chairs, a tall grandfather clock, glass-fronted cabinets,
      a writing desk with brass handles — on worn wooden floorboards, a large paned shop window letting in bright soft
      light from a quiet street. Natural soft diffused daylight, bright overcast sky outside, high-key exposure, low
      contrast, warm wood tones against cream walls. Refined editorial interior photography, sharp detail on the wood
      grain. --ar 16:5 --v 8.1 --no saw, broken furniture, table legs on floor, car, farmhouse, ${NEG}`,
    ko: [
      'Cyril Boggis는 런던의 골동품 가구 판매상이었습니다.',
      '그는 좋은 물건을 낮은 가격에 사서 높은 가격에 파는 것으로 유명했습니다.',
      '사람들은 그에게 가구를 어디에서 구했는지 물었지만, 그는 그저 “그건 비밀이에요.”라고 말했습니다.',
      'Boggis 씨의 비밀은 단순했습니다.',
      '그는 매주 일요일에 작은 마을들에 가서 문을 두드렸습니다.',
      '그는 사람들에게 자신이 가구 판매상이라고 말했습니다.',
      '사람들은 자신들의 물건이 얼마나 값진지 몰랐고, 그래서 Boggis 씨는 그들을 이용했습니다.',
      '그는 물건들을 매우 싸게 살 수 있었습니다.',
    ],
    choices: [
      ['Boggis 씨는 파리의 가구 판매상이었다.', '첫 문장 `an antique furniture dealer in London` — **런던**이다.'],
      ['Boggis 씨는 가구를 구한 곳을 사람들에게 자세히 알려 주었다.', '그는 `It’s a secret.` 이라고만 했다. **알려 주지 않았다**.'],
      ['Boggis 씨는 일요일마다 작은 마을에 가서 문을 두드렸다.', '`He went to small towns every Sunday and knocked on doors.` 와 일치한다.'],
      ['사람들은 자기 물건의 가치를 잘 알고 있었다.', '`People didn’t know how valuable their things were` — **몰랐다**. 그래서 Boggis 씨가 이용할 수 있었다.'],
      ['Boggis 씨는 물건을 비싸게 사서 싸게 팔았다.', '본문은 `buying ~ at a low price and then selling ~ at a high price`, **싸게 사서 비싸게** 팔았다고 한다. 순서가 **뒤바뀌었다**.'],
    ],
    vocab: [
      ['antique', '형·명', '골동품(의)', 'old, vintage', 'modern 현대의', '—'],
      ['furniture', '명', '가구 (셀 수 없음)', '—', '—', 'a piece of furniture 가구 한 점'],
      ['dealer', '명', '판매상, 중개인', 'trader, seller', 'buyer 구매자', 'deal 거래(하다)'],
      ['be known for', '숙', '~로 유명하다', 'be famous for', '—', 'know 알다'],
      ['price', '명', '가격', 'cost', '—', 'priceless 매우 귀중한'],
      ['secret', '명', '비밀', 'mystery', '—', 'secretly 몰래'],
      ['simple', '형', '단순한, 간단한', 'easy, plain', 'complex 복잡한', 'simply 단순히'],
      ['knock', '동', '두드리다, 노크하다', 'tap, rap', '—', '—'],
      ['valuable', '형', '값비싼, 귀중한', 'precious', 'worthless 가치 없는', 'value 가치'],
      ['take advantage of', '숙', '~을 이용하다, 악용하다', 'exploit, use', '—', 'advantage 이점'],
      ['be able to', '숙', '~할 수 있다', 'can', 'be unable to ~할 수 없다', 'ability 능력'],
      ['cheaply', '부', '싸게', 'at a low price', 'expensively 비싸게', 'cheap 싼'],
    ],
    flow: [
      ['🪑', '인물 소개 — 골동품 판매상 Boggis', '**런던의 골동품 가구 판매상**. 싸게 사서 비싸게 파는 것으로 **유명**했다 — 인물의 **성격(이익에 밝음)**이 첫 두 문장에 드러난다.'],
      ['🤫', '“그건 비밀이에요.”', '가구의 출처를 물으면 **비밀**이라고만 한다. 독자의 **궁금증**을 끌어올리는 장치다.'],
      ['🚪', '비밀의 정체 — 일요일의 방문', '**Mr. Boggis’ secret was simple.** — 일요일마다 **작은 마을의 문을 두드리고** 자신을 **가구 판매상**이라 소개했다.'],
      ['💰', '사람들의 무지를 이용하다', '사람들은 물건의 **가치를 몰랐고**, Boggis 씨는 그것을 **이용해** 아주 싸게 샀다. 이 **속임수**가 이야기 결말의 **반전**을 위한 복선이 된다.'],
    ],
    cards: [
      { c: [1, 2], en: 'Cyril Boggis was an antique furniture dealer in London. / He [[was known for]] {{buying}} good things at a low price and then {{selling}} them at a high price.',
        ko: 'Cyril Boggis는 런던의 골동품 가구 판매상이었다. / 그는 유명했다 / 좋은 물건을 낮은 가격에 사서 / 그다음 높은 가격에 파는 것으로.',
        note: '**해석 도움** — `buying ~ and then selling ~` 은 전치사 `for` 의 목적어로 **동명사 두 개가 병렬**을 이룬다. ‘사서 **그다음** 파는 것으로’.',
        pts: [
          ['grammar', '**be known for + (동)명사** — ‘~로 유명하다’. 전치사 뒤이므로 `buying`, `selling` 모두 **-ing**. `be known as`(~로서 알려지다: 자격), `be known to`(~에게 알려지다)와 구별.'],
          ['grammar', '**병렬 구조** — `buying A ~ and (then) selling B ~`. `and` 앞뒤 형태가 같아야 한다(`sell` ×).'],
          ['vocab', '**furniture** — **셀 수 없는 명사**. `a furniture`, `furnitures` × → `a piece of furniture` ○.'],
        ] },
      { c: [3], en: 'People asked him [[where he had got]] the furniture, / ((but)) he just said, “It’s a secret.”',
        ko: '사람들은 그에게 물었다 / 그가 가구를 어디에서 구했는지, / 하지만 그는 그저 말했다, / “그건 비밀이에요.”',
        note: '**해석 도움** — `where he had got the furniture` 는 `asked` 의 **직접목적어**인 **간접의문문**. ‘그가 가구를 **어디서 구했는지**’.',
        pts: [
          ['grammar', '**간접의문문: 의문사 + 주어 + 동사** — `where had he got` × → `where he had got` ○. 의문문이 문장 속에 들어가면 **평서문 어순**이 된다.'],
          ['grammar', '**과거완료 had p.p.** — 사람들이 **물은 것**(과거)보다 그가 가구를 **구한 것**이 **더 먼저**다. 이 ‘대과거’를 `had got` 으로 나타낸다.'],
          ['grammar', '**4형식 ask + 간접목적어 + 직접목적어** — `asked him (IO) where ~ (DO)`. ‘그에게 ~을 물었다’.'],
        ] },
      { c: [4, 5, 6], en: 'Mr. Boggis’ secret was simple. / He went to small towns [[every Sunday]] and knocked on doors. / He told people {{that he was}} a furniture dealer.',
        ko: 'Boggis 씨의 비밀은 단순했다. / 그는 매주 일요일에 작은 마을들에 가서 문을 두드렸다. / 그는 사람들에게 말했다 / 자신이 가구 판매상이라고.',
        note: '**해석 도움** — `Mr. Boggis’` 는 **s로 끝나는 고유명사**의 소유격이라 **’만** 붙였다. `told people that ~` 은 ‘사람들에게 ~라고 말했다’.',
        pts: [
          ['grammar', '**s로 끝나는 이름의 소유격** — `Boggis’`(교과서 표기). `Boggis’s` 로도 쓴다. 복수명사 `players’` 와 모양이 같으니 문맥으로 구별.'],
          ['grammar', '**시제 일치** — 주절이 과거(`told`)라 `that` 절도 과거 `was`. 직접화법으로는 `He said to people, “I am a furniture dealer.”`'],
          ['vocab', '**every + 단수명사** — `every Sunday` 는 ‘매주 일요일’. `every` 뒤에는 **단수명사**가 온다(`every Sundays` ×).'],
        ] },
      { c: [7, 8], en: 'People didn’t know [[how valuable their things were]], / ((so)) Mr. Boggis {{took advantage of}} them. / He [[was able to]] buy things very cheaply.',
        ko: '사람들은 알지 못했다 / 자신들의 물건이 얼마나 값진지, / 그래서 Boggis 씨는 그들을 이용했다. / 그는 물건들을 매우 싸게 살 수 있었다.',
        note: '**해석 도움** — `how valuable their things were` 는 **〈how + 형용사 + 주어 + 동사〉**의 간접의문문. ‘물건이 **얼마나 값진지**’.',
        pts: [
          ['grammar', '**how + 형용사 + 주어 + 동사** — `how valuable were their things` ×. `how valuable` 을 **한 덩어리**로 앞에 두고 평서문 어순을 쓴다.'],
          ['vocab', '**take advantage of** — ‘~을 이용하다’. 사람이 목적어일 때는 **부당하게 이용하다(악용)**의 뜻이 강하다. 이 인물의 **비윤리성**을 드러내는 핵심 표현.'],
          ['grammar', '**be able to = can** — 과거의 **능력**을 `was able to` 로 나타냈다. `can` 은 다른 조동사 뒤에 못 오므로 미래는 `will be able to`.'],
        ] },
    ],
  },

  /* ─────────────────────────── Ch2 ─────────────────────────── */
  {
    no: 2, type: '심경', answer: 5,
    q: '다음 글에서 거실의 탁자를 발견했을 때 Boggis 씨의 심경으로 가장 적절한 것은?',
    summary: '또 다른 일요일, Boggis 씨는 다시 작은 마을에 있었어요. 방문한 집에서 주인 Rummins와 그의 아들 Bert를 만났지요. 고가구가 없다는 Rummins에게 그는 한번 둘러봐도 되겠냐고 물었고 허락을 받았어요. 부엌에는 아무것도 없었지만, 거실에는 값을 매길 수 없을 만큼 귀중한 18세기 영국 가구인 탁자가 있었어요! 그는 너무 흥분해서 거의 넘어질 뻔했어요. Bert가 무슨 일이냐고 묻자 그는 아무 일도 아니라고 거짓말을 하고, 정색하며 그 탁자는 몇 파운드짜리 복제품이라고 말했어요.',
    main_idea_en: 'Mr. Boggis finds a priceless eighteenth-century table, hides his excitement, and lies that it is a cheap reproduction.',
    title_en: 'A Priceless Table and a Straight Face',
    illust: `Wide banner interior photograph of a plain, slightly shabby English countryside farmhouse living room: in the
      center stands a magnificent eighteenth-century English mahogany table with elegantly carved curved cabriole legs
      and a deep glossy polish, looking wildly out of place among a worn armchair, a faded rug, bare whitewashed walls
      and a small cottage window. Natural soft diffused daylight from the window, bright even illumination, high-key
      exposure, low contrast, the rich red-brown wood glowing against the pale plain room. Editorial interior
      photography, sharp detail on the carving. --ar 16:5 --v 8.1 --no saw, sawdust, cut-off legs, car, antique shop,
      rows of furniture, ${NEG}`,
    ko: [
      '또 다른 일요일이 되었고, Boggis 씨는 다시 어느 작은 마을에 있었습니다.',
      '그가 방문한 한 집에서, 그는 두 남자를 만났습니다.',
      '한 명은 주인인 Rummins였고, 다른 한 명은 그의 아들인 Bert였습니다.',
      '“저는 고가구를 삽니다. 고가구가 있으신가요?” Boggis 씨가 물었습니다.',
      '“아니요, 없어요.” Rummins가 말했습니다.',
      '“한번 둘러봐도 될까요?” Boggis 씨가 물었습니다.',
      '“그럼요. 들어오세요.” Rummins가 말했습니다.',
      'Boggis 씨는 먼저 부엌에 갔는데, 아무것도 없었습니다.',
      '그런 다음 그는 거실로 옮겨 갔습니다.',
      '그리고 거기에 그것이 있었습니다!',
      '값을 매길 수 없을 만큼 귀중한 18세기 영국 가구인 탁자가.',
      '그는 너무 흥분해서 거의 넘어질 뻔했습니다.',
      '“무슨 일이세요?” Bert가 물었습니다.',
      '“아, 아무것도 아니에요. 전혀 아무 일도 아닙니다.” Boggis 씨는 거짓말을 했습니다.',
      '그런 다음 그는 정색하며 말했습니다. “이 탁자는 복제품입니다. 몇 파운드의 가치밖에 안 돼요.”',
    ],
    choices: [
      ['bored', '지루함과는 거리가 멀다. **거의 넘어질 뻔할 만큼** 흥분했다.'],
      ['scared', '겁먹을 일은 없다. 탁자는 그가 **바라던 보물**이다.'],
      ['disappointed', '부엌에는 아무것도 없었지만 곧바로 `And there it was!` — **실망**이 아니라 **발견의 기쁨**으로 바뀐다.'],
      ['relieved', '안도는 걱정하던 일이 풀릴 때의 감정이다. 본문에는 **걱정**이 없었다.'],
      ['thrilled', '`He was so excited that he almost fell over.` — **몹시 흥분한(thrilled)** 상태다. 겉으로는 `a straight face` 로 감추었을 뿐이다.'],
    ],
    vocab: [
      ['owner', '명', '주인, 소유자', 'possessor', '—', 'own 소유하다'],
      ['take a look', '숙', '한번 보다, 둘러보다', 'look around, glance', '—', '—'],
      ['kitchen', '명', '부엌', '—', '—', '—'],
      ['living room', '명', '거실', 'sitting room', '—', '—'],
      ['priceless', '형', '값을 매길 수 없을 만큼 귀중한', 'invaluable, precious', 'worthless 가치 없는', 'price 가격 + -less'],
      ['piece', '명', '(물건) 한 점, 조각', 'item', '—', 'a piece of furniture 가구 한 점'],
      ['eighteenth-century', '형', '18세기의', '—', '—', 'century 세기'],
      ['excited', '형', '흥분한, 신이 난', 'thrilled', 'calm 차분한', 'excite 흥분시키다 / exciting 흥미진진한'],
      ['fall over', '숙', '넘어지다', 'tumble, trip', 'stand up 일어서다', '—'],
      ['lie', '동', '거짓말하다 (lie-lied-lied)', 'tell a lie', 'tell the truth 진실을 말하다', 'liar 거짓말쟁이'],
      ['with a straight face', '숙', '정색하며, 시치미 떼고', 'seriously, without smiling', '—', 'straight 똑바른'],
      ['reproduction', '명', '복제품', 'copy, replica', 'original 원본', 'reproduce 복제하다'],
      ['worth', '형', '~의 가치가 있는', 'valued at', '—', 'worthless 가치 없는'],
      ['pound', '명', '파운드 (영국 화폐 단위)', '—', '—', '—'],
    ],
    flow: [
      ['🏡', '또 한 번의 일요일 — Rummins의 집', '장면이 바뀐다. 작은 마을의 한 집, **주인 Rummins**와 **아들 Bert** — 이야기의 두 번째 주인공들이 등장한다.'],
      ['🗣️', '“고가구 있으세요?” — “없어요.”', '짧은 대화로 **긴장 없는 출발**. Rummins는 **없다**고 하지만 Boggis 씨는 **둘러봐도 되느냐**고 끈질기게 들어간다.'],
      ['😲', '발견! — 18세기 영국 탁자', '부엌은 허탕, 거실에서 **And there it was!** 감탄문 한 줄로 **절정의 순간**을 만든다. **so excited that he almost fell over** 가 그의 속마음이다.'],
      ['😐', '표정 관리와 거짓말', '**Mr. Boggis lied.** — 속마음을 숨기고 **with a straight face** 로 ‘**복제품, 몇 파운드짜리**’라고 속인다. 뒤의 **흥정과 반전**을 위한 결정적 거짓말이다.'],
    ],
    cards: [
      { c: [1, 2, 3], en: 'Now it was another Sunday, and Mr. Boggis was in a small town again. / At [[a house he visited]], he met two men. / {{One}} was Rummins, the owner, and {{the other}} was his son Bert.',
        ko: '또 다른 일요일이 되었고, / Boggis 씨는 다시 어느 작은 마을에 있었다. / 그가 방문한 한 집에서, / 그는 두 남자를 만났다. / 한 명은 주인인 Rummins였고, / 다른 한 명은 그의 아들 Bert였다.',
        note: '**해석 도움** — `a house he visited` 는 `a house (that) he visited` 에서 **목적격 관계대명사가 생략**된 형태. ‘**그가 방문한** 한 집’.',
        pts: [
          ['grammar', '**One ~, the other ~** — 둘 중 **하나는 one, 나머지 하나는 the other**. 셋 이상이면 `one ~, another ~, the other ~`.'],
          ['grammar', '**목적격 관계대명사 생략** — `a house (which/that) he visited`. 선행사 뒤에 **〈주어 + 동사〉**가 바로 오면 생략을 의심하자.'],
          ['grammar', '**동격 콤마** — `Rummins, the owner` / `his son Bert`. 콤마나 나란히 놓인 명사가 **같은 사람**을 설명한다.'],
        ] },
      { c: [4, 5], en: '“I buy old furniture. Do you have [[any]]?” asked Mr. Boggis. / “No, I don’t,” said Rummins.',
        ko: '“저는 고가구를 삽니다. / 고가구가 있으신가요?” Boggis 씨가 물었다. / “아니요, 없어요.” Rummins가 말했다.',
        note: '**해석 도움** — `Do you have any?` 의 `any` 는 **대명사**로 `any old furniture` 를 줄인 말이다. ‘(고가구를) **좀** 갖고 계신가요?’',
        pts: [
          ['grammar', '**의문문의 any** — 의문문·부정문에서는 `some` 대신 `any`. 여기서는 뒤의 명사를 생략한 **대명사**로 쓰였다.'],
          ['grammar', '**인용문 뒤 주어·동사 도치** — `asked Mr. Boggis` / `said Rummins`. 인용문 뒤에서 주어가 **명사**면 `said Rummins` 처럼 **도치**가 흔하다. 대명사면 `he said` 로 쓴다.'],
          ['reading', '**대답의 짧음** — `No, I don’t.` 는 **Do 의문문**에 대한 짧은 대답. Rummins는 자기 집 탁자의 가치를 **모른다**는 것이 드러난다.'],
        ] },
      { c: [6, 7], en: '“Can I just [[take a look]]?” asked Mr. Boggis. / “Sure. Please come in,” said Rummins.',
        ko: '“한번 둘러봐도 될까요?” Boggis 씨가 물었다. / “그럼요. 들어오세요.” Rummins가 말했다.',
        note: '**해석 도움** — `Can I ~?` 는 **능력**이 아니라 **허락**을 구하는 표현(‘~해도 될까요?’). `just` 가 붙어 ‘**그냥 잠깐만**’이라는 부드러운 어감이 된다.',
        pts: [
          ['grammar', '**허락의 Can I ~? / May I ~?** — `May I ~?` 가 더 공손하다. 대답은 `Sure.`, `Of course.`, `Go ahead.`'],
          ['vocab', '**take a look** — ‘한번 보다’. `have a look`, `look around`(둘러보다)와 비슷하다.'],
          ['reading', '**끈질긴 판매상** — ‘없다’는 대답에도 물러서지 않는다. Boggis 씨가 **어떻게 좋은 물건을 찾아내는지** 보여 주는 대목.'],
        ] },
      { c: [8, 9, 10], en: 'Mr. Boggis first went to the kitchen, and [[there was nothing]]. / He then moved to the living room. / ((And there it was!))',
        ko: 'Boggis 씨는 먼저 부엌에 갔는데, / 아무것도 없었다. / 그런 다음 그는 거실로 옮겨 갔다. / 그리고 거기에 그것이 있었다!',
        note: '**해석 도움** — `And there it was!` 는 ‘그리고 **바로 거기** 그것이 있었다!’. 부사 `there` 를 앞에 내세워 **발견의 순간**을 강조한다.',
        pts: [
          ['grammar', '**There + 대명사 + 동사** — 주어가 **대명사(it)**면 도치하지 않는다: `There it was!` 주어가 **명사**면 도치: `There was the table!`'],
          ['grammar', '**first ~ then ~** — 시간 순서를 나타내는 부사. `then` 은 **일반동사 앞**(`He then moved`)에 자주 온다.'],
          ['reading', '**긴장 → 폭발** — 부엌의 `nothing`(허탕)으로 **기대를 낮춘 뒤**, 감탄문 한 줄로 **극적 전환**을 만든다.'],
        ] },
      { c: [11, 12], en: 'A table [[which was a priceless piece]] of eighteenth-century English furniture. / He was ((so excited that)) he almost {{fell over}}.',
        ko: '탁자가 / 값을 매길 수 없을 만큼 귀중한 18세기 영국 가구 한 점인. / 그는 너무 흥분해서 / 거의 넘어질 뻔했다.',
        note: '**해석 도움** — 첫 문장은 **동사 없는 명사구**다. 앞 문장의 `it` 이 무엇인지 **덧붙여 밝히는** 말로, 소설에서 흔히 쓰는 **생략 문체**다.',
        pts: [
          ['grammar', '**주격 관계대명사 which** — `A table which was ~` 선행사가 **사물**이므로 `which(that)`. 이 문장 전체가 앞의 `it` 과 **동격**이다.'],
          ['grammar', '**so + 형용사 + that + 주어 + 동사** — ‘너무 ~해서 …하다’(원인·결과). `He was too excited to stand` 처럼 `too ~ to` 로 바꾸면 **부정**의 뜻이 된다.'],
          ['vocab', '**priceless** — `-less` 가 붙었지만 ‘가치 없는’이 **아니라** ‘**값을 매길 수 없을 만큼 귀중한**’. ‘가치 없는’은 **worthless**. 시험 단골 함정.'],
        ] },
      { c: [13, 14], en: '“[[What’s wrong?]]” Bert asked. / “Oh, nothing. Nothing at all,” Mr. Boggis {{lied}}.',
        ko: '“무슨 일이세요?” Bert가 물었다. / “아, 아무것도 아니에요. 전혀 아무 일도 아닙니다.” / Boggis 씨는 거짓말을 했다.',
        note: '**해석 도움** — `Nothing at all` 의 `at all` 은 부정을 **강조**한다(‘**전혀**’). 과한 부인이 오히려 **거짓말**임을 드러낸다.',
        pts: [
          ['vocab', '**What’s wrong?** — ‘무슨 일이야? 어디 안 좋아?’ 상대의 **이상한 모습**을 보고 묻는 말. `What’s the matter?` 와 같다.'],
          ['vocab', '**lie 의 두 동사** — ‘거짓말하다’ **lie-lied-lied**, ‘눕다’ **lie-lay-lain**, ‘눕히다’ **lay-laid-laid**. 여기서 `lied` 는 **거짓말하다**의 과거.'],
          ['reading', '**서술 동사로 드러나는 진실** — `said` 대신 `lied` 를 써서 서술자가 독자에게 **그의 말이 거짓**임을 직접 알려 준다.'],
        ] },
      { c: [15], en: 'He then said {{with a straight face}}, / “This table is [[a reproduction]]. It’s ((worth only a few pounds)).”',
        ko: '그런 다음 그는 정색하며 말했다, / “이 탁자는 복제품입니다. / 몇 파운드의 가치밖에 안 돼요.”',
        note: '**해석 도움** — `with a straight face` 는 ‘**웃음기 없이 진지한 얼굴로**’, 즉 **시치미 떼고**. 속마음(흥분)과 겉모습의 **대비**를 보여 준다.',
        pts: [
          ['grammar', '**be worth + 명사/동명사** — ‘~의 가치가 있다’. `worth` 는 **전치사처럼** 뒤에 명사를 바로 받는다: `worth a few pounds`, `worth reading`.'],
          ['grammar', '**a few + 복수명사** — ‘몇몇의’(긍정). `few pounds` 는 ‘거의 없는’(부정). 여기에 `only` 가 붙어 ‘**겨우 몇 파운드**’.'],
          ['vocab', '**reproduction** — ‘복제품’. 반의어 **original**(원본). 동사 `reproduce`(복제하다, 번식하다).'],
        ] },
    ],
  },

  /* ─────────────────────────── Ch3 ─────────────────────────── */
  {
    no: 3, type: '내용불일치', answer: 2,
    summary: 'Boggis 씨는 자기 집 탁자 다리가 부러졌으니 이 탁자의 다리를 잘라 붙이면 되겠다며 사겠다고 했어요. 가격 흥정이 시작되었지요. 10파운드, 15파운드를 부르는 그에게 Rummins는 50파운드를 불렀고, 결국 30파운드로 합의했어요. Rummins가 이걸 차에 어떻게 싣느냐고 묻자 Boggis 씨는 차를 가지러 나갔어요. 그는 모든 판매상이 꿈꾸던 탁자를 얻게 되어 웃음을 참을 수 없었어요. 한편 Bert는 탁자가 차에 들어가지 않으면 돈을 못 받을까 걱정했고, Rummins는 그가 원하는 건 다리뿐이니 다리를 잘라 주자고 했어요. Bert는 톱을 꺼내 다리를 자르기 시작했어요.',
    main_idea_en: 'After bargaining the price down to thirty pounds, Mr. Boggis goes to get his car, while Rummins and Bert decide to cut off the legs he says he wants.',
    title_en: 'The Deal and the Saw',
    illust: `Wide banner photograph of the front of a small old English countryside farmhouse with a gravel yard: a
      compact vintage 1950s car with a tiny rounded body and a small boot parked by the wooden gate, the farmhouse
      front door standing open, and on a rough wooden workbench beside the door lies a large old hand saw with a
      wooden handle next to a coil of rope. Green hedges and a pale sky. Natural soft diffused daylight, bright
      overcast sky, high-key exposure, low contrast, gentle pastoral greens and creams. Cinematic editorial
      photography, sharp detail. --ar 16:5 --v 8.1 --no antique shop, table legs, sawdust, broken table, ${NEG}`,
    ko: [
      '그런 다음 그는 덧붙였습니다. “흠, 제가 그걸 살 수도 있을 것 같아요.',
      '우리 집에 있는 제 탁자의 다리가 부러졌거든요.',
      '당신 탁자의 다리를 잘라서 제 것에 붙일 수 있겠어요.”',
      '“얼마요?” Rummins가 물었습니다.',
      '“유감이지만 많이는 아니에요. 이건 그저 복제품이니까요.” Boggis 씨가 말했습니다.',
      '“그래서 얼마요?”',
      '“10파운드요.”',
      '“10이요? 그것보다는 더 가치가 있어요.”',
      '“15는 어때요?”',
      '“50으로 하지요.”',
      '“음, 30이요. 이게 제 마지막 제안입니다.”',
      '“좋아요, 이건 당신 겁니다. 그런데 이걸 어떻게 가져갈 건가요?',
      '이건 차에 들어가지 않을 텐데요!”',
      '“두고 봅시다.” Boggis 씨는 말하고는 자신의 차를 가지러 밖으로 나갔습니다.',
      '차로 가는 길에, Boggis 씨는 웃지 않을 수 없었습니다.',
      '그 탁자는 모든 판매상이 꿈꾸는 것이었습니다.',
      '그는 자신의 행운을 믿을 수가 없었습니다.',
      '“아버지, 이게 그의 차에 안 들어가면 어쩌죠? 그가 돈을 내지 않을 수도 있어요.” Bert가 말했습니다.',
      'Rummins는 그때 한 가지 생각이 떠올랐습니다.',
      '“그가 원하는 건 다리뿐이야. 그를 위해 다리를 잘라 주자.” Rummins가 말했습니다.',
      '“좋은 생각이에요!” Bert가 말했습니다.',
      '그런 다음 Bert는 톱을 꺼내서 다리를 자르기 시작했습니다.',
    ],
    choices: [
      ['Boggis 씨는 탁자 다리를 자기 탁자에 붙이겠다고 말했다.', '`I can cut off the legs of your table and attach them to mine.` 과 일치한다.'],
      ['Rummins가 처음에 10파운드를 불렀다.', '`Ten pounds.` 는 Boggis 씨의 첫 제안이다. Rummins는 오히려 `It’s worth more than that.` 이라며 **50**을 불렀다.'],
      ['Boggis 씨는 마지막으로 30파운드를 제안했다.', '`Well, thirty. This is my final offer.` 와 일치한다.'],
      ['Bert는 탁자가 차에 안 들어가면 돈을 못 받을까 걱정했다.', '`He might not pay you` 와 일치한다.'],
      ['Bert는 톱을 꺼내 탁자 다리를 자르기 시작했다.', '마지막 문장 `took out a saw and began to cut off the legs` 와 일치한다.'],
    ],
    vocab: [
      ['add', '동', '덧붙여 말하다, 더하다', 'say further', 'remove 제거하다', 'addition 추가'],
      ['broken', '형', '부러진, 고장 난', 'damaged', 'whole 온전한', 'break 부수다'],
      ['cut off', '숙', '잘라 내다', 'chop off, remove', 'attach 붙이다', 'cut 자르다'],
      ['attach', '동', '붙이다, 부착하다', 'fasten, join', 'detach 떼다', 'attachment 부착(물)'],
      ['I’m afraid', '숙', '유감이지만, 미안하지만', 'unfortunately', '—', 'afraid 두려워하는'],
      ['final', '형', '마지막의, 최종의', 'last', 'first 처음의', 'finally 마침내'],
      ['offer', '명·동', '제안(하다)', 'proposal, suggest', 'refuse 거절하다', '—'],
      ['on one’s way to', '숙', '~로 가는 길에', 'while going to', '—', '—'],
      ['cannot help -ing', '숙', '~하지 않을 수 없다', 'cannot but + 동사원형', '—', '—'],
      ['dream of', '숙', '~을 꿈꾸다', 'long for', '—', 'dreamer 몽상가'],
      ['luck', '명', '행운, 운', 'fortune', 'misfortune 불운', 'lucky 운 좋은'],
      ['what if', '숙', '~하면 어쩌지?', 'suppose', '—', '—'],
      ['pay', '동', '(돈을) 지불하다', 'give money', '—', 'payment 지불'],
      ['saw', '명', '톱', '—', '—', 'saw-sawed-sawn 톱질하다'],
      ['take out', '숙', '꺼내다', 'pull out, bring out', 'put in 넣다', '—'],
    ],
    flow: [
      ['🪚', '두 번째 거짓말 — “다리만 쓰겠다”', '**He then added** — 복제품이라 속인 데 이어 ‘**우리 집 탁자 다리가 부러져서, 이 탁자 다리를 떼어 붙이겠다**’는 **그럴듯한 핑계**를 댄다. 이 거짓말이 결말의 씨앗이다.'],
      ['💷', '10 → 15 → 50 → 30파운드 흥정', '짧은 대사가 **탁구처럼** 오간다. Boggis 씨는 값을 **낮게**, Rummins는 **높게** 부르다 **30파운드**에 합의한다. `OK, it’s yours` 로 거래 성사.'],
      ['😄', 'Boggis 씨의 속마음', '**couldn’t help smiling / what every dealer dreamed of / couldn’t believe his luck** — 세 문장이 연달아 **들뜬 속마음**을 보여 준다. 독자만 아는 **극적 아이러니**.'],
      ['💡', 'Rummins 부자의 ‘친절한’ 생각', '차에 안 들어가면 돈을 **못 받을까** 걱정한 Bert, ‘**그가 원하는 건 다리뿐**’이라는 Rummins의 판단 → **톱**으로 다리를 자르기 시작한다. Boggis 씨의 거짓말이 **그대로 되돌아오는** 순간.'],
    ],
    cards: [
      { c: [1, 2, 3], en: 'He then added, “Hmm, I think I [[may buy]] it. / The legs of my table at home ((are broken)). / I can {{cut off}} the legs of your table and {{attach}} them [[to mine]].”',
        ko: '그런 다음 그는 덧붙였다, / “흠, 제가 그걸 살 수도 있을 것 같아요. / 우리 집에 있는 제 탁자의 다리가 부러졌거든요. / 당신 탁자의 다리를 잘라서 / 제 것에 붙일 수 있겠어요.”',
        note: '**해석 도움** — `mine` 은 **소유대명사**로 `my table` 을 대신한다. `attach A to B` 는 ‘A를 B에 붙이다’.',
        pts: [
          ['grammar', '**주어의 수 일치** — `The legs of my table ~ are broken`. 핵심 주어는 `The legs`(복수) → `are`. `of my table at home` 은 꾸밈말이다.'],
          ['grammar', '**소유대명사 mine / yours** — `mine = my table`. 같은 명사의 **반복을 피하려고** 쓴다.'],
          ['vocab', '**cut off ↔ attach** — ‘잘라 내다’ ↔ ‘붙이다’. 이 문장의 `cut off the legs` 가 이야기 결말에서 **그대로 실현**된다.'],
        ] },
      { c: [4, 5], en: '“[[How much]]?” Rummins asked. / “Not much, {{I’m afraid}}. This is just a reproduction,” said Mr. Boggis.',
        ko: '“얼마요?” Rummins가 물었다. / “유감이지만 많이는 아니에요. / 이건 그저 복제품이니까요.” Boggis 씨가 말했다.',
        note: '**해석 도움** — `I’m afraid` 는 ‘두렵다’가 아니라 **‘유감이지만, 미안하지만’**. 상대가 **듣기 싫은 말**을 할 때 앞뒤에 붙인다.',
        pts: [
          ['vocab', '**I’m afraid (that) ~** — 좋지 않은 소식을 **부드럽게** 전하는 표현. `I’m afraid not.`(아쉽지만 아니에요)'],
          ['grammar', '**How much?** — **가격**을 묻는 말. 셀 수 없는 양은 `how much`, 셀 수 있는 수는 `how many`.'],
          ['reading', '**거짓말의 반복** — 또 `just a reproduction` 을 내세워 값을 **깎는다**. 같은 거짓말을 되풀이하는 인물의 **계산된 태도**.'],
        ] },
      { c: [6, 7, 8], en: '“So how much?” / “Ten pounds.” / “Ten? It’s worth [[more than that]].”',
        ko: '“그래서 얼마요?” / “10파운드요.” / “10이요? / 그것보다는 더 가치가 있어요.”',
        note: '**해석 도움** — 대사에 **말한 사람 표시가 없다**. 흐름으로 읽는다: 묻는 사람 **Rummins** → 답하는 **Boggis** → 반박하는 **Rummins**.',
        pts: [
          ['grammar', '**비교급 + than** — `more than that` = ‘그것(10파운드)보다 더’. `that` 은 앞의 `Ten pounds` 를 가리킨다.'],
          ['reading', '**화자 추적** — 짧은 대사가 이어질 때는 **번갈아 말한다**는 원칙으로 누가 말하는지 따라간다. 내용일치 문제에서 **‘누가 몇 파운드를 불렀나’**가 자주 나온다.'],
        ] },
      { c: [9, 10, 11], en: '“[[How about]] fifteen?” / “{{Make it}} fifty.” / “Well, thirty. This is my ((final offer)).”',
        ko: '“15는 어때요?” / “50으로 하지요.” / “음, 30이요. / 이게 제 마지막 제안입니다.”',
        note: '**해석 도움** — `Make it fifty.` 는 ‘그걸 50으로 **하자**’. 흥정에서 **값을 정할 때** 쓰는 명령문이다.',
        pts: [
          ['grammar', '**How about + 명사/동명사?** — ‘~은 어때요?’ **제안**. `What about ~?` 와 같다. 동사가 오면 `How about going ~?`'],
          ['grammar', '**make + 목적어 + 목적격 보어** — `make it fifty` = ‘그것을 50으로 만들다(하다)’. 5형식 구조.'],
          ['reading', '**흥정의 흐름** — Boggis 10 → 15 / Rummins 50 / Boggis **30(최종)**. 두 사람의 **줄다리기**가 대사 길이만큼 **빠르게** 진행된다.'],
        ] },
      { c: [12, 13], en: '“OK, it’s [[yours]], but {{how are you going to take}} it? / This thing ((will not go in)) a car!”',
        ko: '“좋아요, 이건 당신 겁니다, / 그런데 이걸 어떻게 가져갈 건가요? / 이건 차에 들어가지 않을 텐데요!”',
        note: '**해석 도움** — `go in a car` 는 ‘차에 **들어가다(실리다)**’. 사물 주어 `This thing` 이 **크기 때문에** 안 실린다는 뜻이다.',
        pts: [
          ['grammar', '**be going to + 동사원형** — ‘~할 예정이다’. 의문문 `how are you going to take it?` = ‘**어떻게 가져갈 작정**이에요?’'],
          ['grammar', '**소유대명사 yours** — `it’s yours` = ‘그건 **당신 것**이다’. 거래가 **성사**되었음을 알리는 말.'],
          ['reading', '**복선** — ‘차에 안 들어간다’는 걱정이 뒤에서 Bert의 걱정 → **다리를 자르자**는 결정으로 이어진다.'],
        ] },
      { c: [14], en: '“[[We’ll see]],” Mr. Boggis said and went out {{to bring}} his car.',
        ko: '“두고 봅시다.” / Boggis 씨는 말하고는 / 자신의 차를 가지러 밖으로 나갔다.',
        note: '**해석 도움** — `We’ll see.` 는 ‘**두고 보자, 어떻게 되는지 보자**’. 결정을 **미루는** 말이다.',
        pts: [
          ['grammar', '**to부정사의 부사적 용법(목적)** — `went out to bring his car` = ‘차를 **가지러** 나갔다’.'],
          ['grammar', '**동사 병렬** — `said and went out` 두 과거동사가 `and` 로 이어진다. 주어 `Mr. Boggis` 하나를 공유한다.'],
        ] },
      { c: [15, 16, 17], en: '{{On his way to}} the car, Mr. Boggis [[couldn’t help smiling]]. / The table was ((what every dealer dreamed of)). / He couldn’t believe his luck.',
        ko: '차로 가는 길에, / Boggis 씨는 웃지 않을 수 없었다. / 그 탁자는 모든 판매상이 꿈꾸는 것이었다. / 그는 자신의 행운을 믿을 수 없었다.',
        note: '**해석 도움** — `what every dealer dreamed of` 는 ‘모든 판매상이 **꿈꾸던 것**’. `what` 이 **the thing which** 역할을 하며, 끝의 `of` 는 `dream of` 의 전치사다.',
        pts: [
          ['grammar', '**cannot help + -ing** — ‘~하지 않을 수 없다’. `couldn’t help smiling` = `couldn’t but smile`. `help to smile` ×.'],
          ['grammar', '**관계대명사 what = the thing(s) which** — 선행사를 **품고 있어** 앞에 명사가 없다. `what` 절 전체가 **보어**다.'],
          ['vocab', '**on one’s way to** — ‘~로 가는 길에’. `on one’s way home`(집에 가는 길에)은 `home` 이 부사라 `to` 가 없다.'],
        ] },
      { c: [18, 19], en: '“Dad, [[what if]] this thing doesn’t go in his car? He {{might not pay}} you,” said Bert. / Rummins then had an idea.',
        ko: '“아버지, 이게 그의 차에 안 들어가면 어쩌죠? / 그가 돈을 내지 않을 수도 있어요.” Bert가 말했다. / Rummins는 그때 한 가지 생각이 떠올랐다.',
        note: '**해석 도움** — `What if ~?` 는 ‘**~하면 어쩌지?**’. 걱정되는 **가정**을 말할 때 쓴다. 뒤에는 **평서문 어순**의 절이 온다.',
        pts: [
          ['grammar', '**What if + 주어 + 동사?** — `What (will happen) if ~?` 의 줄임. 미래 걱정이어도 **현재시제**(`doesn’t go`)를 쓴다.'],
          ['grammar', '**might(추측)** — ‘~일지도 모른다’. `may` 보다 **가능성이 약한** 추측. 부정 `might not pay` = ‘안 낼지도 모른다’.'],
          ['reading', '**동기의 확인** — 부자가 다리를 자르는 이유는 **악의가 아니라 돈을 확실히 받기 위해서**다. 그래서 결말의 아이러니가 더 커진다.'],
        ] },
      { c: [20, 21, 22], en: '“[[What he wants]] is only the legs. {{Let’s cut}} the legs off for him,” said Rummins. / “Great idea!” said Bert. / Bert then ((took out)) a saw and began {{to cut off}} the legs.',
        ko: '“그가 원하는 건 다리뿐이야. / 그를 위해 다리를 잘라 주자.” Rummins가 말했다. / “좋은 생각이에요!” Bert가 말했다. / 그런 다음 Bert는 톱을 꺼내서 / 다리를 자르기 시작했다.',
        note: '**해석 도움** — `What he wants` 가 **문장의 주어**다. ‘그가 **원하는 것**은’. `what` 절 주어는 **단수** 취급이라 `is`.',
        pts: [
          ['grammar', '**관계대명사 what 절 주어 + 단수동사** — `What he wants is only the legs.` 보어가 복수(`the legs`)여도 동사는 **주어(what절)**에 맞춰 `is`.'],
          ['grammar', '**cut A off / cut off A** — 구동사의 목적어가 **명사**면 두 위치 모두 가능(`cut the legs off`, `cut off the legs`). **대명사**면 반드시 가운데: `cut them off`.'],
          ['grammar', '**Let’s + 동사원형** — ‘~하자’(제안). 부정은 `Let’s not cut ~`.'],
        ] },
    ],
  },

  /* ─────────────────────────── Ch4 ─────────────────────────── */
  {
    no: 4, type: '교훈', answer: 4,
    q: '다음 글을 포함한 이야기 전체가 주는 교훈으로 가장 적절한 것은?',
    summary: 'Boggis 씨가 차를 가지고 돌아왔을 때, 탁자 다리는 이미 잘려 있었어요. Rummins는 “걱정 마세요. 호의로 한 거예요. 이것에 대한 비용은 받지 않을게요.”라고 말했지요. 값진 탁자를 헐값에 가져가려고 ‘복제품이니 다리만 쓰겠다’고 거짓말했던 Boggis 씨는, 그 거짓말 때문에 보물을 잃고 너무 충격을 받아 아무 말도 할 수 없었어요.',
    main_idea_en: 'Mr. Boggis’s own lie comes back to him: the priceless table is ruined as a “favor,” and he is left speechless.',
    title_en: 'A Favor That Ruined Everything',
    illust: `Wide banner photograph of a plain farmhouse room floor: a beautiful glossy eighteenth-century mahogany
      tabletop lying flat on worn wooden floorboards with no legs, and beside it four elegantly carved curved
      cabriole table legs laid neatly in a row, their freshly sawn ends pale, a small scatter of fine sawdust around
      them, an old hand saw resting against the wall. Natural soft diffused daylight from a side window, bright
      even illumination, high-key exposure, low contrast, warm red-brown wood on pale boards. Quiet ironic still-life
      editorial photography, sharp detail. --ar 16:5 --v 8.1 --no car, antique shop, complete table standing,
      armchair, ${NEG}`,
    ko: [
      'Boggis 씨가 돌아왔을 때, 탁자 다리는 이미 잘려 있었습니다.',
      '“걱정하지 마세요, 이건 호의로 한 거예요. 이것에 대해 비용을 청구하지는 않을게요.” Rummins가 말했습니다.',
      'Boggis 씨는 너무 충격을 받아서 아무 말도 할 수 없었습니다.',
    ],
    choices: [
      ['Practice makes perfect.', '‘연습이 완벽을 만든다’ — **노력·연습**과 관련된 장면이 없다.'],
      ['Two heads are better than one.', '‘백지장도 맞들면 낫다’ — Rummins 부자의 **협력**이 결과적으로 **탁자를 망쳤으니** 교훈이 될 수 없다.'],
      ['The early bird catches the worm.', '‘일찍 일어나는 새가 벌레를 잡는다’ — **부지런함**과 무관하다.'],
      ['Honesty is the best policy.', '‘정직이 최선의 방책이다’ — Boggis 씨는 **복제품이다, 다리만 쓰겠다**는 **거짓말**을 했고, 바로 그 거짓말 때문에 탁자를 잃었다.'],
      ['Every cloud has a silver lining.', '‘모든 먹구름 뒤에는 한 줄기 빛이 있다’ — 불행 뒤 **좋은 일**이 오는 이야기가 아니다. 결말은 **충격**으로 끝난다.'],
    ],
    vocab: [
      ['come back', '숙', '돌아오다', 'return', 'go away 떠나다', '—'],
      ['worry', '동', '걱정하다', 'be anxious', 'relax 안심하다', 'worried 걱정하는'],
      ['favor', '명', '호의, 친절한 행위', 'kindness, service', '—', 'do ~ a favor ~의 부탁을 들어주다'],
      ['charge', '동', '(비용을) 청구하다', 'bill', '—', 'free of charge 무료로'],
      ['shocked', '형', '충격을 받은', 'stunned, astonished', 'calm 침착한', 'shock 충격(을 주다) / shocking 충격적인'],
      ['anything', '대', '(부정문) 아무것도', 'a thing', 'everything 모든 것', '—'],
    ],
    flow: [
      ['🚗', '돌아온 Boggis 씨', '차를 가지고 돌아온 순간, 탁자 다리는 **이미 잘려 있었다**(`had been cut off`). 과거완료 수동태가 ‘**그가 오기 전에 이미 끝난 일**’임을 알린다.'],
      ['🙂', 'Rummins의 선의', '**this was a favor / I won’t charge you** — Rummins는 **친절을 베풀었다**고 믿는다. 악의 없는 선의라서 더 **아이러니**하다.'],
      ['😶', '말문이 막힌 Boggis 씨', '**so shocked that he couldn’t say anything** — 진실을 말하면 자신의 거짓말이 드러나므로 **아무 말도 할 수 없다**.'],
      ['🔁', '이야기의 교훈 — 거짓말의 대가', '‘**복제품이다, 다리만 필요하다**’는 거짓말이 **그대로 실현**되어 보물을 잃었다. **Honesty is the best policy.** 라는 교훈으로 이야기가 닫힌다.'],
    ],
    cards: [
      { c: [1], en: '((When)) Mr. Boggis came back, the legs [[had been cut off]].',
        ko: 'Boggis 씨가 돌아왔을 때, / 탁자 다리는 이미 잘려 있었다.',
        note: '**해석 도움** — `had been cut off` 는 **과거완료 수동태**. 그가 **돌아온 시점(과거)**보다 **먼저** 다리가 **잘린 상태**였다.',
        pts: [
          ['grammar', '**과거완료 수동태 had been + p.p.** — ‘(이미) ~되어 있었다’. 기준 시점 `came back` 보다 **앞선 일**이면서 다리는 **잘리는 대상**이므로 수동.'],
          ['grammar', '**cut 의 3단 변화** — cut-**cut**-**cut**. 과거분사도 `cut` 이라 `had been cut` 이 된다.'],
          ['reading', '**결말의 첫 문장** — 앞 단락에서 Bert가 톱질을 **시작했다**(`began to cut`)면, 여기서는 **이미 끝났다**. 장면 사이 시간의 **공백**을 과거완료가 메운다.'],
        ] },
      { c: [2], en: '“Don’t worry, this was [[a favor]]. I {{won’t charge}} you for this,” said Rummins.',
        ko: '“걱정하지 마세요, 이건 호의로 한 거예요. / 이것에 대해 비용을 청구하지는 않을게요.” / Rummins가 말했다.',
        note: '**해석 도움** — `charge A for B` 는 ‘B에 대해 A에게 **요금을 청구하다**’. `won’t` 는 `will not` — ‘~하지 **않겠다**’는 **의지**.',
        pts: [
          ['vocab', '**charge (A) for B** — ‘B의 값으로 (A에게) 청구하다’. `free of charge` = 무료로.'],
          ['vocab', '**favor** — ‘호의, 친절한 행위’. `Can you do me a favor?`(부탁 하나 들어줄래?)로 자주 쓴다. 영국식 철자 `favour`.'],
          ['reading', '**선의의 아이러니** — Rummins는 **돈을 더 받지도 않는** 친절을 베풀었다고 생각한다. 그러나 그 친절이 **Boggis 씨에겐 최악의 결과**다.'],
        ] },
      { c: [3], en: 'Mr. Boggis was ((so shocked that)) he [[couldn’t say anything]].',
        ko: 'Boggis 씨는 너무 충격을 받아서 / 아무 말도 할 수 없었다.',
        note: '**해석 도움** — `so ~ that ... can’t` 는 ‘너무 ~해서 …할 수 없다’. `too shocked to say anything` 으로 바꿔 쓸 수 있다.',
        pts: [
          ['grammar', '**so ~ that 주어 can’t ↔ too ~ to** — `He was so shocked that he couldn’t say anything.` = `He was too shocked to say anything.` 서술형 **전환** 단골.'],
          ['grammar', '**-ed 형용사 vs. -ing 형용사** — `shocked`(충격을 **받은**: 사람의 감정) / `shocking`(충격을 **주는**: 사물·사건). 2과의 `excited` 와 같은 규칙.'],
          ['reading', '**침묵의 의미** — 그가 말을 못 하는 것은 충격 때문이기도 하지만, **진실을 말하면 자신의 거짓말이 드러나기** 때문이다. 이야기 전체의 **교훈**이 여기에 모인다.'],
        ] },
    ],
  },
];
