/* ===================================================================
 * 천재(조수경) 영어II Lesson 3 — 원문 정본 (ground truth)
 * ===================================================================
 * 원문 PDF(영어2 천재(조) 본문 해석.pdf)에서 verbatim 전사.
 * 문장 누락 검증의 기준. ★ 임의 수정 금지.
 * 본문 5챕터(55문장) + READ MORE 1챕터(15문장) = 총 70문장.
 * =================================================================== */

export const SOURCE = [
  {
    no: 1,
    subtitle: "도입 + Help Yourself and Help Me",
    sentences: [
      "Plants are amazing.",
      "Throughout their long existence, they have created diverse survival strategies.",
      "Seeds, in particular, are one of the strongest survival techniques they have developed.",
      "Let's discover the fascinating and mysterious world of seeds.",
      "Plants will do anything to spread their seeds.",
      "They offer tasty food to animals in return for distributing their seeds.",
      "Jackfruit, the world's largest tree fruit, has a sweet smell that attracts animals, similar to pineapples and bananas.",
      "It tempts animals to eat delicious fruit flesh, thereby getting them to eat the seeds.",
      "The fruit flesh is digested by the animals that consume it, but the seeds are not digested and pass through the animals' digestive tracts untouched.",
      "When these animals poop out the seeds, the seeds begin to sprout and grow, and jackfruit spreads.",
      "In exchange for a satisfying meal, the animals spread the jackfruit seeds.",
    ],
  },
  {
    no: 2,
    subtitle: "The Worst Free Rider",
    sentences: [
      "Many plants opt to scatter their seeds by providing food to animals, but not all of them do.",
      "Some plants attach their seeds to passing animals, spreading them without any return benefit.",
      "Instead of tempting sweet fruits, these seeds are equipped with sharp hooks or needles.",
      "Devil's claw stands out as the most vicious of these plants.",
      "Devil's claw primarily inhabits the Kalahari Desert in South Africa, Namibia, and Botswana.",
      "Its blossoms resembling pink trumpets eventually transform into fruits with many hooks.",
      "As these fruits dry, they become solid, and their hooks become tough enough to attach to the bodies of animals.",
      "As animals pass by, the hooks extending in all directions will keep the dried fruit firmly attached to their fur.",
      "As the animals move away, the seeds from the fruit will be scattered in various locations.",
      "The attached hooks cause severe pain to the animals, making them feel like the devil is scratching them with its horrifying claws.",
      "That is how devil's claw became known as the worst free rider.",
    ],
  },
  {
    no: 3,
    subtitle: "Deceptive Seeds",
    sentences: [
      "Out of numerous creative methods for spreading seeds, silver arrow-reed in South Africa has a particularly unique one.",
      "Silver arrow-reed spreads its seeds by deceiving dung beetles.",
      "Dung beetles, by nature, roll antelope dung and bury it in the ground to eat or lay eggs in.",
      "Silver arrow-reed seeds are dark brown, round, and slightly larger than 1 cm in size.",
      "Their visual appearance and smell are quite similar to antelope dung.",
      "So when a seed falls onto the ground, dung beetles will approach the fallen seed within minutes.",
      "Then, they carefully roll the seed away as if it were antelope dung.",
      "That is why dung beetles are often spotted rolling silver arrow-reed seeds that look and smell like dung balls.",
      "When they try to eat the seeds or lay eggs inside of them, however, the confused beetles will realize they cannot.",
      "They have no choice but to abort and search for real dung balls.",
      "By tricking dung beetles to roll away and bury the seeds, silver arrow-reed is able to spread and plant its seeds better.",
    ],
  },
  {
    no: 4,
    subtitle: "The Wind Beneath My Wings",
    sentences: [
      "Not all seeds are transported by animals.",
      "Some are carried by the wind.",
      "This approach is used by maple trees.",
      "Maple seeds are shaped like a boomerang with irregular ridges on the surface.",
      "When a maple seed falls from the tree, it spins around.",
      "This rotation makes the seed stay in the air longer and fly farther.",
      "It is similar to how helicopters get lifted and stay in the air using their propellers.",
      "The rotation caused by its wings allows the maple seed to elevate twice as high as non-rotating seeds.",
      "As a result, it can travel much farther from the parent tree.",
      "The rotation also slows down the speed of the fall, and the seed softly lands on the ground.",
      "This helps reduce the damage to the seed during the fall.",
    ],
  },
  {
    no: 5,
    subtitle: "Rising from the Ashes",
    sentences: [
      "In most cases, mature seeds are automatically separated from the parent plant.",
      "However, some plants only release their seeds after enduring an extreme experience.",
      "Eucalyptus is one such example.",
      "Eucalyptus seeds are as tiny as grains of sand, but they are bound together in firm capsules.",
      "Birds cannot eat them because they are securely protected by a strong shell.",
      "In long periods of hot and dry weather, eucalyptus leaves rub together and naturally catch fire because the leaves contain highly flammable oil.",
      "The extreme heat from the fire causes the shell to crack open.",
      "Finally, the seeds come out of the shell, hit the ground, and begin to grow.",
      "The fallen seeds are conveniently concealed in the soft ash left over after the fire, which protects them from the harsh environment.",
      "Wildfire, often started by the parent tree, also burns practically everything on the ground, destroying other plants that would compete with the seeds for the water and sunlight needed for growth.",
      "As you can see, eucalyptus is only able to reproduce provided that there is fire.",
    ],
  },
  {
    no: 6,
    subtitle: "READ MORE · The Tallest Tree on Earth",
    sentences: [
      "Where would you find the tallest tree in the world?",
      "You will have to visit Redwood National Park in the United States to find it.",
      "Redwoods are known as the tallest plants in the world.",
      "Typically, redwoods grow over 60 m, and it is easy to find them exceeding 90 m.",
      "Among them, a redwood named Hyperion stands enormously tall, reaching over 115 m.",
      "It holds the record as the world's tallest tree.",
      "Before it was discovered, Helios, which was 114 m, was considered to be the tallest tree.",
      "However, in 2006, two naturalists found a tree taller than Helios.",
      "They were so overwhelmed by its height that they named it after one of the Titans from Greek myths, Hyperion.",
      "Hyperion was the name of the Titan of the Sun, meaning \"the highest one.\"",
      "However, the odds of you seeing Hyperion at the park are slim to none.",
      "The park keeps its precise location a secret to protect it from potential harm caused by visitors.",
      "You may assume you can easily find it among the redwoods, but it is harder than you think.",
      "The height difference between Hyperion and its neighboring redwoods is merely a few meters, making it nearly impossible to identify from the ground.",
      "Every redwood in the park will look like a giant from the bottom.",
    ],
  },
];
