/* ===================================================================
 * 신서고 YBM(박준언) 영어II Lesson 1 — 원문 정본 (ground truth)
 * ===================================================================
 * 원문 PDF(YBM 1과.pdf)에서 verbatim 전사. 문장 누락 검증의 기준.
 * ★ 이 파일은 원문이므로 임의 수정 금지. 오탈자 발견 시 PDF 재확인 후에만 수정.
 * =================================================================== */

export const SOURCE = [
  {
    no: 1,
    subtitle: 'The Story of Hip-Hop Music (도입)',
    sentences: [
      "Imagine an urban area that is fast becoming a slum after an economic recession.",
      "Businesses close their doors and building owners have left.",
      "The area is full of abandoned buildings.",
      "There is no heating even in winter.",
      "Only those who can't afford to move out remain.",
      "Unemployment is high, many gangs emerge, and gang violence between young people becomes an everyday thing.",
      "Despair is on every street corner.",
      "One day, however, a gang called the Ghetto Brothers, which is respected because of its free meal and medical care programs, decides to stop fighting and instead persuade young people to unite and create a better community.",
      "They suggest a peace treaty.",
      "\"This is for peace, men.",
      "The violence took away our brothers.",
      "We're not gangsters anymore.",
      "We've got to make this town a better place to live.\"",
      "Thanks to these new voices, gang leaders from all over the area sign the treaty.",
      "Never again will they use violence to solve their disputes.",
      "This is the Bronx in the New York of the early 1970s, where hip-hop music was born as a major part of a new culture of peace created by African Americans and immigrants.",
      "The story of hip-hop, now one of the world's most dominant music genres, is a fascinating one.",
      "Let's explore it.",
    ],
  },
  {
    no: 2,
    subtitle: 'DJing, Breakdancing, and MCing',
    sentences: [
      "After the peace treaty, the gangs that had fought one another started partying together.",
      "Abandoned buildings and parking lots were used for events called block parties.",
      "What eventually emerged from these parties?",
      "A vibrant youth movement called hip-hop culture, based on DJing, breakdancing, MCing, and graffiti.",
      "It replaced gang violence with music, dance, art, and style.",
      "The most popular block parties were those hosted by DJ Kool Herc, who is regarded as the founding father of hip-hop.",
      "Herc's party for his sister's birthday in August 1973 is now known as the birthplace of hip-hop music because of his new DJ technique.",
      "At this party, using two turntables at the same time, Herc played two copies of the same record and then switched between them to extend the drum section known as the break.",
      "No longer did people have to stop dancing at the end of the record while the DJ changed the LP disc.",
      "Kool Herc's style of DJing quickly became influential in the rise of hip-hop music and breakdancing.",
      "The break section became the most anticipated part of a song.",
      "People would form dancer circles and use the break to show off their individual dancing skills.",
      "Kool Herc named the people dancing to his music B-Boys and B-Girls, short for Break-Boys and Break-Girls.",
      "These people began to dance in groups in the streets and build a street dance battle culture.",
      "DJs like Kool Herc would speak in rhythm and rhyme over instrumental parts of songs to excite the crowd.",
      "They would shout phrases like \"To the beat\" and \"You don't stop!\"",
      "This was the beginning of rapping or MCing.",
      "When DJs couldn't do both DJing and rhythmic shouting at the same time, they asked a friend to take the role of addressing the audience, that is, of the Master of Ceremonies or MC, at their parties.",
      "This separate role became MCing.",
    ],
  },
  {
    no: 3,
    subtitle: 'The Origin of the Word Hip-Hop',
    sentences: [
      "Then where did the word hip-hop originate from?",
      "Nobody knows the exact origin, but it is said that the word hip-hop was first used at a block party.",
      "A young man at the party was about to join the army.",
      "His good friend, the MC of the party, reminded him in a jokey way that his days of freedom were over by moving across the stage like a military instructor to the beat, chanting, \"Hip-hop-hip-hop-hip-hop.\"",
      "The crowd loved it.",
      "After that, MCs tried out new lines at parties like \"Hip, hop, hippy to the hippy hop-bop,\" \"I said a hip-hop, a hibbit, hibby-dibby, hip-hip-hop and you don't stop.\"",
      "Such lines became a standard part of rap and were included in the lyrics of the first recorded hip-hop album, Rapper's Delight (1979), which was an immediate success.",
      "The new music and dancing spread very fast.",
      "There was a sharp unexplained decline in violence during the 1980s in New York.",
      "One police officer asked a boy on the street if he knew why.",
      "The boy said, \"It's because they're dancing.\"",
    ],
  },
  {
    no: 4,
    subtitle: 'The Messages of Hip-Hop',
    sentences: [
      "Rap lyrics, which started as the party chants of early hip-hop, typically focused on having a good time together and boasting about the ability of the DJ or the rapper.",
      "However, a significant shift occurred during the rise of hip-hop music in the 1980s.",
      "Most importantly, the appearance of The Message by the group Grandmaster Flash and Furious Five in 1982 was groundbreaking.",
      "This song's powerful lyrics detailed the harsh realities of life in the ghetto, including the sad story of a boy who was born there and had to live and die as a second-class citizen.",
      "With this song, hip-hop, whose original aim was creating peace through partying, started a new tradition of social criticism against injustice.",
      "The Message became one of the most influential rap singles of all time, and was followed by many hip-hop songs that confronted racial discrimination in the 1980s and 1990s.",
      "At the same time, their music with its rhythmic beat and rapping made people move or dance.",
      "People heard the social message while moving to the beat.",
      "Also, a new attitude gradually emerged in hip-hop lyrics, which can be summarized as \"respect.\"",
      "Hip-hop music began to be a way to express respect for one another, and particularly for hip-hop pioneers.",
      "For rappers, the pioneers are heroes who overcame hardship and injustice and went on to create new music and culture.",
      "Therefore, many hip-hoppers agree that they cannot have too much respect for these heroes.",
      "The phrase \"something from nothing,\" often used to summarize the genre's history, is also an expression of admiration for early hip-hoppers, who developed a new culture in the ghetto despite very limited resources.",
      "Rappers also proudly expressed their feeling that they, too, and perhaps the audience, had suffered and survived in a similar way to the pioneers.",
      "This is why the message of respect is about both self-worth and respect for others.",
      "The importance of the idea of respect in hip-hop cannot be emphasized strongly enough.",
    ],
  },
  {
    no: 5,
    subtitle: 'Hip-Hop in the 21st Century',
    sentences: [
      "\"The HipHop Declaration of Peace,\" presented to the UN on May 16th, 2001, officially recognized hip-hop as an international culture of peace.",
      "This document reminds us of hip-hop's original mission to bring peace to the Bronx, implying global respect for hip-hop history.",
      "When hip-hop artist Kendrick Lamar was awarded a Pulitzer Prize for Music in 2018, it was another important event.",
      "It meant that hip-hop, which started as underground music, had become a major art form like classical music.",
      "If hip-hop music was born as part of a cultural movement for peace in the 1970s, today more and more people regard it as a powerful means to express oneself, fight against injustice, bring about change through social messages, and still be engaged with music and connected to others.",
      "With its unique and growing appeal, hip-hop continues to be a global phenomenon.",
    ],
  },
];
