/* 봉영여중3 추가지문 05~08 저작 데이터 — _author-EX.mjs 가 모아서 쓴다.
 * 05 빈칸은 정답(original)으로 채우고, 08 주어진 문장은 정답 위치 ③ 에 복원했다(_SOURCE-EX.js 주석). */
import { EXAM, LIGHT, NO } from './_author-EX-1.mjs';

export const chapters = [
  /* ── 05 빈칸 내용 추론 ───────────────────────────── */
  {
    no: 5, exam: EXAM, type: '빈칸', answer: 2,
    question: '다음 빈칸에 들어갈 말로 가장 적절한 것은?',
    summary: '위대한 작곡가들도 당대에는 오해를 받았는데, 그들의 음악이 완전히 새로워서 사람들에게 익숙하지 않았기 때문이에요. 하지만 바로 그 새로움이 그들을 위대하게 만들어요. 영화 ‘아마데우스’의 살리에리는 훌륭한 작곡가였지만, 그의 곡은 당시 다른 사람들의 곡과 똑같이 들렸기 때문에 독창적이지 않아 위대한 작곡가가 되지 못했어요.',
    mainIdea: 'Great composers are great because their works are original, while Salieri’s music only sounded like everyone else’s.',
    titleEn: 'Originality Makes Great Composers',
    ko: [
      '여러분은 가장 위대한 작곡가들 중 몇몇이 그들 당대에는 오해를 받았다는 말을 거듭해서 듣는다.',
      '모든 사람이 베토벤, 브람스, 또는 스트라빈스키의 작품을 그들 당대에 이해할 수 있었던 것은 아니었다.',
      '이러한 초기의 수용 부족의 이유는 익숙하지 않음이다.',
      '음악적 형식, 즉 그 안에 표현된 아이디어가 완전히 새로웠다.',
      '그런데도, 이것이 바로 그들을 그토록 위대하게 만드는 것들 중 하나이다.',
      '유능한 작곡가들은 자기 자신만의 아이디어를 가지고 있다.',
      '여러분은 고전 영화 ‘아마데우스’를 본 적이 있는가?',
      '작곡가 안토니오 살리에리는 이 영화의 ‘진행자’이다. 그는 가장 유명한 위대하지 않은 작곡가 중 한 명으로 묘사되는데, 그는 모차르트와 같은 시대에 살았고 그에게 완전히 가려졌다.',
      '그런데 살리에리는 나쁜 작곡가가 아니었다. 사실 그는 매우 훌륭한 작곡가였다.',
      '그러나 그의 작품이 독창적이지 않았기 때문에 그는 세계의 위대한 작곡가 중 한 명은 아니었다.',
      '그가 쓴 곡은 당시 다른 모든 사람들이 작곡하고 있던 것과 똑같이 들렸다.',
    ],
    choices: [
      ['simple', '단순함은 이 글의 기준이 아니다.'],
      ['original', '남들과 똑같이 들렸다 = **독창적이지 않았다** — **정답**.'],
      ['familiar', '익숙함은 오히려 **위대하지 않은** 쪽의 특징이다.'],
      ['conventional', '관습적이었다면 남들과 같은 것이므로 {wasn’t} 와 함께 쓰면 **반대** 뜻이 된다.'],
      ['understandable', '위대한 작곡가는 당대에 **이해받지 못했다** — 기준이 반대다.'],
    ],
    vocab: [
      'composer|명|작곡가|songwriter|—|compose 작곡하다',
      'composition|명|곡, 작곡, 작품|piece, work|—|compose 작곡하다',
      'be misunderstood|숙|오해받다, 진가를 인정받지 못하다|—|—|misunderstanding 오해',
      'initial|형|초기의, 처음의|early, first|final 마지막의|initially 처음에',
      'acceptance|명|수용|approval|rejection 거부|accept 받아들이다',
      'unfamiliarity|명|익숙하지 않음, 생소함|strangeness|familiarity 익숙함|unfamiliar 익숙하지 않은',
      'effective|형|유능한, 효과적인|capable|ineffective 효과 없는|effect 효과',
      'depict|동|묘사하다|portray, describe|—|depiction 묘사',
      'overshadow|동|가리다, 무색하게 하다|outshine|—|shadow 그림자',
      'nongreat|형|대단하지 않은|ordinary|great 위대한|—',
      'original|형|독창적인|creative, novel|conventional 관습적인|origin 기원',
      'conventional|형|관습적인, 전통적인|traditional|original 독창적인|convention 관습',
      'understandable|형|이해할 수 있는|clear|incomprehensible 이해할 수 없는|understand 이해하다',
    ],
    flow: [
      ['🎼', '통념 — 위대한 작곡가도 오해받았다', '베토벤·브람스·스트라빈스키도 당대에는 **이해받지 못했다** — 이유는 **생소함(unfamiliarity)**.'],
      ['💡', '반전 — 새로움이 위대함의 조건', '{And yet} — 그 **새로움**이 바로 그들을 위대하게 만든다. 유능한 작곡가는 **자기만의 아이디어**가 있다.'],
      ['🎬', '예시 — 살리에리', '영화 ‘아마데우스’의 살리에리는 훌륭한 작곡가였지만 **모차르트에게 가려졌다**.'],
      ['✅', '빈칸 — ② original', '그의 곡은 **남들과 똑같이 들렸다** → 그의 작품은 **독창적(original)**이지 않았다. 정답 ②.'],
    ],
    cards: [
      {
        covers: [1],
        en: 'You hear again and again [r:that] some of the greatest composers | [g:were misunderstood] in their own day.',
        note: '**해석 도움** — "가장 위대한 작곡가 중 몇몇이 그들 **당대에는 오해를 받았다**는 말을 거듭 듣는다." 글이 **통념**으로 시작한다.',
        points: [
          ['grammar', '**[수업 필기] 명사절 접속사 that** — {hear} 의 목적어 {that ~}(필기 /). 접속사 뒤 완전한 문장.'],
          ['grammar', '**be misunderstood (수동태)** — "**오해받다, 진가를 인정받지 못하다**"(수업 단어표). 밑줄.'],
          ['vocab', '**again and again / in their own day** — 거듭해서 / **그들 당대에**.'],
        ],
      },
      {
        covers: [2],
        en: '[r:Not everyone] could understand the compositions of Beethoven, Brahms, or Stravinsky | in their day.',
        note: '**해석 도움** — "**모든 사람이** 그 작품을 이해할 수 있었던 **것은 아니다**." 일부는 이해하지 못했다는 뜻.',
        points: [
          ['grammar', '**[수업 필기] 부분부정 Not + every-** — 동그라미 친 {Not} 과 {every}. "모두 ~인 것은 아니다"({No one could ~} 은 "아무도 ~ 못했다" = 전체부정).'],
          ['vocab', '**composition** — "**곡, 작곡, 작품**"({compose} 작곡하다, {composer} 작곡가).'],
        ],
      },
      {
        covers: [3, 4],
        en: 'The reason [h:for this initial lack of acceptance] [g:is] [r:unfamiliarity]. | [h:The musical forms], or [h:ideas] [r:expressed within them], [g:were] completely new.',
        note: '**해석 도움** — 처음에 받아들여지지 못한 이유는 **익숙하지 않음**이다. 음악적 형식, **즉** 그 안에 표현된 아이디어가 **완전히 새로웠다**.',
        points: [
          ['grammar', '**[수업 필기] 주어 + 수식어 → 단수 동사** — S {The reason} ({for this initial lack of acceptance}) → V {is}. 괄호를 걷어내면 단수 주어다.'],
          ['vocab', '**[수업 필기] un-familiarity** — 동그라미 친 {un-} 은 **반대** 접두사: {familiarity} 익숙함 → {unfamiliarity} **익숙하지 않음**.'],
          ['grammar', '**[수업 필기] S1, or S2 → were** — {forms}(S1) {or} {ideas}(S2). {expressed within them} 은 과거분사 **후치수식**. 여기서 {or} 는 "**즉**"(바꿔 말하기).'],
        ],
      },
      {
        covers: [5, 6],
        tags: ['title'],
        en: 'And yet, this is exactly [h:one of the things] [r:that] [g:makes] them so great. | Effective composers have their own ideas.',
        note: '**해석 도움** — {And yet}(그런데도) — **새로움**이 바로 그들을 위대하게 만든다. **유능한 작곡가는 자기만의 아이디어가 있다** → 빈칸의 열쇠.',
        points: [
          ['grammar', '**[수업 필기] makes 의 수 일치** — 밑줄 친 {makes}. 관계사절 {that makes ~} 의 선행사를 {one}(하나)으로 보아 **단수** 동사. {one of the + 복수명사}.'],
          ['grammar', '**make + 목적어 + 형용사** — {makes them so great} "그들을 **그토록 위대하게** 만든다".'],
          ['reading', '**this = 새로움(unfamiliarity)** — 오해의 원인이었던 새로움이 위대함의 조건이라는 **반전**.'],
        ],
      },
      {
        covers: [7, 8],
        en: '[g:Have you ever seen] the classic movie Amadeus? | The composer Antonio Salieri is the “host” of this movie; | [h:he’s] [g:depicted as] one of the most famous nongreat composers | — he lived at the time of Mozart and [g:was completely overshadowed by] [r:him].',
        note: '**해석 도움** — 영화 ‘아마데우스’의 살리에리는 **가장 유명한 위대하지 않은 작곡가**로 묘사된다. 모차르트와 같은 시대에 살았고 **그(모차르트)에게 완전히 가려졌다**.',
        points: [
          ['grammar', '**[수업 필기] Have you ever p.p.? — 현재완료 경험** — 박스 친 {Have you ever seen}. "~해 본 적 있니?"'],
          ['grammar', '**[수업 필기] he’s = he is + depicted (수동태)** — {be depicted as} "~**로 묘사되다**". he = **Salieri**(화살표).'],
          ['reading', '**[수업 필기] him = Mozart** — 화살표로 연결. {be overshadowed by} "~에게 **가려지다**". 지칭을 바꿔 묻는 문제에 주의.'],
          ['vocab', '**nongreat / host** — {non-} 부정 접두사 "**대단하지 않은**" / 진행자(따옴표 = 비유적 표현).'],
        ],
      },
      {
        covers: [9, 10],
        en: 'Now, Salieri wasn’t a bad [h:composer]; in fact, he was a very good [h:one]. | But he wasn’t one of the world’s great composers | [r:because] his work wasn’t [g:original].',
        note: '**해석 도움** — 살리에리는 나쁜 작곡가가 아니었고 **사실 매우 훌륭한 작곡가**였다. 그러나 작품이 **독창적이지 않아서** 위대한 작곡가는 아니었다 — **빈칸 = original**.',
        points: [
          ['grammar', '**[수업 필기] 대명사 one = composer** — 동그라미 {composer} ← {one}. 앞의 셀 수 있는 명사를 받는다.'],
          ['vocab', '**[수업 필기] 빈칸 정답 ② original (중요)** — "**독창적인**". 필기 "original: **기원**" 은 명사 {origin}(기원) → {original}(독창적인, 원래의). ③ familiar ④ conventional ⑤ understandable 은 "남들과 같다" 쪽이라 반대, ① simple 은 무관.'],
          ['vocab', '**in fact** — "**사실은**". 앞 말을 더 강하게 이어 준다(나쁘지 않다 → 매우 훌륭했다).'],
        ],
      },
      {
        covers: [11],
        en: '[h:What he wrote] [g:sounded just like] [h:what everyone else was composing] at the time.',
        note: '**해석 도움** — "**그가 쓴 것**은 당시 **다른 모든 사람들이 작곡하던 것**과 똑같이 들렸다." 빈칸 문장의 **재진술**(= not original).',
        points: [
          ['grammar', '**[수업 필기] 관계대명사 what + 주어** — [{What he wrote}] 가 주어(S) → V {sounded}. {what} = {the thing(s) which}. 뒤의 {what everyone else ~} 도 같은 {what}.'],
          ['grammar', '**[수업 필기] sound like + 명사** — 감각동사 {sound} 뒤 **명사**면 {like}, 형용사면 바로: {sounded just like ~}(밑줄) / {sounds great}.'],
        ],
      },
    ],
    prompt: `Photorealistic interior photograph, wide banner composition. A bright eighteenth-century style music room: a polished harpsichord beside a grand piano, loose sheets of music with blank staff lines scattered on a small table, a feather quill in an inkpot, tall windows with pale curtains. Elegant, thoughtful classical mood. ${LIGHT}, ivory, soft gold and pale blue. ${NO}, musical notation, portraits, stage audience, monkeys, office --ar 16:5 --v 8.1`,
  },

  /* ── 06 요약문 완성 ──────────────────────────────── */
  {
    no: 6, exam: EXAM, type: '요약문', answer: 4,
    question: '다음 글의 내용을 한 문장으로 요약하고자 한다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?',
    summary: '카푸친 원숭이는 사육 상태에서 돌과 간식을 바꾸는 거래를 해요. 나란히 있는 두 원숭이에게 똑같이 오이를 주면 둘 다 잘 먹지만, 한 원숭이에게만 더 좋아하는 포도를 주면 여전히 오이를 받는 원숭이는 오이를 실험자에게 던져 버려요. 자기가 받는 보상은 그대로인데도 다른 원숭이와의 비교가 상황을 불공평하게 만들기 때문이에요.',
    mainIdea: 'Capuchin monkeys reject their rewards when they notice that another monkey is treated better.',
    titleEn: 'Unfair Rewards: Why a Monkey Throws Back Its Cucumber',
    ko: [
      '카푸친 원숭이 — 큰 사회적 무리를 지어 사는 신세계원숭이 — 는 사육 상태에서 사람들과 하루 종일 거래를 할 것인데, 특히 음식이 관련되어 있다면 그렇다.',
      '내가 너에게 이 돌을 주면 너는 나에게 먹을 간식을 준다.',
      '만약 여러분이 우리 안에 있는 원숭이 두 마리를 서로 나란히 두고, 그들이 이미 가지고 있는 돌에 대한 대가로 둘 다에게 오이 조각을 준다면, 그들은 기꺼이 오이를 먹을 것이다.',
      '그러나 만약 여러분이 한 원숭이에게 대신 포도를 준다면 — 포도는 보편적으로 오이보다 선호된다 — 여전히 오이를 받고 있는 원숭이는 그것을 실험자에게 다시 던지기 시작할 것이다.',
      '비록 그녀가 돌을 구해 오는 노력에 대해 여전히 같은 양을 ‘지불받고’ 있고, 그래서 그녀의 특정한 상황은 바뀌지 않았지만, 다른 원숭이와의 비교가 그 상황을 불공평하게 만든다.',
      '게다가, 그녀는 이제 실험자에게 자신의 불쾌감을 전달하기 위해 모든 이득 — 오이 그 자체 — 을 기꺼이 포기한다.',
    ],
    choices: [
      ['benefit …… protect', '혜택 … 보호하다. 보상을 **지키지 않고 버린다**.'],
      ['inequality …… share', '불평등 … 나누다. 보상을 **나누지 않고 던진다**.'],
      ['abundance …… yield', '풍부함 … 내주다. 보상이 **풍부해서**가 아니다.'],
      ['inequality …… reject', '보상의 **불평등**을 깨닫고 보상을 **거부**한다 — **정답**.'],
      ['benefit …… display', '혜택 … 보여 주다. 이득을 **과시**하는 것이 아니다.'],
    ],
    vocab: [
      'captivity|명|사육 상태, 감금|confinement|freedom 자유|captive 사로잡힌',
      'trade|동|거래하다|exchange|—|trader 상인',
      'involve|동|관련시키다, 포함하다|include|exclude 제외하다|involvement 관여',
      'be involved in|숙|~에 참여하다, 관여하다|take part in|—|—',
      'treat|명|간식, 대접 (동) 대우하다, 치료하다|snack|—|treatment 대우',
      'cage|명|우리|pen|—|—',
      'cucumber|명|오이|—|—|—',
      'universally|부|보편적으로, 일반적으로|generally|—|universal 보편적인',
      'prefer|동|더 좋아하다, 선호하다|favor|—|preference 선호',
      'source|동|구하다, 얻다|obtain|—|source 원천',
      'particular|형|특정한|specific|general 일반적인|particularly 특히',
      'comparison|명|비교|contrast|—|compare 비교하다',
      'unfair|형|불공평한, 부당한|unjust|fair 공평한|unfairness 불공평',
      'be willing to|숙|기꺼이 ~하다|be ready to|be unwilling to 꺼리다|willingness 의향',
      'abandon|동|포기하다, 버리다|give up|keep 지키다|abandonment 포기',
      'displeasure|명|불쾌함|dissatisfaction|pleasure 기쁨|displease 불쾌하게 하다',
      'passage|명|글, 지문|text|—|—',
      'reward|명|보상|prize|punishment 벌|rewarding 보람 있는',
      'compared to|숙|~와 비교하여|in comparison with|—|—',
      'reject|동|거절하다|refuse|accept 받아들이다|rejection 거절',
      'treatment|명|대우, 치료|handling|—|treat 대우하다',
      'exactly|부|정확하게|precisely|roughly 대략|exact 정확한',
      'benefit|명|혜택, 이익|advantage|harm 해|beneficial 이로운',
      'inequality|명|불평등|unfairness|equality 평등|unequal 불평등한',
      'abundance|명|풍부함|plenty|scarcity 부족|abundant 풍부한',
      'protect|동|보호하다|guard|—|protection 보호',
      'yield|동|(수익을) 내다, 생산하다 / 항복하다|produce|—|—',
      'display|동|보여 주다, 전시하다|show|hide 숨기다|—',
      'despite|전|~임에도 불구하고|in spite of|—|—',
      'in spite of|숙|~에도 불구하고|despite|—|—',
    ],
    flow: [
      ['🐒', '배경 — 거래하는 원숭이', '카푸친 원숭이는 사육 상태에서 사람과 **하루 종일 거래**한다. 돌을 주면 **간식**을 받는다.'],
      ['🥒', '실험 1 — 둘 다 오이', '두 원숭이에게 돌의 대가로 **똑같이 오이**를 주면 둘 다 **기꺼이** 먹는다.'],
      ['🍇', '실험 2 — 한쪽만 포도', '한 원숭이에게만 **포도**를 주면 오이를 받는 원숭이가 오이를 **던져 버린다** — 보상은 같지만 **비교가 불공평**을 만든다.'],
      ['✅', '요약 — ④ inequality … reject', '보상의 **불평등(inequality)**을 깨달으면 불쾌감을 전하려고 보상을 **거부(reject)**한다. 정답 ④.'],
    ],
    cards: [
      {
        covers: [1],
        en: '[h:Capuchins] — New World Monkeys [r:that] live in large social groups — | [g:will], in captivity, [g:trade] with people all day long, | especially [r:if] food [g:is involved].',
        note: '**해석 도움** — 대시 사이는 {Capuchins} 를 설명하는 **동격 삽입**이다. 주어 {Capuchins} → 동사 {will trade}. 사육 상태에서 사람과 **하루 종일 거래**한다.',
        points: [
          ['grammar', '**[수업 필기] 동격 삽입 — S와 V 찾기** — [{— New World Monkeys that live ~ —}] 와 ({in captivity,}) 를 걷어내면 S {Capuchins} → V {will trade}.'],
          ['grammar', '**주격 관계대명사 that** — {Monkeys that live in large social groups}.'],
          ['vocab', '**[수업 단어표] involve / be involved in** — {involve} 연관 짓다·관련시키다, {be involved in} ~에 **참여하다·관여하다**. {if food is involved} "음식이 **관련되면**". / {captivity} 갇힘·감금·억류.'],
        ],
      },
      {
        covers: [2, 3],
        en: 'I give you this rock and you give me a treat to eat. | If you put two monkeys in cages next to each other, | and [g:offer] [h:them both] [h:slices of cucumber] [r:for] the rocks they already have, | they will happily eat the cucumbers.',
        note: '**해석 도움** — 2번(이탤릭 인쇄)은 원숭이의 **거래 규칙**을 원숭이 입장에서 쓴 말이다. 두 원숭이에게 돌의 **대가로** 똑같이 오이를 주면 **기꺼이** 먹는다.',
        points: [
          ['grammar', '**4형식 give / offer + 간접목적어 + 직접목적어** — {give you this rock}, {offer them both slices of cucumber}(필기 화살표 {offer → them}).'],
          ['grammar', '**[수업 필기] for = 교환 "~에 대한 대가로"** — 동그라미 친 {for the rocks}. / {the rocks (that) they already have} 목적격 관계대명사 생략.'],
          ['vocab', '**a treat to eat** — "먹을 **간식**"(형용사적 to부정사). {treat} 는 간식·대접 / 동사 대우하다·치료하다(수업 단어표).'],
        ],
      },
      {
        covers: [4],
        en: 'If, [r:however], you give one monkey grapes instead | — [h:grapes being universally preferred to cucumbers] — | [h:the monkey] [r:that] is still receiving cucumbers [g:will begin to throw] [r:them] back at the experimenter.',
        note: '**해석 도움** — 한 원숭이에게만 **포도**를 주면(포도는 누구나 오이보다 좋아한다), **여전히 오이를 받는** 원숭이는 오이를 실험자에게 **다시 던지기** 시작한다.',
        points: [
          ['grammar', '**[수업 필기] however, (중요) 삽입** — {If, however, you give ~}. 박스·별표. 실험 조건이 **바뀌는** 신호.'],
          ['grammar', '**[수업 필기] 독립분사구문 grapes being ~** — 박스 친 {being universally preferred to}. 주절 주어(the monkey)와 달라 주어 {grapes} 를 남겼다 = {as grapes are universally preferred to cucumbers}. {prefer A to B} → {A be preferred to B}.'],
          ['grammar', '**[수업 필기] 주어 [관계사절] → 동사** — S {the monkey} [{that is still receiving cucumbers}] → V {will begin}. {them} = **cucumbers**(동그라미).'],
        ],
      },
      {
        covers: [5],
        tags: ['title'],
        en: '[r:Even though] she is still getting “paid” the same amount for her effort of [h:sourcing] rocks, | and so her particular situation has not changed; | [h:the comparison to another] [g:makes] the situation [g:unfair].',
        note: '**해석 도움** — 받는 보상은 **그대로**인데도 **다른 원숭이와의 비교**가 상황을 **불공평하게** 만든다 — 글의 **핵심**이자 요약문 (A) **inequality** 의 근거.',
        points: [
          ['grammar', '**[수업 필기] Even though = 양보** — 물결 표시. "비록 ~일지라도". {she} = 오이를 받는 원숭이.'],
          ['grammar', '**[수업 필기] 전치사 of + 동명사 sourcing** — 동그라미 {-ing}. {source} 가 동사 "**구하다, 얻다**"(모의다·원천이 되다 — 수업 단어표).'],
          ['grammar', '**[수업 필기] make + 목적어 + 형용사 보어(5형식)** — {makes the situation unfair}(밑줄·동그라미). {the comparison to another} 박스 = 주어.'],
          ['vocab', '**“paid” 따옴표** — 원숭이가 받는 오이를 **급여**에 빗댄 표현. {particular} 특정한.'],
        ],
      },
      {
        covers: [6],
        en: '[r:Furthermore], she [g:is now willing to abandon] all gains | — the cucumbers themselves — | [r:to communicate] her displeasure to the experimenter.',
        note: '**해석 도움** — 게다가 그녀는 **불쾌감**을 전하려고 **모든 이득(오이)을 기꺼이 포기**한다 → 요약문 (B) **reject**.',
        points: [
          ['grammar', '**[수업 필기] be willing to = 기꺼이 ~하다** — 밑줄 {is now willing to abandon}. / {to communicate ~} 목적의 to부정사.'],
          ['vocab', '**[수업 필기] dis-pleasure** — 동그라미 {dis-}(반대): {pleasure} 기쁨 → {displeasure} **불쾌함**. {abandon} 포기하다·버리다.'],
          ['reading', '**[요약문 해설] 정답 ④ inequality … reject** — {if the Capuchin monkey realizes the inequality in rewards compared to another monkey, she will reject their rewards to express her feelings about the treatment, despite getting exactly the same rewards as before.}'],
          ['grammar', '**[수업 필기] despite + 동명사 (중요)** — {despite}(**전치사**) 뒤에는 동명사 {getting}(동그라미) = {in spite of}. {compared to} "~와 **비교하여**"(분사구문), {she will} 의 {she} = 원숭이.'],
          ['vocab', '**[수업 단어표] 요약문·선택지 어휘** — {benefit} 혜택 / {inequality} 불평등 / {abundance} 풍부함 / {protect} 보호하다 / {share} 나누다 / {yield} (수익을) 내다·생산하다, 항복하다 / {reject} 거절하다 / {display} 보여 주다·전시하다 / {treatment} 대우·치료 / {exactly} 정확하게 / {despite} = {in spite of} ~임에도 불구하고.'],
        ],
      },
    ],
    prompt: `Photorealistic wildlife photograph, wide banner composition. Two small capuchin monkeys sitting in neighbouring clean enclosures at a bright animal research center, separated by a clear panel: one monkey happily eating from a small bunch of purple grapes, the other staring at a slice of green cucumber lying untouched on the floor in front of it, a few smooth grey pebbles nearby. Curious, gently humorous mood. ${LIGHT}, soft green, warm beige and pale grey. ${NO}, cages with bars, zoo visitors, stage, office --ar 16:5 --v 8.1`,
  },

  /* ── 07 무관한 문장 찾기 ─────────────────────────── */
  {
    no: 7, exam: EXAM, type: '무관한 문장', answer: 4,
    question: '다음 글에서 전체 흐름과 관계 없는 문장은?',
    summary: '시험 전 벼락치기가 최고의 공부법이라고 착각하는 이유는 기억의 여러 영역을 구별하지 못하기 때문이에요. 교과서를 읽은 직후에는 정보가 작업 기억에 있어 안다고 느끼지만, 이 단기 영역은 며칠 뒤 정보를 떠올리는 데 필요한 장기 기억과는 관련이 없어요. 다시 시험해 보지 않으면 기억은 사라지므로, 공부한 뒤 스스로를 시험해야 해요.',
    mainIdea: 'Cramming creates an illusion of learning; to store information in long-term memory, we must study and then test ourselves.',
    titleEn: 'Why Cramming Fools Us: Study, Then Test Yourself',
    ko: [
      '우리는 왜 시험을 위해 벼락치기를 하는 것이 최고의 학습 전략이라는 착각을 하는가?',
      '우리가 우리 기억의 다양한 영역들을 구별할 수 없기 때문이다.',
      '교과서나 수업 필기를 읽은 직후에는, 정보가 우리 머릿속에 완전히 존재한다.',
      '그것은 활성화된 형태로 우리의 의식적인 작업 기억 속에 자리 잡고 있다.',
      '우리는 그것이 우리의 단기 저장 공간에 존재하기 때문에 마치 그것을 아는 것처럼 느끼지만… 이 단기 영역은 며칠 후에 같은 정보를 기억해 내기 위해 우리가 필요로 할 장기 기억과는 아무런 관련이 없다.',
      '몇 초나 몇 분이 지나면 작업 기억은 이미 사라지기 시작하고, 며칠이 지나면 그 영향은 엄청나다. 여러분이 자신의 지식을 다시 시험하지 않으면, 기억은 사라진다.',
      '같은 자료를 반복해서 복습하기보다는 새로운 주제를 탐구하는 데 집중하는 것이 여러분의 학업 성적을 향상시킬 수 있다.',
      '정보를 장기 기억에 넣기 위해서는, 모든 시간을 공부하는 데 쓰기보다는 자료를 공부하고 나서 스스로를 시험하는 것이 필수적이다.',
    ],
    choices: [
      ['① It sits in our conscious working memory in an active form.', '정보가 **작업 기억**에 있다 — 흐름 유지.'],
      ['② We feel as if we know it, …', '안다고 **착각**하는 이유 — 흐름 유지.'],
      ['③ After a few seconds or minutes …', '다시 시험하지 않으면 **사라진다** — 흐름 유지.'],
      ['④ Focusing on exploring new topics rather than reviewing …', '복습보다 **새 주제 탐구**가 낫다 — 다시 시험해야 한다는 흐름과 **반대**. **정답**.'],
      ['⑤ To get information into long-term memory, …', '공부 → **스스로 시험** — 결론.'],
    ],
    vocab: [
      'illusion|명|환상, 착각|delusion|reality 현실|illusory 착각의',
      'cram|동|벼락공부를 하다|—|—|—',
      'differentiate|동|구별하다|distinguish|—|difference 차이',
      'section|명|구획, 부분|part|whole 전체|—',
      'immediately|부|즉시, 곧|at once|—|immediate 즉각적인',
      'present|형|존재하는 / 현재의|existing|absent 부재한|presence 존재',
      'conscious|형|의식적인|aware|unconscious 무의식의|consciousness 의식',
      'working memory|명|작업 기억|—|—|—',
      'short-term|형|단기의|temporary|long-term 장기의|—',
      'storage|명|저장|keeping|—|store 저장하다',
      'have nothing to do with|숙|~와 아무 관련이 없다|be unrelated to|have something to do with 관련이 있다|—',
      'recall|동|기억해 내다|remember|forget 잊다|—',
      'enormous|형|엄청난|huge|tiny 아주 작은|enormously 엄청나게',
      'retest|동|다시 테스트하다|test again|—|test 시험',
      'vanish|동|사라지다|disappear|appear 나타나다|—',
      'explore|동|탐구하다|investigate|—|exploration 탐구',
      'academic|형|학업의|scholastic|—|academy 학교',
      'material|명|자료|resource|—|—',
      'essential|형|필수적인|necessary|unnecessary 불필요한|essence 본질',
      'rather than|숙|~하기보다는|instead of|—|—',
      'spend 시간 -ing|숙|~하는 데 시간을 쓰다|—|—|—',
      'in order to|숙|~하기 위해서|so as to|—|—',
      'unless|접|~하지 않으면 (= if not)|if not|—|—',
    ],
    flow: [
      ['📚', '질문 — 벼락치기의 착각', '벼락치기가 최고의 학습 전략이라는 **착각**은 기억의 영역을 **구별하지 못해서** 생긴다.'],
      ['🧠', '원인 — 단기 기억의 함정', '읽은 직후 정보는 **작업 기억**에 있어 안다고 느끼지만, 이 영역은 **장기 기억과 무관**하다.'],
      ['⏳', '사실 — 다시 시험하지 않으면 사라진다', '몇 초·몇 분이면 작업 기억이 사라지기 시작한다. **retest** 하지 않으면 기억은 **사라진다**.'],
      ['✅', '결론 + 무관 문장 ④', '장기 기억에 넣으려면 **공부 → 스스로 시험**. ④ "복습보다 새 주제 탐구"는 흐름과 **반대** → 정답 ④.'],
    ],
    cards: [
      {
        covers: [1, 2],
        en: '[r:Why] do we have the illusion [g:that] cramming for an exam is the best learning strategy? | [r:Because] we are unable to differentiate between the various sections of our memory.',
        note: '**해석 도움** — **질문(Why) – 답(Because)** 으로 주제를 연다. 벼락치기가 최고라는 **착각**은 기억의 여러 영역을 **구별하지 못해서** 생긴다. {cram} 은 각주 "**벼락공부를 하다**".',
        points: [
          ['reading', '**[수업 필기] Why → Because** — 동그라미 친 두 단어가 질문과 답을 잇는다. 첫 두 문장이 **글의 주제**.'],
          ['grammar', '**[수업 필기] 동격 that** — {the illusion that ~}(화살표·괄호): "~라는 **착각**". that 절 = illusion 의 내용. 동명사 주어 {cramming for an exam} → {is}.'],
          ['grammar', '**[수업 필기] un-able / differentiate between** — {be unable to}(동그라미 {un-}) ~할 수 없다. {differentiate between A and B} "~을 **구별하다**"(물결). {various sections} 다양한 영역(필기 "선택·과정"은 {section} 구획·부분으로 정리).'],
        ],
      },
      {
        covers: [3, 4],
        en: '[r:Immediately after] [g:reading] our textbook or our class notes, | information is fully [h:present] in our mind. | [h:It] [g:sits] in our conscious working memory in an active form.',
        note: '**해석 도움** — 읽은 **직후**에는 정보가 머릿속에 **완전히 존재**한다. 그것은 의식적인 **작업 기억** 속에 활성화된 형태로 **자리 잡고** 있다(① 문장).',
        points: [
          ['grammar', '**전치사 after + 동명사** — {Immediately after reading ~}(즉시·곧, 수업 단어표). 쉼표 뒤가 주절(필기 /).'],
          ['vocab', '**[수업 필기] present = 존재하는 (형용사)** — 물결 표시. {be present in} "~에 **존재하다**". 명사 "현재", 동사 "제시하다"와 구별.'],
          ['reading', '**[수업 필기] It = information** — 화살표. {sits}(밑줄) "자리 잡고 있다". ① 은 흐름 유지.'],
        ],
      },
      {
        covers: [5],
        en: 'We feel [r:as if] we know it, because it is present in our short-term storage space ... | [r:but] this [h:short-term section] [g:has nothing to do with] the [h:long-term memory] | [r:that] we will need [r:in order to] recall the same information a few days later.',
        note: '**해석 도움** — 단기 저장 공간에 있으니 **아는 것처럼** 느끼지만, 이 **단기 영역**은 며칠 뒤 기억해 내는 데 필요한 **장기 기억**과 **아무 관련이 없다**(② 문장).',
        points: [
          ['grammar', '**[수업 필기] as if + S + V** — 동그라미. "**마치 ~인 것처럼**". 실제로는 모르는데 안다고 느낀다.'],
          ['reading', '**[수업 필기] but(세모) — 단기 vs 장기** — 동그라미 친 {short-term section} 과 {long-term memory} 의 **대비**가 글의 핵심.'],
          ['grammar', '**[수업 필기] have nothing to do with** — "~와 **아무런 관련이 없다**"(수업 단어표). / 목적격 관계대명사 {that}(화살표) + {in order to}(밑줄) "~**하기 위해서**".'],
        ],
      },
      {
        covers: [6],
        en: 'After a few seconds or minutes working memory already [g:starts disappearing], | [r:and] after a few days, the effect becomes enormous: | [r:unless] you [h:retest] your knowledge, memory vanishes.',
        note: '**해석 도움** — 몇 초·몇 분이면 작업 기억이 **사라지기 시작**하고, 며칠 뒤엔 영향이 **엄청나다**. 지식을 **다시 시험하지 않으면** 기억은 **사라진다**(③ 문장).',
        points: [
          ['grammar', '**start + -ing** — {starts disappearing} = {starts to disappear}. / {and}(동그라미)로 두 절 연결.'],
          ['grammar', '**[수업 단어표] unless = if not** — "~**하지 않으면**". {unless you retest} = {if you don’t retest}.'],
          ['vocab', '**[수업 필기] retest = reviewing** — 동그라미 친 {retest}(다시 테스트하다)를 ④의 {reviewing} 과 **같은 뜻**으로 연결해 두었다 → ④가 왜 어긋나는지의 열쇠.'],
        ],
      },
      {
        covers: [7],
        tags: ['insert'],
        en: '[h:Focusing] on [g:exploring] new topics [r:rather than] [g:reviewing] the same material over and over again | can improve your academic performance.',
        note: '**해석 도움** — "같은 자료를 반복 **복습하기보다는** **새 주제를 탐구**하는 데 집중하면 성적이 오른다." (중요) **무관한 문장 ④** — 글은 **다시 시험·복습해야** 기억이 남는다는 흐름인데, 이 문장은 **복습을 깎아내린다**.',
        points: [
          ['reading', '**[수업 필기] ④ 가 정답인 이유** — 필기 {retest = reviewing}: 앞(③)과 뒤(⑤)는 "**다시 시험하라**", ④ 만 "**복습하지 말고 새 주제로**" → 흐름과 **정반대**.'],
          ['grammar', '**동명사 주어 Focusing → can improve** — 주어가 길어도 핵심은 {Focusing}.'],
          ['grammar', '**[수업 필기] rather than 병렬** — 박스 친 {rather than} 앞뒤 형태 일치: {exploring} / {reviewing}(동그라미 {-ing}). 전치사 {on} 뒤라 둘 다 동명사.'],
          ['vocab', '**explore / academic / over and over again** — 탐구하다 / 학업의 / 반복해서.'],
        ],
      },
      {
        covers: [8],
        tags: ['title'],
        en: '[r:To get] information into long-term memory, | [g:it] is essential [g:to study] the material, then test yourself, | [r:rather than] spend all your time [h:studying].',
        note: '**해석 도움** — 장기 기억에 넣으려면 모든 시간을 공부에 쓰기**보다는**, 자료를 **공부하고 나서 스스로를 시험하는 것**이 필수적이다 — **결론**(⑤ 문장).',
        points: [
          ['grammar', '**[수업 필기] 가주어 it – 진주어 to부정사** — 동그라미 {it} = {to study the material, then (to) test yourself}. {essential} 필수적인.'],
          ['grammar', '**[수업 필기] rather than + 동사원형** — 박스. 앞의 {(to) study / test} 와 병렬이라 원형 {spend}. / {test yourself} 재귀대명사(동그라미).'],
          ['grammar', '**[수업 단어표] spend + 시간 + -ing** — "~**하는 데 시간을 쓰다**": {spend all your time studying}(동그라미 {-ing}). / {To get ~} 목적, {then}(물결) 그러고 나서.'],
        ],
      },
    ],
    prompt: `Photorealistic interior photograph, wide banner composition. A bright study desk late in the morning: an open textbook with plain pages, a tall messy stack of blank index cards beside a neat small pile of flipped cards, several highlighter pens and a half-finished cup of tea, a window with soft daylight behind. Focused, calm study mood that hints at reviewing and self-testing. ${LIGHT}, white, soft yellow and light blue. ${NO}, writing on pages, hourglass, clock, laptop, monkeys, stage --ar 16:5 --v 8.1`,
  },

  /* ── 08 문장의 위치 파악 ─────────────────────────── */
  {
    no: 8, exam: EXAM, type: '문장 삽입', answer: 3,
    question: '글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은?',
    summary: '생물학자들은 두 종류의 유사성을 구별해요. 새의 날개와 벌의 날개처럼 기능은 같지만 진화 과정에서 따로 생겨난 것은 ‘상사’ 형질이고, 박쥐의 날개와 말의 앞다리처럼 기능은 달라도 공통 조상에서 내려와 구조가 같은 것은 ‘상동’ 형질이에요. 둘을 구별하려면 기관의 전체 구조, 특히 가장 쓸모없는 특성을 살펴봐요.',
    mainIdea: 'Biologists tell analogy from homology by looking at the overall structure and the most useless properties of organs.',
    titleEn: 'Analogy vs. Homology: Same Function or Same Ancestor?',
    ko: [
      '생물학자들은 두 종류의 유사성을 구별한다.',
      '‘상사(相似)’ 형질은 공통된 기능을 가지고 있지만 진화 계통수의 서로 다른 가지에서 생겨났으며, 중요한 의미에서 ‘같은’ 기관이 아닌 것들이다.',
      '새의 날개와 벌의 날개는 둘 다 비행에 사용되고, 비행에 사용되는 것은 무엇이든 그런 방식으로 만들어져야 하기 때문에 어떤 면에서 비슷하지만, 그것들은 진화 과정에서 독립적으로 생겨났고 비행에 사용된다는 점 외에는 공통점이 전혀 없다.',
      '반대로 상동(相同) 형질은 공통된 기능을 가질 수도 있고 가지지 않을 수도 있지만, 공통 조상으로부터 내려왔고, 따라서 그것들이 ‘같은’ 기관임을 보여 주는 어떤 공통된 구조를 가지고 있다.',
      '박쥐의 날개와 말의 앞다리는 매우 다른 기능을 가지고 있지만, 그것들은 모두 모든 포유동물의 조상이 가진 앞다리가 변형된 것이다.',
      '그 결과, 그것들은 뼈의 수와 뼈가 연결된 방식 같은 기능과 무관한 특징을 공유한다.',
      '상사와 상동을 구별하기 위해, 생물학자들은 보통 기관의 전반적인 구조를 살펴보고 가장 쓸모없는 특성에 집중한다.',
    ],
    choices: [
      ['①', '두 종류의 유사성 소개 직후 — 아직 analogous 도 나오기 전이라 {in contrast} 가 대조할 대상이 없다.'],
      ['②', 'analogous 정의와 그 **예시(새·벌의 날개)** 사이를 끊는다.'],
      ['③', 'analogous 예시가 끝난 뒤, homologous **예시(박쥐·말)** 바로 앞 — **정답**.'],
      ['④', '박쥐·말 예시 **안**이라 늦다. 앞에서 이미 homologous 예시가 시작됐다.'],
      ['⑤', '구별 방법(결론) 앞 — 예시가 정의보다 먼저 나오게 된다.'],
    ],
    vocab: [
      'homologous|형|상동의, 동종의|—|analogous 상사의|homology 상동',
      'trait|명|형질, 특성|feature|—|—',
      'descend|동|내려오다, 유래하다|come down|ascend 올라가다|descendant 자손',
      'hence|부|따라서, 그래서|therefore|—|—',
      'indicate|동|보여 주다, 나타내다|show|—|indication 표시',
      'distinguish|동|구별하다|differentiate, tell|confuse 혼동하다|distinction 구별',
      'distinguish A from B|숙|A와 B를 구별하다|tell A from B|—|—',
      'similarity|명|유사성|resemblance|difference 차이|similar 비슷한',
      'analogous|형|유사한, 상사의|similar|—|analogy 유사',
      'arise|동|생겨나다, 발생하다|emerge|—|—',
      'evolutionary|형|진화의|—|—|evolution 진화',
      'independently|부|독립적으로, 별개로|separately|dependently 의존적으로|independent 독립적인',
      'beyond|전|~ 외에는, ~을 넘어서는|besides|—|—',
      'modify|동|수정하다, 변경하다|alter|—|modification 변형',
      'modification|명|변형, 수정|alteration|—|modify 수정하다',
      'forelimb|명|앞다리|—|hind limb 뒷다리|—',
      'analogy|명|유사함, 상사|similarity|—|analogous 유사한',
      'homology|명|상동성, 동종성|—|—|homologous 상동의',
      'overall|형|전체적인, 전반적인|general|partial 부분적인|—',
      'architecture|명|구조, 건축|structure|—|architect 건축가',
      'property|명|특성, 속성|characteristic|—|—',
      'ancestor|명|조상|forefather|descendant 자손|ancestral 조상의',
      'mammal|명|포유동물|—|—|—',
      'nonfunctional|형|기능과 무관한, 쓸모없는|useless|functional 기능적인|function 기능',
    ],
    flow: [
      ['🔬', '도입 — 두 종류의 유사성', '생물학자는 유사성을 **두 종류**로 구별한다.'],
      ['🐦', '상사(analogous) — 기능만 같다', '새의 날개·벌의 날개: **기능은 같지만** 진화의 **다른 가지**에서 독립적으로 생겨났다.'],
      ['🦇', '상동(homologous) — 조상이 같다', '{in contrast} — 박쥐의 날개·말의 앞다리: **기능은 달라도 공통 조상**에서 내려와 **구조**가 같다. 주어진 문장 → ③.'],
      ['🦴', '구별법 — 쓸모없는 특성을 본다', '뼈의 수·연결 방식 같은 **기능과 무관한 특징**, 즉 **가장 쓸모없는 특성**에 집중해 구별한다.'],
    ],
    cards: [
      {
        covers: [1],
        en: 'Biologists [g:distinguish] [h:two kinds of similarity].',
        note: '**해석 도움** — "생물학자들은 **두 종류의 유사성**을 구별한다." 뒤에 **analogous**(상사)와 **homologous**(상동) 두 개념이 차례로 나온다는 **예고**.',
        points: [
          ['reading', '**[수업 필기] two kinds ○** — 동그라미. "두 종류"라고 했으니 두 개념이 **모두** 나와야 한다 → 주어진 문장(homologous)이 들어갈 자리를 찾는 단서.'],
          ['vocab', '**distinguish / similarity** — 구별하다 / 유사성(물결 표시). {distinguish A from B} 는 7번에서 다시 나온다.'],
        ],
      },
      {
        covers: [2],
        en: '“Analogous” traits [g:are] [h:ones] [r:that] [g:have] a common function | but [g:arose] on different branches of the evolutionary tree | and [g:are] in an important sense not “the same” organ.',
        note: '**해석 도움** — ‘**상사**’ 형질 = **공통된 기능**은 있지만 진화 계통수의 **다른 가지**에서 생겨나, 중요한 의미에서 ‘같은’ **기관**이 아닌 것.',
        points: [
          ['grammar', '**[수업 필기] ones = traits / 관계사절 동사 V1·V2·V3** — [{that have}(V1) ~ {but arose}(V2) ~ {and are}(V3) ~]. 세 동사의 주어는 모두 {that}(= ones).'],
          ['vocab', '**[수업 필기] common = 공통의, 비슷한 / function = 기능 / organ = 기관** — 여백 필기. {arise – arose – arisen} 생겨나다.'],
          ['reading', '**[수업 필기 정리] Analogous** — **common** function + **different** branches → 예: **새의 날개, 벌의 날개**.'],
        ],
      },
      {
        covers: [3],
        en: '[h:The wings of birds and the wings of bees] [g:are both used for] flight and are similar in some ways | [r:because] [h:anything] [r:used for flight] [g:has to be built] in those ways, | but they arose independently in evolution | and [g:have nothing in common] beyond their use in flight.',
        note: '**해석 도움** — 새의 날개와 벌의 날개는 비행에 쓰여 비슷하지만, 진화에서 **독립적으로** 생겨났고 비행 외에는 **공통점이 전혀 없다** — **analogous 의 예시**. 이 예시가 끝난 자리가 ③.',
        points: [
          ['grammar', '**[수업 필기] 주어 A and B → are** — [{The wings of birds and the wings of bees}] V {are (both) used}. 복수 주어.'],
          ['grammar', '**[수업 필기] 과거분사 후치수식 + 조동사 수동태** — S {anything} ← ({used for flight}) → V {has to be built}(밑줄). "비행에 쓰이는 것은 무엇이든 그렇게 **만들어져야 한다**".'],
          ['vocab', '**[수업 필기] have nothing in common / beyond** — "공통점이 **전혀 없다**"(밑줄) / {beyond} "~ **외에는**, ~을 넘어서는"(동그라미). {those ways} = 비행에 맞는 방식.'],
        ],
      },
      {
        covers: [4],
        tags: ['insert'],
        en: '[h:Homologous traits], [r:in contrast], may or may not have a common function, | [r:but] they [g:descended from] a common ancestor | and [r:hence] have some common structure [r:that] indicates [h:their being] “the same” organ.',
        note: '**해석 도움** — (중요) **주어진 문장 → ③**. **반대로** ‘상동’ 형질은 기능이 같을 수도 다를 수도 있지만, **공통 조상**에서 내려와 ‘같은’ 기관임을 보여 주는 **공통 구조**를 가진다.',
        points: [
          ['reading', '**[수업 필기] in contrast(반대로) (중요) — 정답 ③ 근거** — 앞(analogous 예시: 새·벌)과 **대조**하고, 바로 뒤 **박쥐 날개·말 앞다리**(기능은 다르고 조상은 같음)가 이 문장의 **예시**가 된다.'],
          ['vocab', '**[수업 필기] descend from / common ancestor / hence** — ~에서 **내려오다**(물결) / **공통 조상**(박스) / **따라서**. {common structure}(박스) **구조**.'],
          ['grammar', '**[수업 필기] 동명사의 의미상 주어 their** — {their being “the same” organ}: {being}(동명사)의 의미상 주어 = 소유격 {their}(= homologous traits). "그것들이 같은 기관이라는 것".'],
          ['reading', '**[수업 필기 정리] Homologous** — **different** function + **common** ancestor(same, 공통 조상) → 예: **박쥐의 날개, 말의 앞다리**.'],
        ],
      },
      {
        covers: [5, 6],
        en: '[h:The wing of a bat and the front leg of a horse] [g:have] very different functions, | but they are all [h:modifications] of the forelimb of the ancestor of all mammals. | [r:As a result], they share nonfunctional traits like [g:the number of] bones and the ways [r:they are connected].',
        note: '**해석 도움** — 박쥐의 날개와 말의 앞다리는 기능이 **매우 다르지만**, 모두 포유동물 조상의 **앞다리가 변형된 것**이다. 그래서 뼈의 수·연결 방식 같은 **기능과 무관한 특징**을 공유한다.',
        points: [
          ['grammar', '**[수업 필기] 주어 A and B → have** — [{The wing of a bat and the front leg of a horse}] V {have}.'],
          ['vocab', '**[수업 필기] ancestor / mammals(포유동물) / non-functional** — 물결 {ancestor}, 여백 "포유동물", 동그라미 {non-}(부정) → 기능과 **무관한**.'],
          ['grammar', '**[수업 필기] a number of vs the number of** — {a number of + 복수명사} "**많은**"(복수 취급) / {the number of + 복수명사} "~의 **수**"(단수 취급). 여기는 "뼈의 **수**".'],
          ['vocab', '**As a result / modification** — 그 결과(물결) / 변형({modify} 수정·변경하다).'],
        ],
      },
      {
        covers: [7],
        en: '[r:To distinguish] analogy [r:from] homology, | biologists usually [g:look at] the overall architecture of the organs | and [g:focus on] their most [h:useless] properties.',
        note: '**해석 도움** — 상사와 상동을 **구별하기 위해**, 생물학자들은 기관의 **전반적인 구조**를 살피고 **가장 쓸모없는 특성**에 집중한다.',
        points: [
          ['grammar', '**[수업 필기] distinguish A from B = tell A from B** — 동그라미 {distinguish}·{from}, 필기 "= tell". / {To distinguish} 목적의 to부정사.'],
          ['grammar', '**[수업 필기] 동사 병렬 V1 and V2** — {look at}(V1) / {focus on}(V2). 주어 {biologists}.'],
          ['vocab', '**[수업 필기] useless = nonfunctional : 쓸모없는** — 6번의 {nonfunctional traits} 를 다시 말한 것. {architecture} 는 여기서 "**구조**"(필기), {overall} 전체적인, {property} 특성.'],
        ],
      },
    ],
    prompt: `Photorealistic museum photograph, wide banner composition. A bright natural history museum display table: a pale bat wing skeleton and a horse foreleg skeleton laid side by side on white linen, with a preserved bird wing and a small bee specimen under glass domes nearby, soft museum lighting. Curious, scientific, clean mood. ${LIGHT}, ivory, bone white and soft grey-blue. ${NO}, labels, skulls, monkeys, stage --ar 16:5 --v 8.1`,
  },
];
