/* 봉영여중3 Lesson 07 Spend Wisely 추가지문 3편 저작 데이터 — _author-EX.mjs 가 모아서 쓴다.
 * 09 snob effect: 필기 없음(단어표 빈칸) → 일반 분석.
 * 10 Veblen effect: 지문 위 필기 + 손글씨 단어표 반영.
 * 11 Romeo and Juliet effect: 지문 위 필기 + 하단 프린트 「간접의문문」 빈칸을 채워 카드에 반영.
 * 원본 프린트에 문제가 없어 type/choices 는 분석지 형식을 위해 새로 붙였다(hide_answer 라 인쇄 안 됨). */
import { EXAM, LIGHT, NO } from './_author-EX-1.mjs';

export const chapters = [
  /* ── 09 The snob effect ──────────────────────────── */
  {
    no: 9, exam: EXAM, type: '주제', answer: 3,
    question: '다음 글의 주제로 가장 적절한 것은?',
    summary: '어떤 사람들은 제품이 인기를 얻으면 오히려 그것을 원하지 않게 되는데, 이를 스놉 효과라고 해요. 희귀하거나 독점적인 제품을 가치 있게 여기는 경향이라, 많은 사람이 같은 제품을 사면 매력이 떨어져요. 밴드왜건 효과와 반대되는 이 심리를 이용해 기업은 한정판이나 명품을 출시하고, 독특함을 중시하는 소비자는 더 높은 가격도 기꺼이 지불해요.',
    mainIdea: 'The snob effect is people’s tendency to value products because they are rare or exclusive, the opposite of the bandwagon effect.',
    titleEn: 'The Snob Effect: When Popular Means Less Wanted',
    ko: [
      '왜 어떤 사람들은 제품이 인기를 얻은 후에 그것을 원하지 않게 될까?',
      '이러한 행동은 스놉 효과라고 불린다.',
      '스놉 효과는 제품이 희귀하거나 독점적이기 때문에 그것을 가치 있게 여기는 사람들의 경향을 가리킨다.',
      '더 많은 사람들이 같은 제품을 살수록, 그것은 그 소비자들에게 덜 매력적이 된다.',
      '예를 들어, 한 회사가 한정판 운동화를 단 500켤레만 출시한다고 상상해 보라.',
      '많은 사람들은 그것을 구하기 어렵기 때문에 사고 싶어 한다.',
      '그러나 그 회사가 나중에 같은 운동화를 수백만 켤레 생산하면, 일부 구매자들은 흥미를 잃는다.',
      '그들은 다른 많은 사람들이 같은 신발을 가지고 있기 때문에 더 이상 특별하다고 느끼지 않는다.',
      '스놉 효과는 밴드왜건 효과의 반대이다.',
      '밴드왜건 효과는 사람들이 단지 다른 많은 사람들이 그것을 사고 있다는 이유로 제품을 살 때 일어난다.',
      '대조적으로, 스놉 효과는 사람들이 군중 속에서 돋보이게 해 주는 제품을 고르도록 부추긴다.',
      '기업들은 종종 마케팅 전략에 스놉 효과를 이용한다.',
      '그들은 희소성과 독점성의 느낌을 만들어 내기 위해 한정판 제품이나 명품을 출시한다.',
      '그 결과, 독특함을 중시하는 소비자들은 이러한 제품에 기꺼이 더 높은 가격을 지불할 수도 있다.',
      '연구자들은 소비자가 독점성을 추구하는지 인기를 추구하는지에 따라 희소성이 수요를 늘릴 수도, 줄일 수도 있다는 것을 발견했다.',
    ],
    choices: [
      ['인기 있는 제품이 더 잘 팔리는 이유', '오히려 인기가 많아지면 **덜 원하게** 되는 경우를 다룬다.'],
      ['한정판 운동화의 생산 과정', '운동화는 **예시**일 뿐이다.'],
      ['희소하고 독점적인 제품을 가치 있게 여기는 스놉 효과', '제품이 흔해지면 덜 원하게 되는 소비 심리 — **정답**.'],
      ['밴드왜건 효과가 생기는 원인', '밴드왜건 효과는 **대조**를 위해 언급된다.'],
      ['명품 가격이 오르는 이유', '가격과 수요의 관계는 다음 지문(베블런 효과)의 내용이다.'],
    ],
    vocab: [
      'popular|형|인기 있는|well-liked|unpopular 인기 없는|popularity 인기',
      'snob effect|명|스놉 효과(속물 효과)|—|bandwagon effect 밴드왜건 효과|snob 속물',
      'refer to|숙|~을 가리키다|mean|—|reference 언급',
      'tendency|명|경향|inclination|—|tend 경향이 있다',
      'value|동|가치 있게 여기다, 중시하다|appreciate|—|valuable 귀중한',
      'rare|형|희귀한|scarce|common 흔한|rarity 희귀성',
      'exclusive|형|독점적인, 배타적인|limited|—|exclusivity 독점성',
      'attractive|형|매력적인|appealing|unattractive 매력 없는|attract 끌다',
      'release|동|출시하다|launch|—|—',
      'limited-edition|형|한정판의|—|mass-produced 대량 생산된|—',
      'obtain|동|얻다, 구하다|get, acquire|lose 잃다|—',
      'lose interest|숙|흥미를 잃다|—|—|—',
      'no longer|숙|더 이상 ~않다|not ~ any longer|—|—',
      'opposite|명|반대|reverse|—|oppose 반대하다',
      'occur|동|일어나다|happen|—|occurrence 발생',
      'encourage|동|부추기다, 장려하다|urge|discourage 단념시키다|encouragement 격려',
      'stand out|숙|눈에 띄다, 돋보이다|be noticeable|blend in 섞이다|outstanding 뛰어난',
      'strategy|명|전략|plan|—|strategic 전략적인',
      'rarity|명|희소성|scarcity|—|rare 희귀한',
      'exclusivity|명|독점성, 배타성|—|—|exclusive 독점적인',
      'uniqueness|명|독특함|distinctiveness|—|unique 독특한',
      'scarcity|명|희소성, 부족|shortage|abundance 풍부|scarce 부족한',
      'demand|명|수요|need|supply 공급|—',
      'depending on|숙|~에 따라|according to|—|—',
    ],
    flow: [
      ['❓', '질문 — 인기 있으면 싫어진다?', '제품이 **인기를 얻은 후** 원하지 않게 되는 행동 = **스놉 효과**.'],
      ['👟', '예시 — 한정판 운동화', '500켤레 한정판은 **구하기 어려워서** 원하지만, 수백만 켤레가 생산되면 **흥미를 잃는다** — 더 이상 **특별하지 않다**.'],
      ['🔄', '대조 — 밴드왜건 효과의 반대', '밴드왜건: **남들이 사니까** 산다. 스놉: 군중 속에서 **돋보이게** 해 주는 제품을 고른다.'],
      ['💎', '활용 — 희소성 마케팅', '기업은 **한정판·명품**으로 희소성을 만든다. 희소성은 소비자가 **독점성**과 **인기** 중 무엇을 원하는지에 따라 수요를 늘리거나 줄인다.'],
    ],
    cards: [
      {
        covers: [1, 2],
        en: 'Why do some people [g:stop wanting] a product | [r:after] it [g:becomes] popular? | This behavior [g:is called] [h:the snob effect].',
        note: '**해석 도움** — 제품이 **인기를 얻은 뒤** 오히려 원하지 않게 되는 행동을 **스놉 효과**라고 부른다. 교과서 L7 본문의 **밴드왜건 효과**와 짝을 이루는 개념.',
        points: [
          ['grammar', '**stop + -ing vs stop + to부정사** — {stop wanting} "원하는 것을 **멈추다**" / {stop to want} 는 "원하기 **위해** 멈추다"(×).'],
          ['grammar', '**become + 형용사 / be called + 명사** — {becomes popular} 인기 있게 되다 / {is called the snob effect} ~라고 **불리다**({call A B} 의 수동태).'],
        ],
      },
      {
        covers: [3, 4],
        tags: ['title'],
        en: 'The snob effect [g:refers to] people’s tendency [r:to value] a product | [r:because] it is [h:rare or exclusive]. | [r:As] more people buy the same product, | it becomes [g:less attractive] to those consumers.',
        note: '**해석 도움** — 스놉 효과 = 제품이 **희귀하거나 독점적이어서** 가치 있게 여기는 경향. 같은 제품을 사는 사람이 **많아질수록** 그 소비자들에게는 **덜 매력적**이 된다 — **정의 문장**.',
        points: [
          ['grammar', '**refer to + 명사** — "~을 **가리키다**". / {tendency to value} "가치 있게 여기는 **경향**"(형용사적 to부정사).'],
          ['grammar', '**비례의 as + 비교급** — {As more people buy ~, it becomes less attractive} "더 많이 살**수록** 덜 매력적이 된다". (10번 Veblen 지문의 {as their prices rise} 와 같은 as)'],
          ['vocab', '**rare / exclusive / attractive** — 희귀한 / 독점적인·배타적인 / 매력적인. {less + 형용사} "덜 ~한".'],
        ],
      },
      {
        covers: [5, 6],
        en: 'For example, [g:imagine] [r:that] a company releases only 500 pairs of limited-edition sneakers. | Many people want to buy [h:them] because they are [g:difficult to obtain].',
        note: '**해석 도움** — 한정판 운동화 **500켤레**를 상상해 보라. **구하기 어렵기 때문에** 많은 사람이 사고 싶어 한다.',
        points: [
          ['grammar', '**명령문 imagine + that절** — "~라고 **상상해 보라**". 예시를 들 때 자주 쓴다.'],
          ['grammar', '**형용사 + to부정사(~하기에)** — {difficult to obtain} "**얻기 어려운**". {them / they} = 운동화.'],
          ['vocab', '**pairs of / limited-edition / obtain** — 켤레 / **한정판의**(하이픈 복합 형용사) / 얻다·구하다.'],
        ],
      },
      {
        covers: [7, 8],
        en: '[r:However], [r:if] the company later [g:produces] millions of the same sneakers, | some buyers [g:lose interest]. | They [g:no longer] feel special | because many other people own the same shoes.',
        note: '**해석 도움** — 같은 운동화가 **수백만 켤레** 나오면 일부 구매자는 **흥미를 잃는다**. 다른 많은 사람도 가지고 있어서 **더 이상 특별하다고 느끼지 않기** 때문이다.',
        points: [
          ['grammar', '**조건의 if절은 현재시제** — {if the company later produces ~}. 미래 일이어도 {will produce} 를 쓰지 않는다.'],
          ['grammar', '**no longer = not ~ any longer** — "**더 이상 ~않다**". / {feel + 형용사} {feel special}.'],
          ['vocab', '**millions of / lose interest** — 수백만의 / 흥미를 잃다.'],
        ],
      },
      {
        covers: [9, 10],
        en: 'The snob effect is [h:the opposite of] the bandwagon effect. | The bandwagon effect [g:occurs] [r:when] people buy a product | [r:simply because] many others [g:are buying] it.',
        note: '**해석 도움** — 스놉 효과는 밴드왜건 효과의 **반대**다. 밴드왜건 효과는 **단지 다른 많은 사람이 사고 있다는 이유로** 제품을 살 때 일어난다.',
        points: [
          ['grammar', '**occur 는 자동사** — "**일어나다**". 수동태로 쓰지 않는다({is occurred} ×).'],
          ['reading', '**교과서 L7 본문과 연결** — {simply because many others are buying it} = 본문 {just because other people have bought it}(밴드왜건 효과).'],
          ['vocab', '**the opposite of** — "~의 **반대**".'],
        ],
      },
      {
        covers: [11],
        en: '[r:In contrast], the snob effect [g:encourages] people [g:to choose] products | [r:that] [g:help] them [g:stand out] from the crowd.',
        note: '**해석 도움** — **대조적으로**, 스놉 효과는 사람들이 **군중 속에서 돋보이게** 해 주는 제품을 고르도록 **부추긴다**.',
        points: [
          ['grammar', '**encourage + 목적어 + to부정사** — {encourages people to choose} "사람들이 **고르도록 부추기다**".'],
          ['grammar', '**주격 관계대명사 that + help + 목적어 + (to) 동사원형** — {products that help them stand out}. 선행사 {products}(복수) → {help}.'],
          ['vocab', '**stand out from the crowd** — "군중 속에서 **돋보이다**". 반대는 {blend in}(섞이다).'],
        ],
      },
      {
        covers: [12, 13],
        en: 'Companies often [g:use] the snob effect in their marketing strategies. | They release limited-edition products or luxury products | [r:to create] a sense of [h:rarity and exclusivity].',
        note: '**해석 도움** — 기업은 **희소성과 독점성**의 느낌을 만들려고 **한정판·명품**을 출시한다.',
        points: [
          ['grammar', '**to부정사 부사적 용법(목적)** — {to create ~} "~을 **만들어 내기 위해**".'],
          ['vocab', '**형용사 → 명사** — {rare} → {rarity} 희소성, {exclusive} → {exclusivity} 독점성. / {a sense of} ~라는 느낌, {strategy} 전략.'],
        ],
      },
      {
        covers: [14, 15],
        en: '[r:As a result], consumers [r:who] value uniqueness [g:may be willing to pay] higher prices for these products. | Researchers [g:have found] [r:that] scarcity can increase or decrease demand | [r:depending on] [h:whether consumers are seeking exclusivity or popularity].',
        note: '**해석 도움** — 그 결과 **독특함을 중시하는** 소비자는 **더 높은 가격**도 기꺼이 낸다. 희소성은 소비자가 **독점성**을 원하는지 **인기**를 원하는지에 **따라** 수요를 늘리기도 줄이기도 한다.',
        points: [
          ['grammar', '**주격 관계대명사 who** — S {consumers} [{who value uniqueness}] → V {may be willing to pay}. {be willing to} 기꺼이 ~하다.'],
          ['grammar', '**whether + 주어 + 동사 (간접의문문)** — {whether consumers are seeking ~} "~**인지 (아닌지)**". 11번 지문 프린트의 **간접의문문 ③**(if / whether + 주어 + 동사)과 같은 구조.'],
          ['vocab', '**depending on / scarcity / demand** — ~에 따라 / 희소성 / 수요. 현재완료 {have found} + that절.'],
        ],
      },
    ],
    prompt: `Photorealistic interior photograph, wide banner composition. A bright minimalist sneaker boutique: one pair of clean white limited-edition sneakers displayed alone on a tall white pedestal under a soft spotlight, while the long shelves behind are packed with many identical plain shoe boxes. Calm contrast between the rare and the common. ${LIGHT}, white, soft grey and pale mint. ${NO}, wagon, parade, monkeys, stage --ar 16:5 --v 8.1`,
  },

  /* ── 10 The Veblen effect ────────────────────────── */
  {
    no: 10, exam: EXAM, type: '요지', answer: 2,
    question: '다음 글의 요지로 가장 적절한 것은?',
    summary: '베블런 효과는 제품이 비싸다는 이유로 사람들이 더 기꺼이 사는 소비 행동이에요. 대부분의 제품과 달리 베블런재는 가격이 오를수록 수요가 늘 수 있는데, 소비자가 자신의 부·성공·사회적 지위를 보여 주려 하기 때문이에요. 이는 경제학자 소스타인 베블런의 과시적 소비 개념에 근거하며, 명품 시계나 핸드백이 대표적인 예예요.',
    mainIdea: 'For Veblen goods, demand rises as prices rise because the products symbolize wealth, prestige, or social status.',
    titleEn: 'The Veblen Effect: The Higher the Price, the Greater the Demand',
    ko: [
      '베블런 효과는 사람들이 어떤 제품이 비싸기 때문에 그것을 더 기꺼이 사려고 하는 소비자 행동의 한 유형이다.',
      '대부분의 제품과 달리, 베블런재에 대한 수요는 가격이 오를수록 증가할 수도 있다.',
      '소비자들은 종종 자신의 부, 성공, 또는 사회적 지위를 보여 주기 위해 이러한 제품을 구매한다.',
      '명품 브랜드, 비싼 시계, 스포츠카, 그리고 디자이너 핸드백은 베블런재의 흔한 예이다.',
      '이 개념은 미국의 경제학자 소스타인 베블런이 소개한 과시적 소비라는 개념에 근거한다.',
      '이 이론에 따르면, 어떤 사람들은 비싼 물건을 그 품질 때문만이 아니라 자신의 경제적 성공을 과시하기 위해서도 구매한다.',
      '(예시) 한 고객이 더 싼 시계 대신 명품 시계를 고르는데, 그 높은 가격이 그 시계를 더 고급스러워 보이게 하기 때문이다.',
      '한 명품 브랜드가 핸드백의 가격을 올리자, 그 제품이 훨씬 더 고급스러워 보이기 때문에 수요가 증가한다.',
      '(요약) 베블런 효과는 제품이 부, 명성, 또는 사회적 지위를 상징하기 때문에 제품의 가격이 오를수록 수요가 증가하는 경향이다.',
    ],
    choices: [
      ['사람들은 품질이 좋은 제품만을 구매한다.', '품질**뿐만 아니라** 과시를 위해서도 산다.'],
      ['어떤 제품은 비쌀수록 오히려 수요가 증가한다.', '베블런 효과의 정의 — **정답**.'],
      ['가격이 오르면 모든 제품의 수요는 줄어든다.', '{Unlike most products} — 베블런재는 **예외**다.'],
      ['명품 브랜드는 가격을 낮춰야 잘 팔린다.', '가격을 **올리자** 수요가 늘었다.'],
      ['소비자는 남들이 사는 제품을 따라 산다.', '밴드왜건 효과의 설명이다.'],
    ],
    vocab: [
      'Veblen effect|명|베블런 효과|—|—|—',
      'consumer|명|소비자|buyer|producer 생산자|consume 소비하다',
      'behavior|명|행동|conduct|—|behave 행동하다',
      'demand|명|수요|—|supply 공급|—',
      'purchase|동|구매하다|buy|sell 팔다|purchaser 구매자',
      'wealth|명|부|riches|poverty 가난|wealthy 부유한',
      'social status|명|사회적 지위|social position|—|—',
      'conspicuous consumption|명|과시적 소비|—|—|conspicuous 눈에 띄는',
      'prestigious|형|명성 있는, 고급스러운|esteemed|—|prestige 명성',
      'exclusive|형|고급의, 독점적인|elite|common 흔한|exclusivity 독점성',
      'be willing to|숙|기꺼이 ~하다|be ready to|be unwilling to 꺼리다|willingness 의향',
      'financial success|명|경제적 성공|—|—|finance 재정',
      'goods|명|물건, 상품|products|—|—',
      'luxury brand|명|명품 브랜드|—|—|luxurious 호화로운',
      'be based on|숙|~에 근거하다|be founded on|—|basis 근거',
      'economist|명|경제학자|—|—|economy 경제',
      'according to|숙|~에 따르면|—|—|—',
      'theory|명|이론|idea|practice 실제|theoretical 이론적인',
      'symbolize|동|상징하다|represent|—|symbol 상징',
    ],
    flow: [
      ['💰', '정의 — 비싸서 산다', '베블런 효과: 제품이 **비싸기 때문에** 더 기꺼이 사는 소비 행동. 가격이 **오를수록** 수요가 늘 수 있다.'],
      ['⌚', '이유 — 부와 지위 과시', '소비자는 **부·성공·사회적 지위**를 보여 주려고 산다. 명품·고급 시계·스포츠카·디자이너 핸드백.'],
      ['📖', '배경 — 과시적 소비', '경제학자 **소스타인 베블런**의 **과시적 소비**: **품질뿐 아니라** 경제적 성공을 **과시**하려고 산다.'],
      ['📌', '정리 — In Short', '제품이 **부·명성·지위를 상징**하기 때문에 **가격이 오를수록 수요도 오르는** 경향.'],
    ],
    cards: [
      {
        covers: [1],
        tags: ['title'],
        en: '[h:The Veblen effect] is [h:a type of] consumer behavior [g:in which] people [g:are more willing to buy] a product | [r:because] it is expensive.',
        note: '**해석 도움** — 베블런 효과는 사람들이 제품이 **비싸기 때문에** 그것을 **더 기꺼이** 사려고 하는 **소비자 행동의 한 유형**이다 — **정의 문장**.',
        points: [
          ['grammar', '**[수업 필기] 전치사 + 관계대명사 in which** — 박스 친 {in which} 가 화살표처럼 {consumer behavior} 를 꾸민다. {in which} = {where}(뒤에 완전한 문장).'],
          ['grammar', '**[수업 필기] be willing to: 기꺼이 ~하다** — 형광펜 {are more willing to}. {more} 가 붙어 "**더** 기꺼이".'],
          ['grammar', '**[수업 필기] because (접) ~한 이유로** — 뒤에 **주어 + 동사**({it is expensive}). {because of} 뒤에는 명사.'],
          ['vocab', '**[수업 필기] a type of = 한 종류 / consumer = 소비자 / behavior = 행동**.'],
        ],
      },
      {
        covers: [2],
        en: '[r:Unlike] most products, demand for Veblen goods [g:may] increase | [r:as] their prices rise.',
        note: '**해석 도움** — **대부분의 제품과 달리**, 베블런재의 수요는 가격이 **오를수록** 늘어날 **수도 있다**. (보통은 비싸지면 덜 산다.)',
        points: [
          ['grammar', '**[수업 필기] Unlike = ~와는 달리 (전치사)** — 뒤에 명사 {most products}.'],
          ['grammar', '**[수업 필기] as (접) ~에 따라 / ~할수록** — 동그라미 친 {increase} 와 {as}: "가격이 오를**수록** 수요가 증가한다". 비례의 as.'],
          ['grammar', '**[수업 필기] may = ~일 수도 있다(추측) / goods = 물건** — {goods} 는 "상품"의 뜻일 때 늘 **복수형**.'],
        ],
      },
      {
        covers: [3, 4],
        en: 'Consumers often [g:purchase] these products [r:to show] their wealth, success, or social status. | Luxury brands, expensive watches, sports cars, and designer handbags | [g:are] common examples of Veblen goods.',
        note: '**해석 도움** — 소비자는 자신의 **부·성공·사회적 지위**를 **보여 주기 위해** 이런 제품을 산다. 명품 브랜드, 비싼 시계, 스포츠카, 디자이너 핸드백이 **베블런재의 예**다.',
        points: [
          ['grammar', '**[수업 필기] to V: 부사적 용법 – 목적** — {to show ~} "~을 **보여 주기 위해**".'],
          ['vocab', '**[수업 필기] purchase = 구매하다 / wealth = 부 / success = 성공 / social status = 사회적 지위 / Luxury brands = 명품 브랜드**.'],
          ['grammar', '**A, B, C, and D → 복수 동사 are** — 주어가 네 개 나열.'],
        ],
      },
      {
        covers: [5],
        en: 'This idea [g:is based on] the concept of [h:conspicuous consumption], | [r:introduced by] the American economist Thorstein Veblen.',
        note: '**해석 도움** — 이 생각은 미국의 **경제학자** 소스타인 베블런이 **소개한** **과시적 소비**라는 개념에 **근거한다**.',
        points: [
          ['grammar', '**[수업 필기] be based on: ~에 근거하다** — 형광펜.'],
          ['grammar', '**과거분사구 introduced by ~** — 쉼표 뒤 {introduced by ~} = {which was introduced by ~}. {conspicuous consumption} 을 설명한다.'],
          ['vocab', '**[수업 필기] economist = 경제학자 / conspicuous consumption = 과시적 소비**(손글씨 단어표).'],
        ],
      },
      {
        covers: [6],
        en: '[r:According to] this theory, some people buy expensive goods | [g:not only] for their quality [g:but also] to display their financial success.',
        note: '**해석 도움** — 이 **이론에 따르면**, 어떤 사람들은 비싼 물건을 **품질 때문만이 아니라** 자신의 **경제적 성공을 과시하기 위해서도** 산다.',
        points: [
          ['grammar', '**[수업 필기] not only A but also B — A뿐만 아니라 B도** — 형광펜. A = {for their quality}, B = {to display their financial success}. 둘 다 "사는 **이유**"로 짝을 이룬다.'],
          ['vocab', '**[수업 필기] According to = ~에 따르면 / theory = 이론 / financial success = 경제적 성공**. {display} 과시하다·보여 주다.'],
        ],
      },
      {
        covers: [7, 8],
        en: 'A customer chooses a luxury watch [r:instead of] a cheaper [h:one] | because its high price [g:makes] the watch [g:seem] more prestigious. | A luxury brand raises the price of a handbag, | and demand increases because the product [g:appears] even more exclusive.',
        note: '**해석 도움** — 프린트의 **[Example]** 아래 두 예시. 높은 가격이 시계를 **더 고급스러워 보이게** 하고, 핸드백 가격을 **올리자** 제품이 **훨씬 더 고급스러워** 보여 수요가 는다.',
        points: [
          ['grammar', '**사역동사 make + 목적어 + 동사원형** — {makes the watch seem more prestigious}({to seem} ×). / {one} = watch.'],
          ['grammar', '**seem / appear + 형용사** — "~하게 **보이다**". {even + 비교급} "**훨씬 더**". / {raise}(타동사, 올리다) vs {rise}(자동사, 오르다).'],
          ['vocab', '**[수업 단어표] prestigious = 명성이 있는, 고급스러운 / exclusive = 고급의** — 둘 다 "비싸서 더 원하게 되는" 이유. {instead of} ~ 대신에.'],
        ],
      },
      {
        covers: [9],
        tags: ['title'],
        en: 'The Veblen effect is the tendency [r:for demand] [g:to rise] | [r:as] the price of a product rises | [r:because] the product [g:symbolizes] wealth, prestige, or social status.',
        note: '**해석 도움** — 프린트의 **[In Short]** 요약. 베블런 효과 = 제품이 **부·명성·사회적 지위를 상징**하기 때문에 **가격이 오를수록 수요가 오르는** 경향.',
        points: [
          ['grammar', '**to부정사의 의미상 주어 for + 명사** — {the tendency for demand to rise} "**수요가** 오르는 경향". 오르는 주체 = demand.'],
          ['grammar', '**비례의 as (2번과 같은 구조)** — {as the price of a product rises}. 첫 단락의 정의를 한 문장으로 다시 정리했다.'],
          ['vocab', '**symbolize / prestige** — 상징하다 / 명성({prestigious} 명성 있는).'],
        ],
      },
    ],
    prompt: `Photorealistic interior photograph, wide banner composition. A bright upscale boutique display: an elegant luxury wristwatch resting on a white marble stand beside a structured designer handbag on a velvet tray, glass shelves and soft reflections behind, no price tags. Refined, aspirational, clean mood. ${LIGHT}, white marble, champagne gold and soft taupe. ${NO}, sneakers, crowd, monkeys, stage --ar 16:5 --v 8.1`,
  },

  /* ── 11 Romeo and Juliet effect ──────────────────── */
  {
    no: 11, exam: EXAM, type: '제목', answer: 1,
    question: '다음 글의 제목으로 가장 적절한 것은?',
    summary: '로미오와 줄리엣은 서로 겨우 5일 동안 알았는데도 사랑에 빠졌어요. 한 심리학자는 부모의 반대 같은 문제가 많았기 때문에 서로를 더 원했다고 설명해요. 이 심리는 쇼핑에도 적용돼서, 사람들은 무언가가 사라질지도 모른다고 생각하면 더 원하게 돼요. 판매자들은 “단 3일 남았어요!”라며 이 효과를 이용하므로, 그럴 때는 정말 필요한지 스스로 물어봐야 해요.',
    mainIdea: 'People want things more when they think the things might disappear, which is called the Romeo and Juliet effect.',
    titleEn: 'The Romeo and Juliet Effect: Wanting What Might Disappear',
    ko: [
      '로미오와 줄리엣의 사랑 이야기는 매우 슬프다.',
      '이야기에서, 그들은 함께할 수 없었기 때문에 죽기로 선택했다.',
      '그런데 로미오와 줄리엣이 서로 단 5일 동안만 알았다는 것을 알고 있었는가?',
      '정말로 누군가와 그렇게 빨리 사랑에 빠질 수 있을까?',
      '한 심리학자는 그들이 왜 그렇게 빨리 사랑에 빠졌는지에 대한 생각을 가지고 있다.',
      '그 생각은 로미오와 줄리엣이 많은 문제를 가지고 있었기 때문에 서로를 더 좋아했다는 것이다.',
      '그들의 부모는 그들의 사랑을 좋아하지 않았고 그들을 막으려고 했는데, 이것이 로미오와 줄리엣이 서로를 훨씬 더 원하게 만들었다.',
      '이 감정은 단지 사랑에 관한 것만이 아니라, 쇼핑에도 적용된다.',
      '사람들은 무언가가 사라질지도 모른다고 생각할 때 그것을 더 원한다.',
      '여러분은 사람들이 무언가가 사라질지도 모른다고 생각할 때 왜 그것을 더 원하는지 궁금할지도 모른다.',
      '많은 판매자들은 로미오와 줄리엣에서 나온 이 생각을 이용한다.',
      '그들은 “단 3일 남았습니다!',
      '사라지기 전에 사세요!”라고 말한다.',
      '구매자들은 원하는 것을 얻지 못할까 봐 걱정해서, 즉시 구매한다.',
      '이것은 로미오와 줄리엣 효과라고 불린다.',
      '그러니 다음에 ‘3일 한정 세일’을 보면, 스스로에게 물어보라. 내가 정말로 그것이 필요할까?',
    ],
    choices: [
      ['Why We Want Things More When They Might Disappear', '사라질 것 같으면 더 원하는 로미오와 줄리엣 효과 — **정답**.'],
      ['The True Story of Romeo and Juliet', '이야기는 **도입**일 뿐이다.'],
      ['How Parents Can Stop Young Love', '부모의 반대는 **예시**의 일부다.'],
      ['Why Sales Always Save Money', '세일이 돈을 아껴 준다는 내용이 아니다.'],
      ['The Best Way to Choose a Gift', '선물 고르기는 언급되지 않는다.'],
    ],
    vocab: [
      'choose|동|선택하다 (choose-chose-chosen)|pick, select|—|choice 선택',
      'each other|대|서로|one another|—|—',
      'fall in love with|숙|~와 사랑에 빠지다|—|—|—',
      'psychologist|명|심리학자|—|—|psychology 심리학',
      'problem|명|문제|trouble|solution 해결책|—',
      'try to|숙|~하려고 애쓰다|attempt to|—|—',
      'apply to|숙|~에 적용되다|relate to|—|application 적용',
      'go away|숙|사라지다|disappear, leave|stay 머물다|—',
      'wonder|동|궁금해하다|ask oneself|—|—',
      'disappear|동|사라지다|vanish|appear 나타나다|disappearance 사라짐',
      'seller|명|판매자|vendor|buyer 구매자|sell 팔다',
      'worry about|숙|~을 걱정하다|be concerned about|—|worried 걱정하는',
      'right away|숙|즉시|immediately, at once|later 나중에|—',
      'ask oneself|숙|스스로에게 묻다|—|—|—',
    ],
    flow: [
      ['💔', '이야기 — 5일 만의 사랑', '로미오와 줄리엣은 겨우 **5일** 알았는데 사랑에 빠져 함께 죽음을 택했다.'],
      ['🧠', '설명 — 장애물이 사랑을 키웠다', '부모의 반대처럼 **문제가 많을수록** 서로를 **더** 원했다는 심리학자의 생각.'],
      ['🛍️', '적용 — 쇼핑에도 같다', '사람들은 무언가가 **사라질지도 모른다고** 생각하면 더 원한다 → “**Only three days left!**” 마케팅.'],
      ['🤔', '결론 — 정말 필요한가?', '이것이 **로미오와 줄리엣 효과**. 3일 한정 세일을 보면 **Do I really need it?** 스스로 물어보자.'],
    ],
    cards: [
      {
        covers: [1, 2],
        en: 'Romeo and Juliet’s love story is very sad. | In the story, they [g:chose to die] [r:because] they couldn’t be together.',
        note: '**해석 도움** — 로미오와 줄리엣은 **함께할 수 없었기 때문에** 죽기로 **선택했다**.',
        points: [
          ['grammar', '**[수업 필기] choose + to V** — {chose to die} "죽기로 **선택했다**". {choose} 는 to부정사를 목적어로 쓴다.'],
          ['grammar', '**[수업 필기] choose – chose – chosen** — 불규칙 3단 변화. {chose} 는 과거형.'],
        ],
      },
      {
        covers: [3, 4],
        en: 'But did you know [r:that] Romeo and Juliet knew each other [r:for] only five days? | Can you really [g:fall in love with] someone so quickly?',
        note: '**해석 도움** — 두 사람이 서로 **단 5일 동안만** 알았다는 것을 알았는가? 정말 누군가와 그렇게 빨리 **사랑에 빠질** 수 있을까?',
        points: [
          ['grammar', '**[수업 필기] know 의 목적어 that절** — 박스 친 {that} + 여백 "**목적어**". {know that S + V} "~라는 것을 알다".'],
          ['grammar', '**[수업 필기] for + 기간** — 동그라미 {for only five days} "**5일 동안**". ({during} + 특정 기간: {during the vacation})'],
          ['vocab', '**[수업 필기] fall in love with = 사랑에 빠지다** — 동그라미 {with}. {fall in love with someone}.'],
        ],
      },
      {
        covers: [5],
        en: 'A [h:psychologist] has an idea about [g:why they fell in love so soon].',
        note: '**해석 도움** — 한 **심리학자**는 그들이 **왜 그렇게 빨리 사랑에 빠졌는지**에 대한 생각을 가지고 있다. {why ~} 는 전치사 {about} 의 목적어인 **간접의문문**이다.',
        points: [
          ['grammar', '**[수업 프린트] 간접의문문이란** — 의문문이 문장 속에 들어가 **주어·목적어·보어** 역할을 하는 것. 여기서는 {about} 의 목적어.'],
          ['grammar', '**[수업 프린트] ① 의문사가 있는 간접의문문 = 의문사 + 주어 + 동사** — 직접의문문은 의문문 어순이지만, 간접의문문은 **평서문 어순**. 직접의문문 {Why did they fall in love so soon?} → 간접의문문 {why they fell in love so soon}({did} 가 빠지고 동사가 과거형 {fell}).'],
          ['vocab', '**[수업 필기] psychologist = 심리학자** — {p} 는 소리 나지 않는다.'],
        ],
      },
      {
        covers: [6],
        en: 'The idea is [r:that] Romeo and Juliet liked each other [g:more] | because they had many problems.',
        note: '**해석 도움** — 그 생각은 두 사람이 **문제가 많았기 때문에** 서로를 **더** 좋아했다는 **것**이다.',
        points: [
          ['grammar', '**[수업 필기] The idea is that ~** — 박스 친 {that}. 필기는 "**동격 that**"이라 적었는데, be동사 뒤에서 {The idea} 의 내용(= ~라는 것)을 말하는 **보어 역할 명사절 that** 이다. {the idea that ~}(동격)과 뜻은 같다.'],
          ['grammar', '**[수업 필기] more 의 원급** — {more} 는 {many / much} 의 비교급. 여기서는 동사 {liked} 를 꾸미므로 **much → more**("더 많이").'],
        ],
      },
      {
        covers: [7],
        en: 'Their parents did not like their love and [g:tried to stop] them, | [r:which] [g:made] Romeo and Juliet [g:want] each other even more.',
        note: '**해석 도움** — 부모가 둘의 사랑을 싫어하고 **막으려 했는데**, **그것이** 두 사람이 서로를 **훨씬 더 원하게** 만들었다.',
        points: [
          ['grammar', '**[수업 필기] try to: ~하려고 하다** — {tried to stop} "막**으려고 애썼다**". ({try -ing} "시험 삼아 ~해 보다")'],
          ['grammar', '**계속적 용법 , which = 앞 절 전체** — {, which made ~} = {and this made ~}. 부모가 막으려 한 **일 전체**가 선행사.'],
          ['grammar', '**사역동사 make + 목적어 + 동사원형** — {made Romeo and Juliet want ~}. / {even more} 비교급 강조 "**훨씬 더**"(even, much, far, still, a lot).'],
        ],
      },
      {
        covers: [8, 9],
        en: 'This feeling is [g:not just] about love, [g:but] it [g:also] [g:applies to] shopping. | People want something more | [r:when] they think [h:it] [g:might] go away.',
        note: '**해석 도움** — 이 감정은 사랑**만의** 이야기가 **아니라** 쇼핑에**도 적용된다**. 사람들은 무언가가 **사라질지도 모른다고** 생각하면 그것을 더 원한다 — **글의 핵심**.',
        points: [
          ['grammar', '**not just A but (also) B** — "A**뿐만 아니라** B도" = {not only A but also B}(10번 Veblen 지문 6번 문장).'],
          ['vocab', '**[수업 필기] apply to = 적용되다** — {applies to shopping} 쇼핑에도 **적용된다**.'],
          ['vocab', '**might / go away** — 약한 추측 "~할지도 모른다" / "**사라지다**". {it} = {something}.'],
        ],
      },
      {
        covers: [10],
        en: 'You [g:may] wonder [h:why people want somethings more] | [r:when] they think they might disappear.',
        note: '**해석 도움** — 여러분은 사람들이 무언가가 사라질지도 모른다고 생각할 때 **왜 그것을 더 원하는지** 궁금할지도 모른다. ※ 인쇄본 표기 {somethings} 를 그대로 실었다(보통은 {something}).',
        points: [
          ['grammar', '**[수업 필기] 조동사 may + 동사원형** — {may wonder} "궁금할**지도 모른다**".'],
          ['grammar', '**[수업 필기] 간접의문문 = 의문사 + S + V** — 밑줄 친 {why people want ~}: 의문사 {why} + 주어 {people} + 동사 {want}. {wonder} 의 목적어.'],
          ['grammar', '**[수업 프린트] ② 의문사가 주어인 경우** — 의문사가 주어 역할을 하면 **어순이 바뀌지 않는다**: {Who broke the window?} → {I wonder who broke the window.}'],
          ['grammar', '**[수업 프린트] ③ Yes/No 의문문** — 의문사가 없는 의문문은 **if / whether + 주어 + 동사**: {Is she busy?} → {I wonder if(whether) she is busy.} / {Did he finish the homework?} → {I wonder if(whether) he finished the homework.}'],
        ],
      },
      {
        covers: [11, 12, 13],
        en: 'Many sellers use this idea from Romeo and Juliet. | They say, [h:“Only three days left!] | [h:Buy before it’s gone!”]',
        note: '**해석 도움** — 판매자들은 이 생각을 이용해 “**단 3일 남았어요! 사라지기 전에 사세요!**”라고 말한다 — **사라질 것 같은 느낌**을 만드는 마케팅.',
        points: [
          ['grammar', '**Only three days left!** — {There are only three days left.} 의 줄임. {left} 는 과거분사 "**남은**".'],
          ['grammar', '**명령문 + it’s gone** — {Buy ~!} 사세요. {it’s gone} = {it is gone}({gone} 형용사 "사라진").'],
        ],
      },
      {
        covers: [14, 15],
        en: 'Buyers [g:worry about] [r:not] [g:getting] [h:what they want], | [r:so] they buy right away. | This [g:is called] the Romeo and Juliet effect.',
        note: '**해석 도움** — 구매자들은 원하는 것을 **얻지 못할까 봐** 걱정해서 **즉시** 산다. 이것을 **로미오와 줄리엣 효과**라고 부른다.',
        points: [
          ['grammar', '**[수업 필기] 전치사 about + 동명사** — 동그라미 {about} 과 {getting}. 동명사의 **부정은 not 을 앞에**: {not getting}.'],
          ['grammar', '**관계대명사 what / so (결과)** — {what they want} "그들이 원하는 **것**". 박스 친 {so} "**그래서**".'],
          ['vocab', '**[수업 필기] right away = 즉시** — 밑줄. {be called} ~라고 불리다.'],
        ],
      },
      {
        covers: [16],
        tags: ['title'],
        en: '[r:So], next time you see a “3-day-only sale,” | [g:ask yourself]: Do I really need it?',
        note: '**해석 도움** — **그러니** 다음에 ‘3일 한정 세일’을 보면 **스스로에게 물어보라**. 내가 정말 그것이 필요할까? — 글의 **결론**.',
        points: [
          ['grammar', '**[수업 필기] So, = 그러니(결론)** — 박스. 앞 내용을 바탕으로 **충고**한다.'],
          ['grammar', '**[수업 필기] ask yourself — 명령문 + 재귀대명사** — 밑줄. "**스스로에게** 묻다". 주어(you)와 목적어가 같아 {yourself}.'],
          ['grammar', '**next time + S + V / 3-day-only** — "다음에 ~할 때" / 하이픈 복합 형용사 안의 명사는 **단수**({3-days-only} ×).'],
        ],
      },
    ],
    prompt: `Photorealistic exterior photograph, wide banner composition. An old stone balcony of a Verona-style house covered with climbing red roses, a small brass hourglass with falling sand standing on the balcony ledge, warm stone walls and a pale sky behind. Romantic but gently ticking-clock mood that hints at time running out. ${LIGHT}, soft rose red, warm stone beige and pale sky blue. ${NO}, shop signs, price tags, monkeys, stage --ar 16:5 --v 8.1`,
  },
];
