/* 봉영여중3 추가지문 01~04 저작 데이터 — _author-EX.mjs 가 모아서 쓴다.
 * (중요) 사진 속 수업 필기(밑줄·S/V 표시·화살표·여백 문법 노트·단어표 뜻)를 문장 분석 카드에
 *   **[수업 필기]** 로 녹였다. 필기 뜻이 틀린 곳(예: silently)은 바른 뜻으로 고쳐 실었다.
 * hide_answer 라 choices 는 인쇄되지 않지만, 원본 문제의 보기·정답을 그대로 기록해 둔다. */

export const EXAM = '봉영여중 3학년 · 추가지문';
export const LIGHT = 'natural soft diffused daylight, bright overcast sky, high-key exposure, low contrast, clean bright palette';
export const NO = '--no text, letters, words, numbers, signage, logo, brand, watermark, people, person, hands, faces, sunset, golden hour, night, dark moody grading, heavy shadows';

export const chapters = [
  /* ── 01 목적 파악 ─────────────────────────────────── */
  {
    no: 1, exam: EXAM, type: '목적', answer: 5,
    question: '다음 글의 목적으로 가장 적절한 것은?',
    summary: 'Sarah Roberts가 Pittsburgh 기차역에 보낸 편지예요. 역이 직원이 있는 매표소를 승차권 자동판매기로 바꾸자, 기계에 익숙하지 않은 사람들이 철도를 이용하기 어려워졌어요. 이들은 직원의 도움에 크게 의존해 왔기 때문에 직원이 있는 매표소가 꼭 필요하다며, 매표소를 다시 열어 달라고 촉구해요.',
    mainIdea: 'The writer urges Pittsburgh Train Station to reopen its staffed ticket offices for people who struggle with ticket vending machines.',
    titleEn: 'Please Reopen the Staffed Ticket Offices',
    ko: [
      '관계자분께, 저는 Pittsburgh 기차역이 시행한 최근의 변화에 대해 깊은 우려를 표하기 위해 이 글을 씁니다.',
      '그 역에는 이전에 직원이 있는 전통적인 매표소가 있었지만, 이것들이 승차권 자동판매기로 대체되었습니다.',
      '그러나 이 기계들에 익숙하지 않은 사람들은 현재 철도 서비스를 이용하는 데 어려움을 겪고 있습니다.',
      '이 사람들은 이동을 하기 위해 직원의 도움에 크게 의존했기 때문에, 역에 직원이 있는 매표소를 몹시 필요로 합니다.',
      '그러므로 저는 귀하께서 매표소를 다시 여는 것을 고려해 주시기를 촉구합니다.',
      '직원들이 제자리로 돌아오면, 많은 사람들이 철도 서비스를 다시 이용할 수 있을 것입니다.',
      '이 문제에 대한 귀하의 신속한 관심과 긍정적인 해결을 기대합니다.',
      'Sarah Roberts 드림',
    ],
    choices: [
      ['승차권 발매기 수리를 의뢰하려고', '발매기 **고장·수리** 이야기는 없다. 기계에 **익숙하지 않은** 사람들이 문제다.'],
      ['기차표 단체 예매 방법을 문의하려고', '**단체 예매**는 언급되지 않는다.'],
      ['기차 출발 시간 지연에 대해 항의하려고', '**출발 지연**은 언급되지 않는다.'],
      ['기차역 직원의 친절한 도움에 감사하려고', '직원의 도움은 **필요한 이유**로 나올 뿐, 감사하는 글이 아니다.'],
      ['기차역 유인 매표소 재운영을 요구하려고', '{Therefore, I am urging you to consider reopening the ticket offices.} — **정답**.'],
    ],
    vocab: [
      'concern|동|~에 관계되다 (명) 우려|be related to|—|concerned 걱정하는',
      'express|동|표현하다|show, convey|hide 숨기다|expression 표현',
      'recent|형|최근의|latest|old 오래된|recently 최근에',
      'traditional|형|전통적인|conventional|modern 현대적인|tradition 전통',
      'ticket office|명|매표소|box office|—|—',
      'replace|동|대체하다|substitute|—|replacement 대체',
      'vending machine|명|자판기|—|—|vend 팔다',
      'individual|명|개인 (형) 개인의|person|group 집단|individually 개별적으로',
      'unfamiliar|형|익숙하지 않은|unknown, strange|familiar 익숙한|familiarity 익숙함',
      'experience|동|경험하다, 겪다|undergo|—|experienced 숙련된',
      'access|동|접근하다, 이용하다|reach, use|—|accessible 접근 가능한',
      'rely on|숙|의존하다|depend on, count on|—|reliance 의존',
      'assistance|명|도움|help, aid|—|assist 돕다',
      'in need of|숙|~을 필요로 하는|needing|—|—',
      'urge|동|촉구하다|press, push|—|urgent 긴급한',
      'regain|동|되찾다, 회복하다|recover, get back|lose 잃다|—',
      'prompt|형|신속한|quick, immediate|slow 느린|promptly 즉시',
      'attention|명|주의, 관심|notice, focus|—|attend 주의하다',
      'resolution|명|해결|solution|—|resolve 해결하다',
    ],
    flow: [
      ['🚉', '상황 — 매표소가 사라졌다', 'Pittsburgh 기차역이 직원이 있는 **전통적인 매표소**를 **승차권 자동판매기**로 바꿨다.'],
      ['😟', '문제 — 기계가 낯선 사람들', '{However} — 기계에 **익숙하지 않은** 사람들이 철도 서비스를 **이용하는 데 어려움**을 겪는다.'],
      ['🙏', '요청 — 매표소를 다시 열어 주세요', '{Therefore, I am urging you ~} — 직원의 도움에 **의존하던** 사람들을 위해 **매표소 재운영**을 촉구한다.'],
      ['✅', '정답 — ⑤ 유인 매표소 재운영 요구', '목적은 {Therefore} 뒤에 있다. ① 발매기 수리 ② 단체 예매 ③ 출발 지연 ④ 감사는 **본문에 없다**.'],
    ],
    cards: [
      {
        covers: [1],
        en: '[h:To whom it may concern], | I [g:am writing] [r:to express] my deep concern about the recent change | [r:made] by Pittsburgh Train Station.',
        note: '**해석 도움** — {To whom it may concern} 은 받는 사람을 모를 때 쓰는 편지 첫머리 "**관계자분께**"다. {made by ~} 는 {the recent change} 를 뒤에서 꾸민다.',
        points: [
          ['vocab', '**concern 두 가지 뜻** — 첫머리 {may concern} 은 동사 "~**에 관계되다**"(수업 단어표), {my deep concern} 은 명사 "**우려**"다.'],
          ['grammar', '**to부정사 부사적 용법(목적)** — {to express ~} "~을 **표현하기 위해**". 편지를 쓰는 **이유**를 밝힌다.'],
          ['grammar', '**[수업 필기] 과거분사 후치수식** — {the recent change made by ~}. {made}(p.p.)가 이끄는 **수식어구**가 명사를 뒤에서 꾸민다 = {which was made by ~}.'],
        ],
      },
      {
        covers: [2],
        en: 'The station had [h:traditional ticket offices with staff] before, | but [r:these] [g:have been replaced with] ticket vending machines.',
        note: '**해석 도움** — {these} 는 앞의 {traditional ticket offices with staff}(직원이 있는 전통적인 매표소)를 가리킨다. {with staff} 는 "**직원이 있는**".',
        points: [
          ['grammar', '**[수업 필기] replace A with B → A be replaced with B** — "A를 B로 대체하다" → 수동태 "A가 B로 대체되다". 여기서 A = {these}(매표소), B = {ticket vending machines}.'],
          ['grammar', '**현재완료 수동태 have been p.p.** — 과거에 대체되어 **지금도** 매표소가 없는 상태다.'],
          ['reading', '**[수업 필기] 지칭** — {these} = 매표소(동그라미·화살표). 대명사가 가리키는 말을 반드시 확인한다.'],
        ],
      },
      {
        covers: [3],
        en: '[r:However], [h:individuals] [r:who] are unfamiliar with these machines | [g:are] now [g:experiencing difficulty] [h:accessing] the railway services.',
        note: '**해석 도움** — 주어는 {individuals who are unfamiliar with these machines}(이 기계들에 익숙하지 않은 사람들), 동사는 {are experiencing} 이다. {However} 로 **문제**가 시작된다.',
        points: [
          ['grammar', '**[수업 필기] 주어(S)와 동사(V)** — 주격 관계대명사절 [{who are unfamiliar with these machines}] 을 괄호로 묶으면 S {individuals} — V {are} 가 바로 보인다.'],
          ['grammar', '**[수업 필기] have(experience) difficulty(trouble) -ing (중요)** — "~하는 데 어려움을 겪다". {difficulty} 뒤에 **동명사** {accessing} 이 온다({to access} ×).'],
          ['vocab', '**[수업 필기] be unfamiliar with** — "~에 **익숙하지 않다**". 반대는 {be familiar with}.'],
          ['vocab', '**[수업 필기] access vs assess** — {access} 접근하다·이용하다 / {assess} **평가하다**. 철자 한 글자 차이라 시험에 잘 나온다.'],
        ],
      },
      {
        covers: [4],
        en: '[r:Since] these individuals heavily [g:relied on] the staff assistance [r:to be able to travel], | they are [h:in great need of] ticket offices with staff in the station.',
        note: '**해석 도움** — {Since} 는 여기서 "~**이기 때문에**"(이유)다. 이 사람들이 직원의 도움에 **크게 의존해 왔으므로** 직원이 있는 매표소가 **몹시 필요하다**는 뜻이다.',
        points: [
          ['grammar', '**[수업 필기] Since = because (중요)** — 이유의 접속사. "~**이후로**"(시간)의 since 와 구별한다(현재완료와 함께 쓰이면 주로 시간).'],
          ['vocab', '**[수업 필기] rely on / heavily vs highly** — {rely on} 의존하다. {heavily} 는 "**크게, 심하게**", 필기의 {highly} 는 "**매우**"({high} 높이 와 다르다) — -ly 가 붙으면 뜻이 바뀌는 부사에 주의.'],
          ['grammar', '**to be able to + 동사원형** — {be able to} = {can}. {to be able to travel} 은 "**이동할 수 있기 위해**"(목적).'],
          ['vocab', '**in (great) need of** — "~을 (몹시) **필요로 하는**". {need} 가 **명사**로 쓰였다.'],
        ],
      },
      {
        covers: [5],
        tags: ['title'],
        en: '[r:Therefore], I [g:am urging you to consider] [h:reopening] the ticket offices.',
        note: '**해석 도움** — {Therefore}(그러므로) 뒤가 **글의 목적**이다. 매표소를 **다시 여는 것**을 고려해 달라고 **촉구**한다 → 정답 ⑤.',
        points: [
          ['grammar', '**[수업 필기] urge A to 동사원형** — "A에게 ~할 것을 **촉구하다**(요구하다)". {urge you to consider}.'],
          ['grammar', '**[수업 필기] consider + -ing** — {consider} 는 **동명사**를 목적어로 쓴다: {consider reopening}({consider to reopen} ×).'],
          ['vocab', '**re- (다시)** — {reopen} 다시 열다, {regain} 되찾다(6번 문장). 접두사 {re-} 는 "**다시**".'],
        ],
      },
      {
        covers: [6],
        en: '[r:With] [h:the staff] back in their positions, | many people [g:would regain] access to the railway services.',
        note: '**해석 도움** — "직원들이 **제자리로 돌아오면**, 많은 사람들이 철도 서비스를 **다시 이용할 수 있을 것**이다." 매표소 재운영의 **기대 효과**다.',
        points: [
          ['grammar', '**with + 명사 + 부사(구)** — "~가 ~한 채로 / ~하면". {with the staff back in their positions} 는 조건처럼 해석된다.'],
          ['grammar', '**would + 동사원형** — 아직 일어나지 않은 일의 **가정적 결과** "~할 것이다"(매표소가 다시 열린다면).'],
          ['vocab', '**access 명사 vs 동사** — {regain access to ~}(명사 "이용") / 3번 {accessing the railway services}(동사 "이용하다"). 명사로 쓸 땐 {access to}.'],
        ],
      },
      {
        covers: [7, 8],
        en: 'I [g:look forward to] [h:your prompt attention] to this matter and a positive resolution. | Sincerely, Sarah Roberts',
        note: '**해석 도움** — "이 문제에 대한 귀하의 **신속한 관심**과 **긍정적인 해결**을 기대합니다." 편지 끝 인사다. {Sincerely} 는 맺음말 "~ 드림".',
        points: [
          ['grammar', '**[수업 필기] look forward to + -ing / 명사** — "~을 기대하다". 이 {to} 는 **전치사**라 동명사나 명사가 온다. 여기선 명사구 {your prompt attention}(동그라미 {your}).'],
          ['vocab', '**[수업 필기] pay attention to** — "~에 **주의를 기울이다**". {attention to this matter} 도 같은 {to}.'],
          ['vocab', '**prompt / resolution** — {prompt} 신속한, {resolution} 해결({resolve} 해결하다).'],
        ],
      },
    ],
    prompt: `Photorealistic interior photograph, wide banner composition. A quiet bright old railway station hall: a closed ticket office window with its blinds pulled down, beside a neat row of modern ticket vending machines, polished stone floor, tall arched windows. Calm, slightly nostalgic mood with lots of soft space. ${LIGHT}, soft cream, pale grey and muted sage green. ${NO}, trains, stage, monkeys --ar 16:5 --v 8.1`,
  },

  /* ── 02 심경 분위기 파악 ─────────────────────────── */
  {
    no: 2, exam: EXAM, type: '심경 변화', answer: 5,
    question: '다음 글에 드러난 Jeevan의 심경 변화로 가장 적절한 것은?',
    summary: '무대에서 연기하던 Arthur가 갑자기 쓰러지고, Jeevan이 다가가 보니 심장이 뛰지 않았어요. Jeevan은 말없이 심폐소생술을 하며 다시 숨을 쉬라고 간절히 바랐어요. 잠시 후 의사인 Walter Jacobi가 나타나 함께 Arthur를 살려 냈고, Arthur의 숨소리를 다시 들은 Jeevan은 “다행이다, 돌아왔구나.”라며 안도해요.',
    mainIdea: 'Jeevan desperately performs CPR on Arthur and finally feels relieved when, with Dr. Jacobi’s help, Arthur breathes again.',
    titleEn: 'From Desperation to Relief on the Stage',
    ko: [
      '무대 위의 모든 배우들은 자신의 연기에 집중하고 있었다.',
      '그때, 갑자기 Arthur가 무대 구석으로 쓰러졌다.',
      'Jeevan은 즉시 Arthur에게 다가갔고 그의 심장이 뛰고 있지 않다는 것을 알게 되었다.',
      'Jeevan은 심폐소생술을 시작했다.',
      'Jeevan은 이따금 Arthur의 얼굴을 흘끗 보면서 말없이 (심폐소생술을) 계속했다.',
      '그는 “제발, 다시 숨을 쉬어, 제발.”이라고 생각했다.',
      'Arthur의 눈은 감겨 있었다.',
      '잠시 후, 회색 정장을 입은 나이 든 남자가 나타나 재빨리 Arthur의 가슴 옆에 무릎을 꿇었다.',
      '“저는 Walter Jacobi입니다.',
      '저는 의사입니다.”',
      '그는 차분한 목소리로 알렸다.',
      'Jeevan은 이마의 땀을 닦아 냈다.',
      '힘을 합친 노력으로, Jeevan과 Jacobi 박사는 Arthur를 성공적으로 소생시켰다.',
      'Arthur의 눈이 천천히 떠졌다.',
      '마침내 Jeevan은 다시 Arthur의 숨소리를 들을 수 있었고, 속으로 생각했다. “다행이다.',
      '돌아왔구나.”',
    ],
    choices: [
      ['thrilled → bored', '흥분 → 지루함. 처음부터 **긴박하고 간절**하다.'],
      ['ashamed → confident', '부끄러움 → 자신감. 부끄러워할 이유가 없다.'],
      ['hopeful → helpless', '희망 → 무력감. 결말은 **소생 성공**이라 반대다.'],
      ['surprised → indifferent', '놀람 → 무관심. 끝까지 **걱정하고 안도**한다.'],
      ['desperate → relieved', '“Please, start breathing again” → “Thank goodness. You’re back.” — **정답**.'],
    ],
    vocab: [
      'suddenly|부|갑자기|all of a sudden|gradually 점차|sudden 갑작스러운',
      'immediately|부|즉시|at once|later 나중에|immediate 즉각적인',
      'approach|동|~에 다가가다|come near|—|approachable 다가가기 쉬운',
      'silently|부|조용히, 말없이|quietly|loudly 시끄럽게|silent 조용한',
      'glance at|숙|~을 흘끗 보다|peek at|stare at 응시하다|—',
      'suit|명|정장|—|—|—',
      'swiftly|부|신속하게|quickly|slowly 천천히|swift 빠른',
      'kneel|동|무릎을 꿇다|—|—|knee 무릎',
      'chest|명|가슴|breast|—|—',
      'announce|동|알리다, 발표하다|declare|—|announcement 발표',
      'calm|형|차분한|peaceful|nervous 긴장한|calmly 차분하게',
      'wipe off|숙|닦아 내다|clean off|—|—',
      'sweat|명|땀|perspiration|—|sweaty 땀투성이의',
      'forehead|명|이마|brow|—|—',
      'combined|형|합친, 결합된|joint|separate 분리된|combine 결합하다',
      'effort|명|노력|attempt|—|effortless 힘들이지 않는',
      'revive|동|소생시키다, 되살리다|bring back|—|revival 부활',
      'desperate|형|절박한, 필사적인|hopeless|—|desperately 필사적으로',
      'relieved|형|안도한|reassured|worried 걱정하는|relief 안도',
    ],
    flow: [
      ['🎭', '상황 — 무대 위 연기 중', '배우들이 연기에 **집중**하던 중 Arthur가 **갑자기** 무대 구석으로 쓰러진다.'],
      ['😰', '위기 — 심장이 멈췄다', 'Jeevan이 다가가 보니 **심장이 뛰지 않는다**. 심폐소생술을 하며 “**제발, 다시 숨 쉬어**” → **desperate**.'],
      ['🩺', '전환 — 의사의 등장', '회색 정장의 **Dr. Jacobi**가 **차분한 목소리**로 의사라고 밝히고, 두 사람이 **힘을 합쳐** Arthur를 소생시킨다.'],
      ['😌', '결말 — ⑤ desperate → relieved', '숨소리를 다시 듣고 “**Thank goodness. You’re back.**” → **안도(relieved)**. 정답 ⑤.'],
    ],
    cards: [
      {
        covers: [1],
        en: '[h:All the actors] on the stage | [g:were focused on] their acting.',
        note: '**해석 도움** — 주어는 {All the actors}, {on the stage} 는 주어를 꾸미는 **전치사구**, 동사는 {were focused on} 이다.',
        points: [
          ['grammar', '**[수업 필기] 주어(S) 찾기** — 전치사구 ({on the stage}) 를 괄호로 묶으면 S {All the actors} → V {were} 가 바로 연결된다. 복수 주어라 {were}.'],
          ['vocab', '**be focused on** — "~에 **집중하다**". 사건 직전의 평온한 분위기.'],
        ],
      },
      {
        covers: [2],
        en: 'Then, [r:suddenly], [h:Arthur] [g:fell into] the corner of the stage.',
        note: '**해석 도움** — {suddenly}(갑자기)가 **사건의 시작**을 알린다. 쓰러진 사람은 **Arthur**다.',
        points: [
          ['reading', '**[수업 필기] 등장인물 구분 — 지칭 문제** — 선생님이 "**지칭하는 것 구분하는 문제**"를 말씀하셨다. 쓰러진 사람 = **Arthur**(세모 표시), 돕는 사람 = **Jeevan**, 나중에 온 의사 = **Walter Jacobi**. {he / his} 가 누구인지 문장마다 확인할 것.'],
          ['vocab', '**fall into** — "~으로 쓰러지다, 빠지다". {fall – fell – fallen}.'],
        ],
      },
      {
        covers: [3, 4],
        en: 'Jeevan immediately [g:approached] Arthur [r:and] [g:found] [h:his heart wasn’t beating]. | Jeevan began CPR.',
        note: '**해석 도움** — Jeevan이 Arthur에게 **다가갔고**(V1) 그의 심장이 뛰지 않는다는 것을 **알게 되었다**(V2). {CPR} 은 **심폐소생술**.',
        points: [
          ['grammar', '**[수업 필기] 동사 병렬 V1 and V2** — {approached} 와 {found} 가 {and} 로 연결된 두 동사. 주어는 둘 다 {Jeevan}.'],
          ['grammar', '**approach 는 타동사** — "~에 다가가다"인데 전치사 없이 바로 목적어: {approached Arthur}({approached to Arthur} ×).'],
          ['grammar', '**found (that) 절** — {found his heart wasn’t beating} 은 {found that ~} 에서 {that} 이 생략됐다.'],
          ['reading', '**[수업 필기] his = Arthur’s** — 심장이 멈춘 사람은 Arthur. (12번의 {his forehead} 는 **Jeevan** 의 이마 — 같은 {his} 라도 가리키는 사람이 다르다.)'],
        ],
      },
      {
        covers: [5],
        en: 'Jeevan [g:worked] silently, | [r:glancing] sometimes [h:at Arthur’s face].',
        note: '**해석 도움** — "Jeevan은 이따금 Arthur의 얼굴을 **흘끗 보면서** 말없이 (심폐소생술을) 계속했다." {glancing ~} 은 **분사구문**이다.',
        points: [
          ['grammar', '**[수업 필기] 분사구문 만드는 법** — {S+V, (접속사)+S+V} 에서 ① **접속사 생략** ② **(같은) 주어 생략** ③ **동사원형+ing**. {and he glanced} → {glancing}. ({Being / Having been} 은 생략 가능)'],
          ['vocab', '**glance at** — "~을 **흘끗 보다**". {silently} 는 "**조용히, 말없이**"(수업 단어표의 뜻은 칸이 밀려 적혀 있으니 바로잡을 것).'],
        ],
      },
      {
        covers: [6, 7],
        en: 'He thought, [h:“Please, start breathing again, please.”] | Arthur’s eyes [g:were closed].',
        note: '**해석 도움** — "제발, 다시 숨을 쉬어, 제발." — 같은 말을 되풀이하는 **간절함**이 Jeevan의 첫 심경 **desperate**(절박한)의 근거다.',
        points: [
          ['grammar', '**start + -ing / to부정사** — {start breathing} = {start to breathe}. 뜻 차이 없음.'],
          ['reading', '**심경 단서 ①** — {Please ~ please} 반복 + {Arthur’s eyes were closed}(눈이 감겨 있음) → 상황이 **절박**하다.'],
          ['grammar', '**be closed** — "감겨 있다"(상태). {closed} 는 형용사처럼 쓰인 과거분사.'],
        ],
      },
      {
        covers: [8],
        en: 'Moments later, [h:an older man] in a grey suit [g:appeared], | [r:swiftly kneeling] beside Arthur’s chest.',
        note: '**해석 도움** — 주어 {an older man (in a grey suit)} → 동사 {appeared}. 뒤의 {swiftly kneeling ~} 은 "그리고 재빨리 무릎을 꿇었다"는 **분사구문**이다.',
        points: [
          ['grammar', '**[수업 필기] 분사구문 + 쉼표** — {appeared, swiftly kneeling} 의 **쉼표**(동그라미)가 분사구문의 신호. = {and he swiftly knelt}. {kneel – knelt – knelt}.'],
          ['grammar', '**[수업 필기] 주어 수식 괄호** — ({in a grey suit}) 를 묶으면 S {man} → V {appeared}.'],
          ['vocab', '**swiftly / kneel / chest** — 신속하게 / 무릎을 꿇다 / 가슴.'],
        ],
      },
      {
        covers: [9, 10, 11],
        en: '“I’m Walter Jacobi. | I’m a doctor.” | [h:He] [g:announced] [r:with a calm voice].',
        note: '**해석 도움** — 의사가 등장하는 **전환점**. "저는 Walter Jacobi입니다. 저는 의사입니다." 그는 **차분한 목소리로** 알렸다.',
        points: [
          ['reading', '**[수업 필기] 지칭** — {He} = Walter Jacobi(나이 든 남자). Jeevan 이 아니다.'],
          ['grammar', '**with + 명사 = 방법** — {with a calm voice} "**차분한 목소리로**". 괄호로 묶이는 부사구.'],
          ['reading', '**심경 전환** — 의사의 등장 + 차분한 목소리 → 절박함이 **안도**로 바뀌기 시작한다.'],
        ],
      },
      {
        covers: [12, 13],
        en: 'Jeevan [g:wiped the sweat off] [h:his forehead]. | [r:With combined efforts], Jeevan and Dr. Jacobi successfully [g:revived] Arthur.',
        note: '**해석 도움** — Jeevan이 **자기 이마**의 땀을 닦았다. 두 사람이 **힘을 합쳐** Arthur를 **소생시켰다**. {Dr.} 는 {Doctor} 의 약어.',
        points: [
          ['reading', '**[수업 필기] his forehead = Jeevan의 이마** — 밑줄 친 {his} 는 주어 Jeevan 자신. 3번의 {his heart}(Arthur)와 헷갈리게 내는 **지칭 문제**.'],
          ['vocab', '**wipe A off B** — "B에서 A를 **닦아 내다**". 땀을 닦는 행동 = 긴장이 풀리는 순간.'],
          ['vocab', '**revive** — "**소생시키다, 되살리다**"(타동사). 필기의 "살아나다"는 자동사 뜻이니, 여기선 {revived Arthur} "Arthur를 **살려 냈다**".'],
          ['vocab', '**combined efforts** — "**합친 노력**"({combine} 결합하다).'],
        ],
      },
      {
        covers: [14, 15, 16],
        en: 'Arthur’s eyes slowly opened. | Finally, Jeevan [g:was able to hear] Arthur’s breath again, | [r:thinking to himself], [h:“Thank goodness.] | [h:You’re back.”]',
        note: '**해석 도움** — 마침내 Arthur의 숨소리를 다시 듣고 **속으로** "다행이다. 돌아왔구나."라고 생각한다 → 마지막 심경 **relieved**(안도한). 정답 ⑤ {desperate → relieved}.',
        points: [
          ['grammar', '**[수업 필기] 분사구문 thinking** — {again, thinking ~} = {and he thought to himself}. 쉼표(동그라미) 뒤 {-ing}.'],
          ['grammar', '**think to oneself** — "**속으로 생각하다**". 주어가 Jeevan 이라 재귀대명사 {himself}.'],
          ['grammar', '**[수업 필기] S + was able to** — S {Jeevan} V {was able to hear}. {be able to} = {can} 의 과거.'],
          ['reading', '**심경 단서 ②** — {Finally}, {Thank goodness} → **relieved**. ①~④ 는 처음·끝 감정이 모두 맞지 않는다.'],
        ],
      },
    ],
    prompt: `Photorealistic interior photograph, wide banner composition. An empty small theater stage right after a performance with the bright house lights on: a deep red velvet curtain half open, a single wooden chair, a white first-aid kit resting near the corner of the stage, soft warm wooden floorboards. Calm, hopeful after-the-crisis mood. ${LIGHT}, warm cream, soft red and light wood tones. ${NO}, ticket machines, monkeys, train station --ar 16:5 --v 8.1`,
  },

  /* ── 03 요지 주장 추론 ───────────────────────────── */
  {
    no: 3, exam: EXAM, type: '요지', answer: 3,
    question: '다음 글의 요지로 가장 적절한 것은?',
    summary: '우리의 감정은 인간이라는 종의 생존에 기여해 왔기 때문에 존재한다고 여겨져요. 두려움은 위험을 피하게, 분노 표현은 위협을 쫓아내게, 긍정적인 감정 표현은 다른 사람과 유대를 맺게 도와요. 진화적으로 감정은 주의·지각·기억 등을 지휘하는 일종의 ‘프로그램’이며, 감정이 생존과 적응을 돕지 않았다면 우리와 함께 진화하지 않았을 거예요.',
    mainIdea: 'Emotions exist because they have helped us survive as a species.',
    titleEn: 'Why We Have Emotions: Tools for Survival',
    ko: [
      '우리의 감정은 그것이 하나의 종으로서 우리의 생존에 기여해 왔기 때문에 존재한다고 여겨진다.',
      '두려움은 우리가 위험을 피하도록 도와 왔고, 분노를 표현하는 것은 우리가 위협을 쫓아내도록 도우며, 긍정적인 감정을 표현하는 것은 우리가 다른 사람들과 유대를 맺도록 돕는다.',
      '진화적 관점에서, 감정은 일종의 ‘프로그램’으로, 작동되면 우리 활동의 많은 부분(주의, 지각, 기억, 움직임, 표정 등을 포함하여)을 지휘한다.',
      '예를 들어, 두려움은 우리를 매우 주의 깊게 만들고, 우리의 지각적 초점을 위협적인 자극으로 좁히며, 우리가 상황에 맞서거나(싸움) 그것을 피하게(도망) 하고, 경험을 더 예리하게 기억하게 할 수도 있다(미래에 그 위협을 피할 수 있도록).',
      '감정이 우리의 체계를 활성화하는 구체적인 방식과 상관없이, 우리가 가진 구체적인 감정들은 오래전 그것들이 우리가 (하나의 종으로서) 환경 속의 어려움을 이겨 내고 살아남도록 도왔기 때문에 존재한다고 여겨진다.',
      '만약 감정이 우리가 적응하고 살아남도록 돕지 않았다면, 그것은 우리와 함께 진화하지 않았을 것이다.',
    ],
    choices: [
      ['과거의 경험이 현재의 감정에 영향을 미친다.', '경험과 감정의 **관계**는 다루지 않는다.'],
      ['문명의 발달에 따라 인간의 감정은 다양화되어 왔다.', '**문명 발달**은 언급되지 않는다. 핵심은 **생존**이다.'],
      ['감정은 인간이 생존하도록 도와왔기 때문에 존재한다.', '첫 문장과 5번 문장이 반복하는 요지 — **정답**.'],
      ['부정적인 감정은 긍정적인 감정보다 더 오래 기억된다.', '두려움의 **기억 효과**는 예시일 뿐, 긍정 감정과 비교하지 않는다.'],
      ['두려움의 원인을 파악함으로써 두려움을 없앨 수 있다.', '두려움을 **없애는 방법**은 없다. 두려움은 오히려 **쓸모 있다**.'],
    ],
    vocab: [
      'be thought to|숙|~라고 여겨지다|be believed to|—|—',
      'contribute to|숙|~에 기여하다|add to|—|contribution 기여',
      'species|명|종(種)|kind|—|—',
      'avoid|동|피하다|escape|face 직면하다|avoidance 회피',
      'scare off|숙|겁주어 쫓아내다|frighten away|attract 끌어들이다|scary 무서운',
      'threat|명|위협|danger|—|threaten 위협하다',
      'bond with|숙|~와 유대를 맺다|connect with|—|bond 유대',
      'evolutionary|형|진화의|—|—|evolution 진화',
      'perspective|명|관점|viewpoint|—|—',
      'trigger|동|작동시키다, 유발하다|cause, set off|—|—',
      'direct|동|지휘하다, 이끌다|guide, control|—|direction 방향',
      'perception|명|지각, 인식|awareness|—|perceive 인지하다',
      'attentive|형|주의 깊은|alert|careless 부주의한|attention 주의',
      'narrow|동|좁히다|limit|widen 넓히다|narrowly 좁게',
      'perceptual|형|지각의|—|—|perception 지각',
      'stimulus|명|자극 (복수 stimuli)|trigger|—|stimulate 자극하다',
      'acutely|부|예리하게, 강하게|sharply|dully 둔하게|acute 예리한',
      'flight|명|도망, 도피|escape|fight 싸움|flee 도망치다',
      'specific|형|구체적인, 특정한|particular|general 일반적인|specifically 구체적으로',
      'activate|동|활성화하다|start|deactivate 비활성화하다|active 활동적인',
      'possess|동|소유하다, 지니다|have, own|—|possession 소유',
      'adapt|동|적응하다|adjust|—|adaptation 적응',
      'evolve|동|진화하다|develop|—|evolution 진화',
      'regardless of|숙|~와 상관없이|despite|—|—',
    ],
    flow: [
      ['🧬', '주장 — 감정은 생존을 도왔다', '감정은 **종으로서의 생존에 기여**했기 때문에 존재한다고 여겨진다(첫 문장 = 요지).'],
      ['😨', '예시 — 두려움·분노·긍정 감정', '두려움은 **위험 회피**, 분노 표현은 **위협 퇴치**, 긍정 감정 표현은 **유대** 형성을 돕는다.'],
      ['⚙️', '설명 — 감정은 일종의 프로그램', '작동되면 주의·지각·기억·움직임을 지휘한다. 두려움 → 집중, 싸움 또는 도망, **예리한 기억**.'],
      ['✅', '결론 — ③ 생존을 도왔기 때문에 존재', '돕지 않았다면 **진화하지 않았을 것**(가정법 과거완료). 정답 ③.'],
    ],
    cards: [
      {
        covers: [1],
        tags: ['title'],
        en: 'Our emotions [g:are thought to exist] | [r:because] [h:they] have [g:contributed to] our survival as a species.',
        note: '**해석 도움** — "우리의 감정은 종으로서 우리의 **생존에 기여해 왔기 때문에** 존재한다고 **여겨진다**." 글 전체의 **요지**가 첫 문장에 있다(5번에서 반복).',
        points: [
          ['grammar', '**[수업 필기] be thought to** — "~라고 **여겨지다**". {People think that our emotions exist ~} 의 수동 표현.'],
          ['reading', '**[수업 필기] they = Our emotions** — 화살표로 연결한 지칭. 감정이 생존에 기여했다.'],
          ['grammar', '**contribute to + 명사** — "~에 기여하다". {to} 는 전치사. 현재완료 {have contributed} 는 오래전부터 **지금까지**.'],
          ['vocab', '**species** — "**종**". 단수·복수 형태가 같다({a species}).'],
        ],
      },
      {
        covers: [2],
        en: '[h:Fear] has helped us [g:avoid] dangers, | [h:expressing anger] [g:helps] us scare off threats, | and [h:expressing positive emotions] [g:helps] us bond with others.',
        note: '**해석 도움** — 감정이 생존을 도운 **세 가지 예** A, B, and C: 두려움 → 위험 회피 / 분노 표현 → 위협 쫓기 / 긍정 감정 표현 → 유대.',
        points: [
          ['grammar', '**help + 목적어 + 동사원형(to부정사)** — {helped us avoid}, {helps us scare off}, {helps us bond}. 목적어 뒤 **원형**이 온다.'],
          ['grammar', '**[수업 필기] 동명사 주어 → 단수 동사** — {expressing anger}(S) → {helps}, {expressing positive emotions}(S) → {helps}. 동명사구 주어는 **단수** 취급.'],
          ['vocab', '**scare off / bond with** — 겁주어 쫓아내다 / ~와 유대를 맺다.'],
        ],
      },
      {
        covers: [3],
        en: 'From an evolutionary perspective, | an emotion is a kind of “program” | [r:that], [h:when triggered], [g:directs] many of our activities | (including attention, perception, memory, movement, expressions etc.).',
        note: '**해석 도움** — 감정은 일종의 ‘**프로그램**’으로, **작동되면** 우리 활동의 많은 부분을 **지휘한다**. 괄호 안은 그 활동의 예(주의·지각·기억·움직임·표정).',
        points: [
          ['grammar', '**[수업 필기] 주격 관계대명사 that + 동사 directs** — 선행사 {“program”}(단수) ← [{that ~ directs}]. 관계사절 동사도 **단수** {directs}.'],
          ['grammar', '**[수업 필기] 삽입 when triggered (p.p.)** — {when (it is) triggered}. 접속사 뒤 **주어+be동사 생략**, 과거분사만 남았다. "**작동될 때**".'],
          ['vocab', '**trigger / direct / including** — 작동시키다·유발하다 / 지휘하다 / ~을 포함하여.'],
        ],
      },
      {
        covers: [4],
        en: 'For example, [h:fear] [g:makes] us very attentive, | [g:narrows] our perceptual focus to threatening stimuli, | [g:will cause] us [r:either to face] a situation (fight) [r:or avoid] it (flight), | and [g:may cause] us [r:to remember] an experience more acutely | ([r:so that] we avoid the threat in the future).',
        note: '**해석 도움** — 주어는 {fear} 하나, 동사가 **넷**: 주의 깊게 **만들고**(V1) / 초점을 **좁히고**(V2) / 맞서거나 피하게 **하고**(V3) / 더 예리하게 기억하게 **할 수 있다**(V4).',
        points: [
          ['grammar', '**[수업 필기] 동사 4개 병렬** — {makes}(V1), {narrows}(V2), {will cause}(V3), {may cause}(V4). 주어 {fear} 가 모두의 주어다.'],
          ['grammar', '**[프린트 노트] make + 목적어 + 목적보어** — "~을 ~하게 만들다". {Fear makes us very attentive.}'],
          ['grammar', '**[수업 필기] cause + 목적어 + to부정사** — {cause us to face / to remember}(동그라미 {to}). / **[프린트 노트] either A or B** — "A, B 둘 중 하나": {either to face ~ or (to) avoid ~}.'],
          ['grammar', '**[수업 필기] so that + S + V** — "S가 V하기 **위해서**". {so that we avoid the threat}. / {face} 는 동사 "**직면하다**"(필기).'],
        ],
      },
      {
        covers: [5],
        tags: ['title'],
        en: '[r:Regardless of] the specific ways [g:in which] they activate our systems, | [h:the specific emotions] we possess [g:are thought to exist] | because they have helped us (as a species) survive challenges within our environment long ago.',
        note: '**해석 도움** — 감정이 작동하는 방식이 **무엇이든**, 우리가 가진 감정은 오래전 우리가 환경 속 **어려움을 이겨 내고 살아남도록 도왔기 때문에** 존재한다 — 첫 문장의 **요지 재진술**.',
        points: [
          ['grammar', '**[수업 필기] 전치사 + 관계대명사 in which** — {the specific ways in which they activate ~}. 화살표처럼 {in which} 가 {ways} 를 꾸민다(= {how}).'],
          ['grammar', '**[수업 필기] 목적격 관계대명사 생략 + 수 일치** — {the specific emotions (that) we possess} 가 주어(S) → 동사 {are}. 괄호 [ ] 를 묶고 S–V 를 잇는다.'],
          ['vocab', '**regardless of** — "~와 **상관없이**". / {help us survive} help + 목적어 + **동사원형**.'],
        ],
      },
      {
        covers: [6],
        en: '[r:If] they [g:had not helped] us adapt and survive, | they [g:would not have evolved] with us.',
        note: '**해석 도움** — "(실제로는 도왔지만) **만약** 감정이 우리가 적응하고 살아남도록 **돕지 않았다면**, 우리와 함께 **진화하지 않았을 것이다**." 과거 사실의 **반대**를 가정한다.',
        points: [
          ['grammar', '**[수업 필기·프린트 노트] 가정법 과거완료 — 과거 사실의 반대** — {If + S + had p.p. ~, S + would(조동사 과거형) + have p.p.} "만약 ~했다면, ~했을 것이다".'],
          ['grammar', '**[수업 필기] 가정법 과거 — 현재 사실의 반대** — {If + S + 과거동사 ~, S + would + 동사원형} "만약 ~라면, ~할 텐데".'],
          ['grammar', '**[수업 필기] 조건문(직설법)** — {If + S + V(현재) ~, S + will/can/may/should + 동사원형}. 실제로 일어날 수 있는 일.'],
          ['reading', '**요지 확인** — 돕지 않았다면 진화하지 않았다 = 감정은 **생존을 도왔기 때문에 존재** → 정답 ③.'],
        ],
      },
    ],
    prompt: `Photorealistic nature photograph, wide banner composition. A young wild deer standing alert at the edge of a bright open meadow, ears raised and head turned, sensing something in the distance, tall grass and a soft forest edge behind it. Calm but watchful mood that suggests instinct and survival. ${LIGHT}, fresh spring green, soft beige and pale sky blue. ${NO}, predators, blood, stage, office --ar 16:5 --v 8.1`,
  },

  /* ── 04 주제 제목 추론 ───────────────────────────── */
  {
    no: 4, exam: EXAM, type: '주제', answer: 4,
    question: '다음 글의 주제로 가장 적절한 것은?',
    summary: 'AI는 노동 시장에서 불리한 위치에 있는 노동자들의 직장 접근성을 개선해 포용성을 높일 수 있어요. 시각·언어·청각 장애가 있는 노동자를 돕는 AI 보조 장치가 널리 퍼지고 있고, 음성 인식과 실시간 자막은 동료와의 소통을 쉽게 해요. 또한 실시간 번역과 AI 텍스트 생성기는 저숙련 노동자와 비원어민의 업무 능력을 즉시 향상시켜요.',
    mainIdea: 'AI can make the workplace more inclusive by supporting workers who are at a disadvantage.',
    titleEn: 'How AI Supports Disadvantaged Workers',
    ko: [
      '노동 시장에서 일반적으로 불리한 위치에 있는 노동자들을 위해 직장의 접근성을 개선함으로써, AI는 직장 내 포용성을 향상시킬 수 있다.',
      '시각, 언어 또는 청각에 어려움이 있는 노동자들을 돕는 AI 기반 보조 장치가 더 널리 보급되고 있으며, 장애가 있는 사람들의 일에 대한 접근성과 일의 질을 향상시키고 있다.',
      '예를 들어, (신경 장애로 인한) 구음 장애가 있는 사람들을 위한 음성 인식 솔루션이나 청각 장애인과 난청인을 위한 실시간 자막 시스템은 동료와의 의사소통과 대인 의사소통이 필요한 직업에 대한 접근을 용이하게 할 수 있다.',
      'AI는 또한 저숙련 노동자들의 능력을 향상시킬 수 있으며, 그들의 임금과 경력 전망에 잠재적으로 긍정적인 영향을 줄 수 있다.',
      '예를 들어, 글과 말을 실시간으로 번역하는 AI의 능력은 직장에서 비원어민 화자들의 업무 수행을 향상시킬 수 있다.',
      '게다가, AI 기반 텍스트 생성기의 최근 발전은 글쓰기, 코딩 또는 고객 서비스와 같은 영역에서 숙련도가 더 낮은 사람들의 업무 수행을 즉시 향상시킬 수 있다.',
    ],
    choices: [
      ['jobs replaced by AI in the labour market', 'AI가 **일자리를 대체**한다는 내용은 없다.'],
      ['ethical issues caused by using AI in the workplace', '**윤리적 문제**는 언급되지 않는다.'],
      ['necessity of using AI technology for language learning', '번역은 업무 수행 예시일 뿐, **언어 학습**이 주제가 아니다.'],
      ['impacts of AI on supporting workers with disadvantages', '불리한 노동자를 **돕는** AI의 영향 — **정답**.'],
      ['new designs of AI technology to cure people with disabilities', '장애를 **치료**하는 기술이 아니라 **일을 돕는** 기술이다.'],
    ],
    vocab: [
      'improve|동|향상시키다|enhance|worsen 악화시키다|improvement 향상',
      'accessibility|명|접근성|availability|—|accessible 접근 가능한',
      'typically|부|일반적으로, 보통|usually|—|typical 전형적인',
      'disadvantage|명|불리한 위치, 불리|drawback|advantage 유리|disadvantaged 불우한',
      'labour market|명|노동 시장|job market|—|—',
      'inclusiveness|명|포용성, 포함함|—|exclusiveness 배타성|inclusive 포괄적인',
      'assistive|형|보조의|supportive|—|assist 돕다',
      'device|명|장치|tool, gadget|—|devise 고안하다',
      'aid|동|돕다|help, assist|—|—',
      'access|명|접근, 이용|entry|—|accessible 접근 가능한',
      'recognition|명|인식|identification|—|recognize 인식하다',
      'captioning|명|자막 넣기|subtitling|—|caption 자막',
      'deaf|형|청각 장애가 있는|hearing-impaired|—|deafness 청각 장애',
      'facilitate|동|용이하게 하다|ease, help|hinder 방해하다|facility 시설',
      'colleague|명|동료|coworker|—|—',
      'inter-personal|형|대인 관계의|social|—|person 사람',
      'enhance|동|향상시키다|improve, boost|weaken 약화시키다|enhancement 향상',
      'capability|명|능력|ability|inability 무능|capable 할 수 있는',
      'wage|명|임금|pay, salary|—|—',
      'prospect|명|전망|outlook|—|prospective 장래의',
      'translate|동|번역하다|interpret|—|translation 번역',
      'non-native|형|모국어가 아닌|foreign|native 원어민의|—',
      'generator|명|생성기|—|—|generate 생성하다',
      'instantly|부|즉시|immediately|—|instant 즉각적인',
      'domain|명|영역|field, area|—|—',
      'dysarthric|형|(신경 장애로 인한) 구음 장애의|—|—|dysarthria 구음 장애',
    ],
    flow: [
      ['🤖', '주제 — AI가 포용성을 높인다', '불리한 노동자의 **직장 접근성**을 개선해 AI가 직장 내 **포용성**을 향상시킨다.'],
      ['🦻', '도움 1 — 장애가 있는 노동자', 'AI 보조 장치 확산: **음성 인식**·**실시간 자막**이 동료와의 소통과 일자리 접근을 돕는다.'],
      ['📈', '도움 2 — 저숙련·비원어민 노동자', '{also} — **실시간 번역**, **AI 텍스트 생성기**가 저숙련·비원어민의 업무 수행을 즉시 높인다.'],
      ['✅', '정답 — ④ 불리한 노동자를 돕는 AI의 영향', '① 일자리 대체 ② 윤리 문제 ③ 언어 학습 ⑤ 장애 치료는 **언급되지 않는다**. 정답 ④.'],
    ],
    cards: [
      {
        covers: [1],
        tags: ['title'],
        en: '[r:By improving] accessibility of the workplace for workers | [r:that] are typically at a disadvantage in the labour market, | [h:AI] [g:can improve] inclusiveness in the workplace.',
        note: '**해석 도움** — 불리한 노동자들을 위해 직장의 **접근성**을 개선**함으로써**, AI는 직장 내 **포용성**을 향상시킬 수 있다 — **주제문**.',
        points: [
          ['grammar', '**[수업 필기] by + -ing = ~함으로써** — {By improving ~}. 전치사 {by} 뒤 **동명사**.'],
          ['grammar', '**[수업 필기] 주격 관계대명사 that** — 선행사 {workers} ← [{that are typically at a disadvantage ~}]. 화살표처럼 앞 명사를 꾸민다.'],
          ['grammar', '**[수업 필기] 주어 AI (중요)** — 긴 부사구({By improving ~ market,}) 뒤에 진짜 주어 {AI} → 동사 {can improve}.'],
          ['vocab', '**at a disadvantage / inclusiveness** — "**불리한 위치에**" / "**포용성**"({include} 포함하다).'],
        ],
      },
      {
        covers: [2],
        en: '[h:AI-powered assistive devices] [r:to aid] workers with visual, speech or hearing difficulties | [g:are becoming] more widespread, | [r:improving] the access to, and the quality of work for people with disabilities.',
        note: '**해석 도움** — 주어는 {AI-powered assistive devices}(AI 기반 보조 장치), {to aid ~} 는 그 장치를 꾸미고, 동사는 {are becoming} 이다. 뒤의 {improving ~} 은 결과를 덧붙이는 분사구문.',
        points: [
          ['grammar', '**[수업 필기] 주어 + to부정사(형용사적 용법) → 동사** — S {devices} ← [{to aid workers ~ difficulties}] → V {are}. 괄호 끝에서 동사를 찾는다.'],
          ['grammar', '**[수업 필기] 분사구문 improving** — 쉼표(동그라미) 뒤 {improving ~} = {and they improve ~}.'],
          ['grammar', '**두 명사가 목적어 공유** — {the access to, and the quality of + work} = 일**에 대한 접근**과 일**의 질**. 쉼표 뒤 {to} 와 {of} 가 함께 {work} 를 받는다.'],
          ['vocab', '**[수업 필기] visual, speech or hearing** — 세 형용사 병렬(체크 표시). {AI-powered} AI 기반의, {assistive} 보조의, {aid} 돕다.'],
        ],
      },
      {
        covers: [3],
        en: '[r:For example], [h:speech recognition solutions] for people with dysarthric voices [r:or] [h:live captioning systems] for deaf and hard of hearing people | [g:can facilitate] communication with colleagues and access to jobs | [r:where] inter-personal communication is necessary.',
        note: '**해석 도움** — 주어가 **둘**: 음성 인식 솔루션(S1) **또는** 실시간 자막 시스템(S2) → 동사 {can facilitate}. 동료와의 **소통**과 대인 소통이 필요한 **일자리 접근**을 쉽게 한다.',
        points: [
          ['grammar', '**[수업 필기] S1 or S2 → V** — {solutions (for ~)} 와 {systems (for ~)} 가 {or} 로 묶인 주어. 괄호 수식을 걷어내면 → {can facilitate}.'],
          ['grammar', '**[수업 필기] 관계부사 where** — 선행사 {jobs} ← {where inter-personal communication is necessary}(물결 표시). = {in which}.'],
          ['vocab', '**[각주] dysarthric** — "(신경 장애로 인한) **구음(構音) 장애의**". / {hard of hearing} 난청의, {facilitate} 용이하게 하다, {colleague} 동료.'],
        ],
      },
      {
        covers: [4],
        en: 'AI can [r:also] [g:enhance] the capabilities of [h:low-skilled] workers, | [g:with] potentially positive effects on their wages and career prospects.',
        note: '**해석 도움** — {also}(또한)로 **두 번째 도움**으로 넘어간다: 장애가 있는 노동자 → **저숙련 노동자**. 그들의 임금과 경력 전망에도 좋은 영향을 줄 수 있다.',
        points: [
          ['reading', '**[수업 필기] also + low-skilled** — 동그라미 친 {also} 가 글의 2단 구조 신호. {low-skilled} → 5번 {non-native}, 6번 {lower-skilled} 로 이어지는 "**불리한 노동자**" 계열(화살표).'],
          ['grammar', '**with + 명사 (부대 상황)** — {with potentially positive effects on ~} "~에 잠재적으로 긍정적인 영향을 **주면서**".'],
          ['vocab', '**effect on / enhance / capability** — ~에 대한 영향 / 향상시키다 / 능력.'],
        ],
      },
      {
        covers: [5],
        en: 'For example AI’s capacity [r:to translate] written and spoken word in real-time | [g:can improve] the performance of [h:non-native speakers] in the workplace.',
        note: '**해석 도움** — 주어 {AI’s capacity}(AI의 능력)를 {to translate ~}(실시간 번역하는)가 꾸미고, 동사는 {can improve} 다. ※ 인쇄본은 이 {For example} 뒤에 **쉼표가 없다**(원문 그대로).',
        points: [
          ['grammar', '**[수업 필기] 주어 + to부정사 수식 // 동사** — S {capacity} ← ({to translate ~ real-time}) // V {can improve}. 필기의 // 가 주어부와 동사의 경계.'],
          ['grammar', '**written and spoken** — 과거분사 두 개가 {word} 를 꾸민다: "**글로 쓰인 말과 입으로 하는 말**".'],
          ['vocab', '**[수업 필기] non-native** — "**모국어가 아닌**" 화자 = 비원어민(박스). {in real-time} 실시간으로.'],
        ],
      },
      {
        covers: [6],
        en: '[r:Moreover], recent developments [h:in AI-powered text generators] | [g:can instantly improve] the performance of lower-skilled individuals | in domains [r:such as] writing, coding or customer service.',
        note: '**해석 도움** — {Moreover}(게다가)로 예를 하나 더한다. AI 텍스트 생성기의 발전이 숙련도가 낮은 사람들의 업무 수행을 **즉시** 높인다.',
        points: [
          ['grammar', '**[수업 필기] 주어 + 전치사구 → 복수 동사** — S {developments} (in ~ generators) → V {can instantly improve}.'],
          ['reading', '**[수업 필기] 선택지 분석 — 정답 ④** — {impacts of AI on supporting workers with disadvantages}. ① {jobs replaced by AI} / ② {issues caused by ~} 는 **과거분사 후치수식**(화살표), ② {ethical} "**윤리적인, 도덕적인**", ⑤ {cure} "**치료하다**" — 모두 본문에 없다.'],
          ['vocab', '**such as / domain / instantly** — ~와 같은 / 영역 / 즉시.'],
        ],
      },
    ],
    prompt: `Photorealistic interior photograph, wide banner composition. A bright modern accessible office desk: an open laptop with a plain screen, a small hearing aid in its case, a lightweight microphone headset, a tactile braille keyboard and a smartphone on a stand, a potted plant and a large window behind. Inclusive, hopeful, clean workplace mood. ${LIGHT}, white, soft teal and light grey. ${NO}, screens with writing, robots, stage, monkeys --ar 16:5 --v 8.1`,
  },
];
