/* 봉영여중3 비상(김진완) Lesson 5 — Critical Minds 챕터 저작 데이터
 * 실행: node _author-L5.mjs  → data/L5/{1..5}.json */
import { writeChapter } from './_author.mjs';
import { SOURCE } from './_SOURCE-L5.js';

const LIGHT = 'natural soft diffused daylight, bright overcast sky, high-key exposure, low contrast, clean bright palette';
const NO = '--no text, letters, words, numbers, headline, logo, watermark, people, person, hands, faces, sunset, golden hour, night, dark moody grading, heavy shadows';

export const chapters = [
  /* ── Ch1 ─────────────────────────────────────────── */
  {
    no: 1, type: '주제', answer: 3,
    question: '다음 글의 주제로 가장 적절한 것은?',
    summary: '우리는 매일 흥미로운 뉴스를 보고 듣고 읽지만, 그 기사가 정말 사실인지 진지하게 생각해 본 적은 드물어요. 가짜 뉴스는 사람들이 정보를 덜 알게 하거나 잘못 이끌 수 있어 매우 해로워요. 그런데도 역사 속에는 다양한 가짜 뉴스가 있었어요. 왜 어떤 사람들은 거짓 정보를 썼을까요? 기사 뒤에 숨은 동기를 생각하며 몇 가지 기사를 살펴보자고 제안해요.',
    mainIdea: 'Fake news is harmful because it can leave people less informed or misled, so we should look into fake news articles and the hidden motives behind them.',
    titleEn: 'Can You Spot Fake News? Looking for the Motives behind False Stories',
    ko: [
      '매일 우리는 흥미로운 뉴스를 보거나 듣거나 읽는다.',
      '그러나 당신은 기사가 정말로 사실인지 진지하게 생각해 본 적이 있는가?',
      '모든 사람이 흥미로운 뉴스 기사를 좋아하지만, 만약 그것이 완전히 지어낸 것이라면 어떻게 할 것인가?',
      '가짜 뉴스는 사람들에게 정보를 부족하게 제공하거나 사람들을 잘못 이끌 수 있다는 점에서 매우 해로울 수 있다.',
      '그럼에도 불구하고, 역사를 통틀어 다양한 가짜 뉴스 보도들이 존재해 왔다.',
      '왜 어떤 사람들은 그러한 거짓 정보를 써 왔던 것일까?',
      '그 뒤에 숨겨진 동기를 생각하면서 몇 가지 기사를 살펴보자.',
    ],
    choices: [
      ['흥미로운 뉴스를 매일 접하는 것의 장점', '매일 뉴스를 접한다는 말은 **도입**일 뿐, 그 **장점**을 설명하지 않는다.'],
      ['뉴스 기사를 빠르게 읽는 방법', '글은 **빨리 읽는 법**이 아니라 기사가 **사실인지 의심해 보자**는 내용이다.'],
      ['가짜 뉴스의 해로움과 그 뒤에 숨은 동기', '가짜 뉴스가 **해롭다**({very harmful})는 점과, 거짓 기사를 쓴 **숨은 동기**({hidden motives})를 살펴보자는 제안을 모두 담은 **정답**이다.'],
      ['역사 속 유명한 기자들의 업적', '{throughout history} 는 가짜 뉴스가 **늘 있었다**는 뜻이지, **기자들의 업적**을 말하지 않는다.'],
      ['신문과 방송 뉴스의 차이점', '{watch, hear, or read} 는 뉴스를 접하는 방식일 뿐, 매체 간 **차이**를 비교하지 않는다.'],
    ],
    vocab: [
      'seriously|부|진지하게, 심각하게|earnestly|lightly 가볍게|serious 진지한',
      'consider|동|고려하다, 숙고하다|think about|ignore 무시하다|consideration 고려',
      'whether|접|~인지 (아닌지)|if|—|—',
      'article|명|(신문·잡지의) 기사|report, story|—|—',
      'completely|부|완전히|totally, entirely|partly 부분적으로|complete 완전한',
      'make up|동|(이야기 등을) 지어내다|invent, create|—|made-up 지어낸',
      'harmful|형|해로운|damaging|harmless 무해한|harm 해; 해치다',
      'in that|접|~라는 점에서|because, since|—|—',
      'informed|형|잘 아는, 정보를 가진|knowledgeable|uninformed 무지한|inform 알리다 / information 정보',
      'mislead|동|잘못 이끌다, 오해하게 하다|deceive|guide 올바로 안내하다|misleading 오해의 소지가 있는',
      'nevertheless|부|그럼에도 불구하고|however, still|—|—',
      'various|형|다양한|diverse|same 같은|variety 다양성 / vary 다르다',
      'report|명|보도|article, news|—|reporter 기자',
      'throughout|전|~ 내내, ~ 동안 죽|all through|—|—',
      'false|형|거짓의, 틀린|untrue, fake|true 사실인|falsehood 거짓',
      'look into|동|조사하다, 살펴보다|examine, investigate|—|—',
      'hidden|형|숨겨진|secret|open 드러난|hide 숨기다',
      'motive|명|동기|reason, purpose|—|motivate 동기를 부여하다',
    ],
    flow: [
      ['📰', '도입 — 매일 접하는 흥미로운 뉴스', '{Every day we watch, hear, or read interesting news.} 로 누구나 겪는 **일상**에서 출발한다.'],
      ['🤔', '질문 — 그 기사, 정말 사실일까?', '{However} 뒤 두 개의 **질문**으로 독자를 흔든다. 기사가 **사실인지** 의심해 봤는지, **지어낸 것이라면** 어떨지 묻는다.'],
      ['⚠️', '문제 — 가짜 뉴스의 해로움', '가짜 뉴스는 사람들을 **정보가 부족하게** 하거나 **잘못 이끌어** 해롭다. 그런데도({Nevertheless}) **역사 내내** 존재해 왔다.'],
      ['🔍', '예고 — 숨은 동기를 찾아서', '{Why have some people written ~?} 라는 질문 뒤, **숨은 동기**를 생각하며 **실제 기사들**을 살펴보자고 제안한다. 본문 2~4의 사례로 이어진다.'],
    ],
    cards: [
      {
        covers: [1, 2],
        en: '[h:Every day] we [g:watch, hear, or read] interesting news. | [r:However], [g:have you ever seriously considered] | [h:whether an article is really true]?',
        note: '**해석 도움** — {Every day}(부사구, 매일)와 {everyday}(형용사, 일상의)를 구분하자. {whether ~} 는 동사 {considered} 의 **목적어 명사절**로 "기사가 정말 사실**인지**"로 해석한다.',
        points: [
          ['grammar', '**동사의 병렬** — {watch, hear, or read} 처럼 같은 형태(동사원형) 셋을 {A, B, or C} 로 나열한다. 셋 다 {news} 를 목적어로 취한다.'],
          ['grammar', '**현재완료 경험 have you ever p.p.?** — "~해 본 적이 있는가?" {ever} 는 **경험**을 묻는 신호어다. 부사 {seriously} 는 {have} 와 {considered} 사이에 온다.'],
          ['grammar', '**명사절 접속사 whether** — "~인지 (아닌지)". 목적어절일 때는 {if} 로 바꿔 쓸 수 있지만, **주어 자리**나 **전치사 뒤**에서는 {whether} 만 쓴다.'],
          ['vocab', '**Every day vs. everyday** — {Every day}(두 단어)는 "매일"이라는 **부사구**, {everyday}(한 단어)는 "일상의"라는 **형용사**다. 시험 단골.'],
        ],
      },
      {
        covers: [3],
        en: 'Everyone likes an interesting news story | but [r:what if] it is [g:completely made up]?',
        note: '**해석 도움** — {what if ~?} 는 "만약 ~라면 어떻게 할 것인가?"라는 뜻의 **관용 표현**이다. {is made up} 은 **수동태**로 "지어내어진 것이다", 즉 "**꾸며낸 것**이다".',
        points: [
          ['grammar', '**Everyone + 단수동사** — {Everyone likes}. {everyone, everybody, each} 는 뜻은 "모두"여도 **단수 취급**한다.'],
          ['grammar', '**What if + 주어 + 동사 ~?** — {What (would happen) if ~?} 가 줄어든 형태. "만약 ~라면 어쩌지?"라는 **가정·걱정**을 나타낸다.'],
          ['vocab', '**make up 의 수동태 be made up** — {make up}(지어내다) → {be made up}(지어내어지다). {be made up of}(~로 구성되다)와 헷갈리지 말 것.'],
        ],
      },
      {
        covers: [4],
        en: 'Fake news [g:can be very harmful] | [r:in that] it can [g:make people less informed or even misled].',
        note: '**해석 도움** — {in that} 은 "~라는 점에서"라는 **접속사**로, 가짜 뉴스가 **왜 해로운지** 그 이유·측면을 밝힌다. {make + 목적어 + 과거분사} 는 "목적어가 ~된 상태가 되게 하다"이다.',
        points: [
          ['grammar', '**in that + 주어 + 동사** — "~라는 점에서". 전치사 {in} 뒤에는 원래 {that}절이 올 수 없지만 {in that} 은 **예외적으로** 쓰는 접속사다.'],
          ['grammar', '**5형식 make + 목적어 + 목적격 보어(p.p.)** — {make people (less) informed / misled}. 사람들이 정보를 **받는** 입장, 잘못 **이끌리는** 입장이라 **과거분사**를 쓴다.'],
          ['vocab', '**less informed** — "덜 알게 되는", 즉 **정보가 부족한** 상태. {even misled} 는 한 걸음 더 나아가 "**심지어** 잘못된 쪽으로 이끌린" 상태다({mislead-misled-misled}).'],
        ],
      },
      {
        covers: [5, 6],
        en: '[r:Nevertheless], [g:there have been] various fake news reports [h:throughout history]. | Why [g:have some people written] [h:such false information]?',
        note: '**해석 도움** — {Nevertheless} 는 "(해로운데도) **그럼에도 불구하고**"라는 **역접** 연결어다. {have been} 과 {have written} 은 둘 다 **현재완료 계속**으로 "역사 **내내 지금까지**"의 의미다.',
        points: [
          ['grammar', '**There have been + 복수명사** — "~이 (지금까지) 있어 왔다". 뒤의 {reports} 가 **진짜 주어**라 {have} 를 쓴다.'],
          ['grammar', '**현재완료 의문문** — {Why have some people written ~?}. {have} 가 주어 앞으로 나간다. {write-wrote-written}.'],
          ['vocab', '**such + (형용사) + 명사** — {such false information} "그러한 거짓 정보". {information} 은 **셀 수 없는 명사**라 {a} 나 {-s} 를 붙이지 않는다.'],
        ],
      },
      {
        covers: [7],
        en: '[g:Let’s look into] some articles | [r:thinking about] the hidden motives [h:behind them].',
        note: '**해석 도움** — {thinking about ~} 은 **분사구문**으로 "~을 **생각하면서**"라는 **동시 동작**을 나타낸다. {them} 은 앞의 {some articles} 를 가리킨다.',
        points: [
          ['grammar', '**분사구문(동시동작)** — {thinking about ~} = {while we think about ~}. 주절의 주어(we)가 **하면서** 하는 동작이다.'],
          ['vocab', '**look into** — "~을 조사하다, 들여다보다"({= examine}). {look at}(보다), {look for}(찾다), {look after}(돌보다)와 구분하자.'],
          ['reading', '**글의 방향 제시** — 숨은 **동기**({hidden motives})를 생각하며 읽자는 이 문장이 이후 두 가짜 기사(헤럴드, 데일리 텔레그램)를 읽는 **관점**이 된다.'],
        ],
      },
    ],
    prompt: `Photorealistic editorial still life photograph, wide banner composition. A clean light wooden desk seen from slightly above: a neatly folded blank newspaper with only soft grey column blocks, a smartphone lying face down, a pair of reading glasses and a large magnifying glass resting on the newspaper as if someone is checking whether a story is true. A small cup of tea at the right edge, lots of calm empty space. ${LIGHT}, soft white, pale wood and light grey. ${NO}, zoo, animals, rhinoceros, coal mine --ar 16:5 --v 8.1`,
  },

  /* ── Ch2 ─────────────────────────────────────────── */
  {
    no: 2, type: '내용일치', answer: 5,
    question: '다음 글의 내용과 일치하는 것은?',
    summary: '(기사 “끔찍한 참사”) 어젯밤 화난 코뿔소 떼가 동물원 우리를 부수고 탈출해 다른 야생 동물 우리도 부쉈고, 동물들이 거리를 달리며 수백 명을 다치게 했으며 12마리는 아직 잡히지 않았다는 기사예요. 하지만 기사 끝에는 “위의 어떤 일도 일어나지 않았다”고 적혀 있었어요. 끝까지 읽은 사람은 웃었지만, 끝까지 읽지 않은 사람들은 겁에 질려 도시를 빠져나가거나 총을 들고 공원으로 나갔어요. 헤럴드 사는 나중에 동물원의 안전하지 않은 상태에 독자들의 주의를 끌려고 기사를 지어냈다고 고백했어요.',
    mainIdea: 'The Herald made up a story about escaped zoo animals to draw readers’ attention to the unsafe conditions at the zoo, and people who did not read to the end panicked.',
    titleEn: 'Awful Disaster: A Fake Story to Warn about an Unsafe Zoo',
    ko: [
      '(기사 “끔찍한 참사”) 어젯밤, 화가 난 코뿔소 떼가 동물원 우리의 벽을 부수고 도망쳤다.',
      '그 코뿔소들은 또한 다른 야생 동물 우리의 벽도 부수었다.',
      '이 동물들은 거리를 뛰어다니며 수백 명의 사람들에게 부상을 입혔다.',
      '그중 열두 마리의 동물들이 아직 잡히지 않았다.',
      '시민들은 추후 안내가 있을 때까지 집 안에 머물러야 한다.',
      '위에 기술된 어떤 행동이나 사건도 일어나지 않았다.',
      '그 당시, 이 기사를 주의 깊게 읽었던 사람들은 크게 웃었다.',
      '그것을 끝까지 읽지 않은 사람들은 정말로 걱정하였다.',
      '그 기사가 거짓이라는 것을 알지 못했기 때문에, 많은 사람이 겁에 질려 어쩔 줄 몰랐다.',
      '어떤 사람들은 도시를 빠져나가려고 했고, 다른 사람들은 그 동물들을 사냥하기 위해 총을 들고 공원으로 나갔다.',
      '그렇다면 왜 헤럴드 사는 이러한 뉴스를 만들어 냈을까?',
      '나중에 그들은 동물원의 안전하지 않은 상태에 대해 독자들의 주의를 끌기 위해 그 기사를 지어냈다고 고백했다.',
    ],
    choices: [
      ['기사에 따르면 탈출한 동물은 모두 다시 잡혔다.', '{Twelve of the animals are still on the loose} — 기사는 12마리가 **아직 잡히지 않았다**고 썼다.'],
      ['기사 속 동물들은 공원에만 머물며 사람을 다치게 하지 않았다.', '기사 속 동물들은 **거리를 달리며** 수백 명을 **다치게 했다**({injured hundreds of people}).'],
      ['기사를 끝까지 읽은 사람들은 크게 걱정했다.', '주의 깊게 끝까지 읽은 사람들은 **크게 웃었다**({laughed out loud}). 걱정한 쪽은 **끝까지 읽지 않은** 사람들이다.'],
      ['헤럴드 사는 동물원의 인기를 높이려고 기사를 썼다.', '동물원의 **인기**가 아니라 **안전하지 않은 상태**({the unsafe conditions at the zoo})에 주의를 끌려는 것이었다.'],
      ['일부 사람들은 동물을 사냥하려고 총을 들고 공원에 갔다.', '{others went into the parks with guns to hunt the animals} 와 **일치**한다. **정답**.'],
    ],
    vocab: [
      'laugh out loud|동|크게 웃다|burst out laughing|—|laughter 웃음',
      'worried|형|걱정하는|anxious, concerned|relieved 안심한|worry 걱정하다',
      'rhinoceros|명|코뿔소|rhino|—|rhinoceroses 복수형',
      'break down|동|부수다, 허물다|destroy|build 짓다|breakdown 고장, 붕괴',
      'escape|동|탈출하다, 벗어나다|run away, flee|—|escape 탈출(명사)',
      'injure|동|부상을 입히다|hurt, wound|heal 치료하다|injury 부상',
      'on the loose|숙|(잡히지 않고) 도주 중인|at large, free|captured 잡힌|loose 풀린',
      'citizen|명|시민|resident|—|citizenship 시민권',
      'indoors|부|실내에서|inside|outdoors 야외에서|indoor 실내의',
      'until further notice|숙|추후 안내가 있을 때까지|—|—|notice 공지',
      'incident|명|사건|event, happening|—|incidental 부수적인',
      'describe|동|묘사하다, 기술하다|explain|—|description 묘사',
      'take place|동|일어나다, 발생하다|happen, occur|—|—',
      'panic|동|겁에 질려 어쩔 줄 모르다|freak out|calm down 진정하다|panicked 과거형 / panic 공황',
      'hunt|동|사냥하다|chase|—|hunter 사냥꾼',
      'confess|동|고백하다, 자백하다|admit|deny 부인하다|confession 고백',
      'draw attention to|숙|~에 주의를 끌다|call attention to|—|attention 주의',
      'unsafe|형|안전하지 않은|dangerous|safe 안전한|safety 안전',
      'condition|명|상태, 조건|state|—|conditional 조건부의',
    ],
    flow: [
      ['🦏', '가짜 기사 — 동물원 탈출 참사', '코뿔소 떼가 우리를 부수고 탈출 → 다른 동물 우리도 부숨 → 거리의 수백 명 부상 → 12마리 **도주 중** → 시민은 **실내 대기**. 긴박한 **기사체**다.'],
      ['📝', '반전 — 아무 일도 없었다', '{Not a single act or incident described above has taken place.} 기사 **끝**에 "위의 어떤 일도 **일어나지 않았다**"는 문장이 숨어 있었다.'],
      ['😱', '독자의 반응 — 웃음 vs. 공포', '끝까지 **주의 깊게 읽은** 사람은 **웃었고**, 끝까지 **읽지 않은** 사람은 겁에 질려 도시를 떠나거나 **총을 들고** 공원으로 갔다.'],
      ['🎯', '숨은 동기 — 동물원의 위험 알리기', '헤럴드 사는 **동물원의 안전하지 않은 상태**에 독자의 **주의를 끌기 위해**({so that they could draw ~}) 기사를 지어냈다고 **고백**했다.'],
    ],
    cards: [
      {
        covers: [1, 2],
        en: '[h:Last night], an angry group of rhinoceroses [g:broke down] the walls of the cage at the zoo [g:and escaped]. | They [h:also] [g:broke down] the walls of [r:the other wild animals’ cages].',
        note: '**해석 도움** — 주어는 {an angry group of rhinoceroses}(화가 난 코뿔소 **떼**)이고 동사 {broke down} 과 {escaped} 가 {and} 로 이어진다. {the other wild animals’ cages} 의 소유격 {animals’} 는 **복수명사의 소유격**이다.',
        points: [
          ['grammar', '**과거시제 동사의 병렬** — {broke down ~ and escaped}. 하나의 주어에 과거동사 둘이 이어진다({break-broke-broken}).'],
          ['grammar', '**복수명사의 소유격 -s’** — {animals’ cages}(동물들의 우리). {-s} 로 끝나는 복수명사는 **아포스트로피만** 붙인다. 단수는 {animal’s}.'],
          ['vocab', '**a group of + 복수명사** — "~의 무리, ~ 떼". {rhinoceros} 의 복수형은 {rhinoceroses}(또는 {rhinoceros}).'],
        ],
      },
      {
        covers: [3, 4, 5],
        en: 'These animals [g:ran down] the streets [g:and injured] [h:hundreds of people]. | [h:Twelve of the animals] are still [r:on the loose]. | Citizens [g:should stay] indoors [r:until further notice].',
        note: '**해석 도움** — {on the loose} 는 "잡히지 않고 **돌아다니는**", {until further notice} 는 "**추가 공지가 있을 때까지**"라는 뜻의 **뉴스 관용 표현**이다.',
        points: [
          ['vocab', '**hundreds of + 복수명사** — "수백의". 막연한 많은 수는 {hundreds of}, 정확한 수는 {two hundred people}(-s 없음).'],
          ['grammar', '**조동사 should + 동사원형** — "~해야 한다"는 **권고**. 뉴스 기사에서 시민에게 행동 지침을 줄 때 자주 쓴다.'],
          ['reading', '**기사체의 특징** — 시간({Last night}), 피해 규모({hundreds}), 숫자({Twelve}), 행동 지침({should stay indoors})까지 **진짜 기사처럼** 구체적이라 독자가 속기 쉽다.'],
        ],
      },
      {
        covers: [6],
        en: '[r:Not a single act or incident] [h:described above] | [g:has taken place].',
        note: '**해석 도움** — {Not a single ~} 은 "단 하나의 ~도 … 않다"는 **강한 부정**이다. {described above} 는 앞 명사를 꾸미는 **과거분사구**로 "위에서 **기술된**"이다.',
        points: [
          ['grammar', '**Not a single + 단수명사** — "단 하나도 ~ 않다". {No act ~ has taken place} 보다 **훨씬 강한** 부정이다. 주어가 단수라 {has}.'],
          ['grammar', '**과거분사의 후치 수식** — {act or incident (which was) described above}. 분사가 **구**를 이루면 명사 **뒤**에서 꾸민다.'],
          ['reading', '**반전의 핵심 문장** — 이 한 문장이 앞 기사 **전체를 부정**한다. 끝까지 읽은 사람만 이 문장을 봤다는 점이 다음 단락의 반응 차이를 만든다.'],
        ],
      },
      {
        covers: [7, 8],
        en: '[h:At that time], [g:those who] read the article carefully | laughed out loud. | [g:Those who] didn’t read it [r:to the end] | got really worried.',
        note: '**해석 도움** — {those who ~} 는 "~하는 **사람들**"이다. 첫 문장의 동사는 {laughed}, 둘째 문장의 동사는 {got} 이다 — {who} 뒤의 {read}/{didn’t read} 는 **관계절 안의 동사**다.',
        points: [
          ['grammar', '**those who + 동사** — "~하는 사람들"({= people who}). 복수 취급하며, 주절 동사를 찾을 때 **관계절을 괄호로** 묶어 보자.'],
          ['grammar', '**get + 형용사(과거분사)** — {got worried} "걱정하게 되었다". {get} 은 **상태의 변화**를 나타낸다.'],
          ['reading', '**대조 구조** — 주의 깊게 **끝까지 읽은** 사람 ↔ **끝까지 읽지 않은** 사람. **비판적 읽기**의 중요성이라는 단원 주제가 드러난다.'],
        ],
      },
      {
        covers: [9],
        en: '[r:Not knowing] the news was false, | many people [g:panicked].',
        note: '**해석 도움** — {Not knowing ~} 은 **부정 분사구문**으로 "~을 **알지 못했기 때문에**"라는 **이유**를 나타낸다. {knowing} 뒤에는 {that} 이 생략된 명사절 {(that) the news was false} 가 온다.',
        points: [
          ['grammar', '**분사구문의 부정** — {not} 은 분사 **앞**에 둔다. {Not knowing ~} = {Because they didn’t know ~}.'],
          ['grammar', '**panic 의 과거형 panicked** — {-ic} 로 끝나는 동사는 {-ed/-ing} 앞에 {k} 를 넣는다({panicked, panicking / picnicked}).'],
        ],
      },
      {
        covers: [10],
        en: '[h:Some] tried [r:to escape] the city | [g:while] [h:others] went into the parks with guns | [r:to hunt] the animals.',
        note: '**해석 도움** — {Some ~, others ...} 는 "어떤 사람들은 ~하고, 다른 사람들은 …하다"라는 **대조 구문**이다. 여기서 {while} 은 "~하는 반면"이라는 **대조**의 접속사다.',
        points: [
          ['grammar', '**Some ~ others ...** — 전체 중 **일부**와 **또 다른 일부**를 대비한다. 나머지 **전부**를 가리킬 땐 {the others}.'],
          ['grammar', '**try + to부정사** — {tried to escape} "탈출하려고 **애썼다**". {try + -ing} 는 "시험 삼아 ~해 보다".'],
          ['grammar', '**to부정사의 부사적 용법(목적)** — {to hunt the animals} "동물들을 **사냥하기 위해**".'],
        ],
      },
      {
        covers: [11, 12],
        en: 'So why did The Herald [g:make up] such news? | [h:Later], they [g:confessed] that they [g:made it up] | [r:so that they could draw] the readers’ attention | to the unsafe conditions at the zoo.',
        note: '**해석 도움** — {so that + 주어 + could ~} 는 "~할 수 있도록, ~하기 위해"라는 **목적**이다. {made it up} 처럼 **대명사 목적어**는 {make} 와 {up} **사이**에 온다.',
        points: [
          ['grammar', '**so that + 주어 + can/could** — "~하기 위해서"({= in order to}). 과거 문장이라 {could} 를 썼다.'],
          ['grammar', '**동사 + 부사 이어동사의 어순** — 대명사 목적어는 반드시 가운데: {made it up} (○) / {made up it} (×). 명사는 둘 다 가능: {make up such news}.'],
          ['vocab', '**draw one’s attention to ~** — "~에 …의 주의를 끌다". {the readers’ attention}(독자들의 주의) — 복수 소유격.'],
          ['reading', '**숨은 동기 ①** — 헤럴드 사의 동기는 **동물원의 안전 문제**를 알리려는 것이었다. 좋은 의도였어도 **많은 사람이 공포에 빠졌다**는 점을 함께 기억하자.'],
        ],
      },
    ],
    prompt: `Photorealistic documentary photograph, wide banner composition. An empty city zoo enclosure in the morning: a heavy old wooden fence and iron gate of a rhinoceros pen that looks worn out, cracked and rusty, with loose planks and a weak hinge, suggesting unsafe conditions. Behind it a quiet grassy paddock and trees, a single calm rhinoceros standing far in the background, nothing broken or chaotic. ${LIGHT}, soft greens, weathered wood and grey stone. ${NO}, guns, blood, crowds, city streets, newspaper --ar 16:5 --v 8.1`,
  },

  /* ── Ch3 ─────────────────────────────────────────── */
  {
    no: 3, type: '내용불일치', answer: 1,
    question: '다음 글의 내용과 일치하지 않는 것은?',
    summary: '(기사 “슬라브인이 언쟁 중에 친구에게 총을 쏘다”) 목요일 저녁, 컬럼비아 탄광의 슬라브인 노동자 Mejk Swenekafew가 채굴 야영지 근처에서 John Pecitello가 쏜 총에 맞아 크게 다쳤다는 기사예요. 두 사람은 회의 중 언쟁을 벌였고, 언쟁이 싸움으로 번져 Pecitello가 Swenekafew의 가슴과 다리에 두 번 총을 쐈어요. Swenekafew는 위독한 상태로 입원 중이고, Pecitello는 달아나 경찰이 그를 찾으며 시민들에게 경고하고 있어요.',
    mainIdea: 'A news article reports that a Slav worker named Mejk Swenekafew was shot by John Pecitello after an argument, and the police are searching for the dangerous shooter.',
    titleEn: 'Slav Shoots a Friend in Argument: The Second Fake Article',
    ko: [
      '(기사 “슬라브인이 언쟁 중에 친구에게 총을 쏘다”) 목요일 저녁 채굴 야영지 근처에서, 컬럼비아 광산 소속의 슬라브인 노동자 Mejk Swenekafew가 John Pecitello에 의해 총상을 입어 심각하게 다쳤다.',
      '그 두 사람은 회의 중에 언쟁을 벌였다.',
      '언쟁이 싸움으로 번졌고, Pecitello가 Swenekafew의 가슴과 다리에 두 번 총을 쏘았다.',
      '현재 그는 위독한 상태로 입원 중이다.',
      'Pecitello는 총격 이후 도주했다.',
      '경찰이 지금 그를 찾고 있으며, 그가 극히 위험하다고 시민들에게 경고하고 있다.',
    ],
    choices: [
      ['사건은 일요일 아침 광산 안에서 일어났다.', '사건은 **목요일 저녁**({Thursday evening}), 광산 안이 아니라 **채굴 야영지 근처**({near the mining camp})에서 일어났다. **불일치 — 정답**.'],
      ['Swenekafew는 컬럼비아 탄광의 노동자이다.', '{a Slav worker at the Columbia Coal Mine} 과 일치한다.'],
      ['두 사람은 회의 중에 언쟁을 벌였다.', '{The two men had an argument during a meeting.} 과 일치한다.'],
      ['Pecitello는 Swenekafew에게 총을 두 번 쏘았다.', '{Pecitello shot Swenekafew twice, in the chest and leg} 와 일치한다.'],
      ['경찰은 달아난 Pecitello를 찾고 있다.', '{Pecitello ran away ~} / {The police are searching for him now} 와 일치한다.'],
    ],
    vocab: [
      'Slav|명|슬라브인|—|—|Slavic 슬라브(인)의',
      'shoot|동|(총을) 쏘다|fire|—|shot 과거·과거분사 / shooting 총격',
      'argument|명|언쟁, 말다툼|quarrel, dispute|agreement 합의|argue 논쟁하다',
      'coal mine|명|탄광|colliery|—|coal 석탄 / miner 광부',
      'wound|동|상처를 입히다|injure, hurt|heal 낫게 하다|wound 상처(명사)',
      'mining camp|명|채굴 야영지, 광산촌|—|—|mine 광산',
      'lead to|동|~로 이어지다|result in, cause|—|led 과거형',
      'fight|명|싸움|struggle, clash|peace 평화|fighter 전사',
      'chest|명|가슴|breast|back 등|—',
      'critical|형|위독한, 대단히 중요한|serious, dangerous|stable 안정된|critically 위독하게',
      'condition|명|상태|state|—|—',
      'run away|동|달아나다|escape, flee|stay 머물다|runaway 도망자',
      'search for|동|~을 찾다|look for, seek|—|search 수색',
      'warn|동|경고하다|alert, caution|—|warning 경고',
      'extremely|부|극도로, 매우|very, highly|slightly 약간|extreme 극단적인',
    ],
    flow: [
      ['📰', '헤드라인 — 사건의 요약', '{SLAV SHOOTS A FRIEND IN ARGUMENT} — 누가(슬라브인) · 무엇을(총격) · 왜(언쟁) 를 **현재시제**로 압축한 **기사 제목**이다.'],
      ['📍', '리드 — 누가, 언제, 어디서', '첫 문장에 피해자(**Mejk Swenekafew**), 가해자(**John Pecitello**), 시간(**목요일 저녁**), 장소(**채굴 야영지 근처**)가 모두 담긴다.'],
      ['💥', '경위 — 언쟁에서 총격으로', '회의 중 **언쟁** → **싸움** → **가슴과 다리에 두 발**. 피해자는 **위독**한 상태로 입원 중이다.'],
      ['🚨', '현재 상황 — 도주와 수색', '가해자는 **도주**했고, 경찰은 그를 **찾으며** 시민들에게 그가 **극히 위험하다**고 경고한다. 이 **진짜 같은 기사**가 다음 단락의 반전으로 이어진다.'],
    ],
    cards: [
      {
        covers: [1],
        en: 'Mejk Swenekafew, [h:a Slav worker at the Columbia Coal Mine], | [g:was shot and seriously wounded] [r:by John Pecitello] | near the mining camp [h:Thursday evening].',
        note: '**해석 도움** — 콤마 사이 {a Slav worker ~} 는 Swenekafew 를 설명하는 **동격**이다. {was shot and (was) seriously wounded by ~} 는 **수동태** 두 개가 {and} 로 이어진 것으로, "~에 의해 총을 맞고 심하게 다쳤다".',
        points: [
          ['grammar', '**수동태 be + p.p. + by 행위자** — {was shot ~ by John Pecitello}. 기사는 **피해자**에 초점을 두므로 수동태로 쓴다.'],
          ['grammar', '**동격의 콤마** — {Mejk Swenekafew, a Slav worker at ~,}. 이름 뒤에서 **신분**을 보충한다.'],
          ['vocab', '**요일 앞 전치사 생략** — {Thursday evening} 처럼 기사체에서는 {on} 을 생략하기도 한다. 원래는 {on Thursday evening}.'],
        ],
      },
      {
        covers: [2, 3],
        en: 'The two men [g:had an argument] [h:during a meeting]. | The argument [g:led to] a fight, | and Pecitello [g:shot] Swenekafew [h:twice], [r:in the chest and leg].',
        note: '**해석 도움** — {lead to ~} 는 "~로 **이어지다**"라는 **인과** 표현이다. {in the chest and leg} 는 총을 맞은 **신체 부위**를 덧붙인다.',
        points: [
          ['grammar', '**during + 명사 / while + 절** — {during a meeting}(회의 **동안**). 뒤에 **주어+동사**가 오면 {while}: {while they were having a meeting}.'],
          ['vocab', '**lead to (led-led)** — "~로 이어지다, ~을 초래하다". 원인 → 결과의 흐름: **언쟁 → 싸움 → 총격**.'],
          ['vocab', '**신체 부위 앞의 the** — {shoot/hit + 사람 + in the + 부위}. {in the chest}(가슴을). 소유격({his})이 아니라 **the** 를 쓴다.'],
        ],
      },
      {
        covers: [4, 5],
        en: '[h:He] is now at the hospital [r:in critical condition]. | Pecitello [g:ran away] [h:after the shooting].',
        note: '**해석 도움** — {He} 는 총에 맞은 **Swenekafew** 를 가리킨다. {in critical condition} 은 "**위독한** 상태로"라는 뜻이다.',
        points: [
          ['reading', '**대명사 He 의 지칭** — 바로 앞 문장의 마지막 사람은 Swenekafew. 병원에 있는 쪽은 **피해자**, 달아난 쪽은 **Pecitello** 다.'],
          ['vocab', '**critical** — "비판적인"(Lesson 제목 Critical Minds) / "위독한"(in critical condition) / "대단히 중요한". **문맥**으로 뜻을 고르자.'],
        ],
      },
      {
        covers: [6],
        en: 'The police [g:are searching for] him now | [g:and are warning] citizens | [r:that] he is [h:extremely dangerous].',
        note: '**해석 도움** — {The police} 는 **복수 취급**하므로 {are} 를 쓴다. {warn + 사람 + that절} 은 "~에게 …라고 **경고하다**"이다.',
        points: [
          ['grammar', '**The police + 복수동사** — {police} 는 항상 **복수 취급**(경찰관들 전체). {The police is} (×).'],
          ['grammar', '**현재진행형의 병렬** — {are searching for ~ and are warning ~}. 기사 작성 시점에 **진행 중인** 상황을 전한다.'],
          ['grammar', '**warn + 목적어 + that절** — "~에게 …라고 경고하다". {tell/inform/remind + 사람 + that} 과 같은 구조다.'],
        ],
      },
    ],
    prompt: `Photorealistic historical documentary photograph, wide banner composition. An early twentieth century American coal mining camp in the hills: a wooden mine entrance with a timber frame, empty coal carts on narrow rails, small plain wooden cabins and a water tower, piles of dark coal beside a dirt road. Quiet and deserted, no action. ${LIGHT}, muted earthy browns, soft grey sky and pale dust. ${NO}, guns, blood, police, zoo, animals, newspaper --ar 16:5 --v 8.1`,
  },

  /* ── Ch4 ─────────────────────────────────────────── */
  {
    no: 4, type: '요지', answer: 4,
    question: '다음 글의 요지로 가장 적절한 것은?',
    summary: '앞의 기사에 뭔가 이상한 점이 있어요. 슬라브인 이름 Swenekafew를 거꾸로 읽으면 “we-fake-news(우리는 뉴스를 조작한다)”가 돼요. 데일리 텔레그램 사는 경쟁사 데일리 뉴스 사가 자신들의 기사를 훔치는지 증명하려고 이 가짜 기사를 실었어요. 데일리 뉴스 사는 다음 날 Swenekafew에 관한 똑같은 기사를 실어 기사를 훔친 것이 들통났고, 자신들의 행동을 인정하고 대중에게 혹독한 비난을 받았어요.',
    mainIdea: 'The Daily Telegram published a fake article with a hidden message, “we-fake-news,” to prove that its competitor, The Daily News, was stealing its articles.',
    titleEn: 'We Fake News: A Trap to Catch an Article Thief',
    ko: [
      '이 기사에 뭔가 이상한 점이 있는가?',
      '그 슬라브인의 이름을 거꾸로 읽어 보아라. 그것의 철자는 “우리는 뉴스를 조작한다.”가 된다.',
      '누가 이것을 썼고 왜 그랬을까?',
      '데일리 텔레그램 사는 그들의 경쟁자인 데일리 뉴스 사가 그들의 기사를 훔치는지를 증명하기 위해서 이 거짓 기사를 발행했다.',
      '데일리 뉴스 사는 그 다음 날 ‘Swenekafew’에 대한 동일한 기사를 발행했고 그래서 훔친 것이 발각되었다.',
      '데일리 뉴스 사의 사람들은 그들의 행동을 인정해야만 했고 대중으로부터 혹독한 비난을 받았다.',
    ],
    choices: [
      ['외국인 노동자의 안전을 위한 제도가 필요하다.', '슬라브인 노동자는 **가짜 기사 속 인물**일 뿐, 노동자 **안전 제도**는 다루지 않는다.'],
      ['신문사는 경쟁사와 협력해 기사를 써야 한다.', '두 신문사는 **협력**이 아니라, 한쪽이 다른 쪽의 **기사 도용을 잡아내는** 관계다.'],
      ['이름을 거꾸로 읽는 놀이는 독해력을 키운다.', '이름을 거꾸로 읽는 것은 **숨겨진 메시지**를 찾는 장치일 뿐, **독해력 훈련**을 말하지 않는다.'],
      ['한 신문사는 기사 도용을 밝히려고 가짜 기사를 썼다.', '데일리 텔레그램 사가 **경쟁사의 기사 도용을 증명하려고**({so that they could prove if ~}) 가짜 기사를 실었다는 핵심을 담은 **정답**이다.'],
      ['가짜 뉴스를 만든 신문사는 모두 처벌받았다.', '비난을 받은 쪽은 기사를 **훔친** 데일리 뉴스 사이고, **처벌**이 아니라 **대중의 비난**이다.'],
    ],
    vocab: [
      'strange|형|이상한|odd, unusual|normal 평범한|strangely 이상하게',
      'backwards|부|거꾸로, 뒤로|in reverse|forwards 앞으로|backward 뒤쪽의',
      'spell|동|철자를 쓰다, (철자가) ~가 되다|—|—|spelling 철자',
      'fake|형|가짜의, 조작된|false, made-up|real 진짜의|fake 조작하다(동사)',
      'publish|동|발행하다, 싣다|print, issue|—|publisher 출판사',
      'prove|동|증명하다|show, confirm|disprove 반증하다|proof 증거',
      'competitor|명|경쟁자, 경쟁사|rival|partner 협력자|compete 경쟁하다 / competition 경쟁',
      'steal|동|훔치다|take, rob|—|stole-stolen 과거·과거분사',
      'get caught|동|(나쁜 짓을 하다) 들키다|be caught|—|catch 잡다',
      'thus|부|그래서, 따라서|therefore, so|—|—',
      'admit|동|인정하다|confess|deny 부인하다|admission 인정',
      'harshly|부|혹독하게, 가혹하게|severely|gently 부드럽게|harsh 가혹한',
      'criticize|동|비난하다, 비판하다|blame|praise 칭찬하다|criticism 비판 / critical 비판적인',
      'public|명|대중, 일반 사람들|people, society|private 사적인(형)|publicly 공개적으로',
    ],
    flow: [
      ['❓', '의문 제기 — 이 기사, 이상하지 않은가?', '{Is there anything strange about the article?} 로 앞 기사를 **다시 보게** 만든다.'],
      ['🔄', '단서 — 이름을 거꾸로 읽으면', '{Swenekafew} 를 거꾸로 읽으면 **we-fake-news**. 기사 속에 **숨겨진 메시지**가 있었다.'],
      ['🪤', '숨은 동기 — 기사 도용을 잡는 덫', '데일리 텔레그램 사는 경쟁사 데일리 뉴스 사가 **기사를 훔치는지 증명하려고** 이 가짜 기사를 실었다.'],
      ['⚖️', '결과 — 들통난 도용과 비난', '다음 날 데일리 뉴스 사가 **똑같은 기사**를 실어 **도용이 발각**됐고, 잘못을 **인정**하며 **대중의 혹독한 비난**을 받았다.'],
    ],
    cards: [
      {
        covers: [1, 2, 3],
        en: 'Is there [h:anything strange] about the article? | [g:Read] the Slav’s name [r:backwards]; it [g:spells] “we-fake-news.” | Who wrote this [h:and why]?',
        note: '**해석 도움** — {anything strange} 처럼 {-thing} 으로 끝나는 대명사는 형용사가 **뒤에서** 꾸민다. {spell} 은 "(글자들이 모여) ~라는 **단어가 되다**"라는 뜻이다. {and why} 는 {and why did they write this} 가 줄어든 것.',
        points: [
          ['grammar', '**-thing + 형용사** — {anything strange}, {something interesting}. {-thing/-body/-one} 대명사는 형용사를 **뒤에** 둔다.'],
          ['grammar', '**명령문** — {Read the Slav’s name backwards} 는 동사원형으로 시작하는 명령문. 세미콜론({;}) 뒤에서 그 **결과**를 바로 보여 준다.'],
          ['vocab', '**spell** — "철자를 말하다/쓰다" 외에 "(철자를 이어 읽으면) **~가 되다**"라는 뜻. S-w-e-n-e-k-a-f-e-w 를 거꾸로 → **w-e-f-a-k-e-n-e-w-s**.'],
        ],
      },
      {
        covers: [4],
        en: 'The Daily Telegram [g:published] this fake article | [r:so that they could prove] | [h:if] The Daily News, [h:their competitor], | [g:was stealing] their articles.',
        note: '**해석 도움** — {so that they could prove ~} 는 "~을 **증명하기 위해**"라는 **목적**이다. {if} 는 여기서 "만약"이 아니라 "~**인지**"라는 **명사절 접속사**다(= whether).',
        points: [
          ['grammar', '**so that + 주어 + could** — 목적 "~하기 위해". 본문 2의 {so that they could draw ~} 와 **같은 구조** — 두 신문사 모두 **숨은 목적**이 있었다.'],
          ['grammar', '**명사절 if(= whether)** — {prove if ~} "~인지 증명하다". 동사의 **목적어** 자리의 {if} 는 "~인지"로 해석한다.'],
          ['grammar', '**과거진행형 was stealing** — 기사를 **반복적으로 훔쳐 오고 있었는지**를 나타낸다. 동격 {their competitor} 는 콤마로 끼워 넣었다.'],
        ],
      },
      {
        covers: [5],
        en: 'The Daily News [g:published] the same article about “Swenekafew” [h:the next day] | and [r:thus] [g:got caught stealing].',
        note: '**해석 도움** — {thus} 는 "**그래서, 그 결과**". {get caught -ing} 는 "~하다가 **들키다**"라는 표현이다.',
        points: [
          ['grammar', '**get caught + -ing** — "~하다가 붙잡히다/들키다". {get + p.p.} 는 **수동**의 의미를 가진다({get hurt, get lost}).'],
          ['reading', '**덫에 걸리다** — 실존하지 않는 인물 Swenekafew 의 기사를 **그대로** 실었다는 것 자체가 **도용의 증거**가 됐다.'],
        ],
      },
      {
        covers: [6],
        en: 'The people at The Daily News [g:had to admit] their act | [g:and were harshly criticized] [r:by the public].',
        note: '**해석 도움** — {had to} 는 {must} 의 **과거**로 "~해야만 했다". {were criticized by the public} 은 **수동태**로 "대중에게 **비난받았다**".',
        points: [
          ['grammar', '**had to + 동사원형** — {must} 는 과거형이 없어 {had to} 로 쓴다. "인정할 수밖에 없었다".'],
          ['grammar', '**수동태 + 부사** — {were harshly criticized}. 부사 {harshly} 는 **be동사와 p.p. 사이**에 온다.'],
          ['vocab', '**the public** — "대중". {the + 형용사} 꼴이지만 여기서는 **집합명사**로 쓰였다.'],
        ],
      },
    ],
    prompt: `Photorealistic still life photograph, wide banner composition. An old-fashioned newspaper office desk: a vintage black typewriter, a stack of blank folded newspapers, a brass magnifying glass and a round mirror standing upright, the mirror reflecting a row of wooden letter blocks to suggest reading a word backwards, the blocks themselves blank and unreadable. Warm pale wood, tidy composition with open space. ${LIGHT}, cream, pale wood and soft black. ${NO}, coal mine, guns, zoo, animals --ar 16:5 --v 8.1`,
  },

  /* ── Ch5 ─────────────────────────────────────────── */
  {
    no: 5, type: '제목', answer: 2,
    question: '다음 글의 제목으로 가장 적절한 것은?',
    summary: '앞의 두 기사는 특별한 경우였지만, 매일 많은 “가짜” 뉴스 기사가 발행돼요. 그래서 독자인 우리는 비판적으로 읽고 뉴스가 진짜인지 가짜인지 판단해야 해요. 가짜 뉴스를 찾아내는 방법은 네 가지예요. ① 출처를 고려하라(믿을 만한 출처인가? 필자를 믿을 수 있는가?) ② 날짜를 확인하라(새 이야기인가, 오래된 이야기인가? 현재 사건과 관련 있는가?) ③ 제목 그 이상을 읽어라(제목이 내용과 일치하는가?) ④ 뒷받침하는 자료를 찾아라(다른 관련 기사도 비슷한 내용을 제공하는가?)',
    mainIdea: 'Since many fake news articles are published every day, readers need to read critically by checking the source, the date, the content beyond the headline, and supporting sources.',
    titleEn: 'How to Spot Fake News: Four Checks for Critical Readers',
    ko: [
      '이 두 기사는 특별한 경우였지만, 매일 발행되는 ‘가짜’ 뉴스 기사는 많이 있다.',
      '독자로서, 우리는 비판적으로 읽고 그 뉴스가 진짜인지 가짜인지 판단할 필요가 있다.',
      '(가짜 뉴스를 찾아내는 방법!) 출처를 고려하라',
      '그것은 믿을 만한 출처에서 온 것인가?',
      '우리는 그 필자를 신뢰할 수 있는가?',
      '날짜를 확인하라',
      '그것은 새로운 이야기인가 혹은 오래된 이야기인가?',
      '그것은 현재의 사건들과 관련된 것인가?',
      '기사 제목 그 이상을 읽어라',
      '기사 제목이 기사 내용과 일치하는가?',
      '뒷받침하는 자료를 찾아라',
      '다른 관련된 이야기도 비슷한 내용을 제공하는가?',
    ],
    choices: [
      ['Why Newspapers Love Special Cases', '두 기사가 **특별한 경우**였다는 말은 도입일 뿐, 신문사가 특별한 경우를 **좋아하는 이유**는 없다.'],
      ['Read Critically: How to Spot Fake News', '매일 쏟아지는 가짜 뉴스 속에서 **비판적으로 읽고**({read critically}) 가짜를 가려내는 **네 가지 방법**을 제시하는 글 전체를 담은 **정답**이다.'],
      ['How to Write an Exciting Headline', '제목(headline)은 **내용과 일치하는지 확인할** 대상일 뿐, **제목 쓰는 법**을 다루지 않는다.'],
      ['The Best Sources for Current Events', '출처와 현재 사건은 **점검 항목**의 일부일 뿐, **최고의 뉴스 출처**를 추천하지 않는다.'],
      ['Old Stories Are Always Fake News', '날짜를 **확인하라**고 했을 뿐, 오래된 이야기가 **항상 가짜**라고 말하지 않는다. 지나친 일반화다.'],
    ],
    vocab: [
      'special|형|특별한|unusual, exceptional|ordinary 평범한|specially 특별히',
      'case|명|경우, 사례|example, instance|—|—',
      'publish|동|발행하다|print, release|—|publication 출판(물)',
      'critically|부|비판적으로|carefully, analytically|blindly 맹목적으로|critical 비판적인 / criticize 비판하다',
      'judge|동|판단하다|decide, determine|—|judgment 판단 / judge 판사(명사)',
      'consider|동|고려하다|think about|ignore 무시하다|consideration 고려',
      'source|명|출처, 근원|origin|—|—',
      'reliable|형|믿을 만한|trustworthy, dependable|unreliable 믿을 수 없는|rely 의지하다 / reliability 신뢰성',
      'trust|동|신뢰하다|believe in|doubt 의심하다|trust 신뢰(명사)',
      'related|형|관련된|connected|unrelated 관련 없는|relate 관련시키다 / relation 관계',
      'current|형|현재의, 지금의|present|past 과거의|currently 현재',
      'beyond|전|~ 너머, ~ 이상|past, over|—|—',
      'headline|명|(기사) 제목|title|—|—',
      'match|동|일치하다, 어울리다|fit, agree with|differ 다르다|match 경기, 성냥(명사)',
      'content|명|내용|substance|—|contents 목차',
      'supporting|형|뒷받침하는|backing|—|support 지지하다',
      'similar|형|비슷한|alike|different 다른|similarity 유사성',
    ],
    flow: [
      ['🔁', '정리 — 두 사례는 특별한 경우', '헤럴드 사·데일리 텔레그램 사의 기사는 **특별한 경우**였다. 하지만 {but} 매일 **많은 가짜 뉴스**가 발행된다.'],
      ['🧠', '주장 — 비판적으로 읽어라', '{As readers, we need to read critically and judge ~} — 독자로서 **비판적으로 읽고** 진짜·가짜를 **판단**해야 한다. 이 단원의 **핵심 주장**이다.'],
      ['✅', '방법 ①② — 출처와 날짜', '**출처를 고려하라**: 믿을 만한가, 필자를 믿을 수 있는가. **날짜를 확인하라**: 새로운가 오래됐는가, 현재 사건과 관련 있는가.'],
      ['🔎', '방법 ③④ — 제목 너머와 뒷받침 자료', '**제목 너머를 읽어라**: 제목과 내용이 일치하는가. **뒷받침 자료를 찾아라**: 다른 기사도 비슷한 내용을 전하는가.'],
    ],
    cards: [
      {
        covers: [1],
        en: 'The two articles [g:were] special cases, | [r:but] [g:there are] many “fake” news articles | [h:published every day].',
        note: '**해석 도움** — {The two articles} 는 앞의 **헤럴드 사**와 **데일리 텔레그램 사** 기사다. {published every day} 는 {articles} 를 뒤에서 꾸미는 **과거분사구**로 "매일 **발행되는**"이다.',
        points: [
          ['grammar', '**과거분사의 후치 수식** — {articles (which are) published every day}. 기사는 **발행되는** 대상이라 수동의 **p.p.** 를 쓴다.'],
          ['grammar', '**There are + 복수명사** — 뒤의 {many ~ articles} 가 **진짜 주어**라 {are}.'],
          ['reading', '**따옴표 “fake”** — 앞의 두 기사처럼 **의도적 장치**가 아니라, 일상에서 쏟아지는 **이른바 가짜 뉴스**를 가리키려고 따옴표를 붙였다.'],
        ],
      },
      {
        covers: [2],
        en: '[r:As readers], we [g:need to read critically and judge] | [h:whether the news is real or fake].',
        note: '**해석 도움** — {As readers} 의 {as} 는 "~**로서**"라는 **자격**의 전치사다. {need to} 뒤에 동사원형 {read} 와 {judge} 가 {and} 로 **병렬**된다.',
        points: [
          ['grammar', '**전치사 as(자격)** — "~로서". {As readers}(독자로서). 접속사 {as}(~할 때, ~ 때문에)와 구분하자.'],
          ['grammar', '**to부정사 병렬** — {need to read ~ and (to) judge ~}. 두 번째 {to} 는 생략됐다.'],
          ['grammar', '**whether A or B** — "A인지 B인지". {whether the news is real or fake} 는 {judge} 의 **목적어 명사절**이다.'],
        ],
      },
      {
        covers: [3, 4, 5],
        en: '[g:CONSIDER] [h:the Source] | Is it from [r:a reliable source]? | Can we [g:trust] the writer?',
        note: '**해석 도움** — 체크리스트 제목({CONSIDER the Source})은 **명령문**, 그 아래 질문은 **스스로 점검할 항목**이다. {it} 은 **뉴스(기사)**를 가리킨다.',
        points: [
          ['grammar', '**명령문으로 된 소제목** — {CONSIDER / CHECK / READ / FIND} 네 항목 모두 **동사원형**으로 시작한다. 대문자는 **강조** 표시다.'],
          ['vocab', '**reliable** — {rely on}(의지하다) + {-able}(할 수 있는) → "**믿을 만한**". 반의어 {unreliable}.'],
          ['reading', '**점검 ① 출처** — **어디서** 나온 뉴스인가, **누가** 썼는가. 믿을 만한 기관·필자인지부터 확인한다.'],
        ],
      },
      {
        covers: [6, 7, 8],
        en: '[g:CHECK] [h:the Date] | Is it [r:a new or an old story]? | Is it [g:related to] [h:current events]?',
        note: '**해석 도움** — {a new or an old story} 는 {a new story or an old story} 를 줄인 것이다. {old} 는 **모음 소리**로 시작해 {an} 을 쓴다.',
        points: [
          ['grammar', '**a / an 의 구분** — 발음이 **모음**으로 시작하면 {an}: {an old story}, {an article}. 철자가 아니라 **발음** 기준이다({an hour}, {a university}).'],
          ['vocab', '**be related to** — "~와 관련되다". {current events} 는 "**시사**, 현재 일어나는 사건들".'],
          ['reading', '**점검 ② 날짜** — 오래된 기사가 **지금 일처럼** 다시 퍼지는 경우가 많다. **언제** 쓰인 이야기인지 확인한다.'],
        ],
      },
      {
        covers: [9, 10],
        en: '[g:READ BEYOND] [h:the Headlines] | Does the headline [g:match] [h:the content]?',
        note: '**해석 도움** — {beyond} 는 "~ **너머**, ~ **이상**"이다. 제목만 보지 말고 **본문까지** 읽으라는 뜻이다. {match} 는 여기서 "**일치하다**"라는 동사다.',
        points: [
          ['vocab', '**beyond** — "~을 넘어서". {READ BEYOND the Headlines} 는 "제목 **그 이상을** 읽어라".'],
          ['grammar', '**일반동사 의문문** — {Does the headline match ~?}. 주어가 **3인칭 단수**라 {Does} + **동사원형** {match}.'],
          ['reading', '**점검 ③ 제목 너머** — 본문 2의 헤럴드 사 기사가 바로 이 경우다. **끝까지 읽지 않은** 사람만 속았다.'],
        ],
      },
      {
        covers: [11, 12],
        en: '[g:FIND] [h:Supporting Sources] | Do [r:other related stories] [g:provide] [h:similar content]?',
        note: '**해석 도움** — {Supporting Sources} 는 "**뒷받침하는** 자료". 다른 관련 기사들도 **비슷한 내용**을 전하는지 **교차 확인**하라는 뜻이다.',
        points: [
          ['grammar', '**현재분사 형용사 supporting** — "뒷받침**하는**". 자료가 **능동적으로** 뒷받침하므로 {-ing}.'],
          ['grammar', '**복수 주어 의문문** — {Do other related stories provide ~?}. 주어가 **복수**라 {Do}.'],
          ['reading', '**점검 ④ 교차 확인** — 한 곳에서만 나온 이야기는 의심하자. 여러 **믿을 만한 출처**가 같은 내용을 전하는지 확인한다.'],
        ],
      },
    ],
    prompt: `Photorealistic flat lay photograph, wide banner composition. A bright white desk seen from directly above with four neat items in a row, like a checklist for spotting fake news: a small stack of trusted reference books, a desk calendar page with blank squares, a folded newspaper with the top half hidden under a sheet of paper, and three different blank newspapers overlapping side by side for comparison. A pencil and a magnifying glass nearby. ${LIGHT}, white, soft grey and light blue accents. ${NO}, typewriter, mirror, zoo, animals, coal mine --ar 16:5 --v 8.1`,
  },
];

if (process.argv[1]?.endsWith('_author-L5.mjs')) {
  console.log('✍️  L5 저작');
  for (const c of chapters) writeChapter('L5', SOURCE, c);
}
